# Generated by scripts/build-dsa-library-bridges.mjs
# Owner: src/learn/data/string-matching-examples.js; examples: kmp, stream
# Rebuild; do not maintain a second hand-edited implementation here.

def prefix_function(sequence):
    prefix = [0] * len(sequence)
    for position in range(1, len(sequence)):
        matched = prefix[position - 1]
        while matched > 0 and sequence[position] != sequence[matched]:
            matched = prefix[matched - 1]
        if sequence[position] == sequence[matched]:
            matched += 1
        prefix[position] = matched
    return prefix

def find_all(text, pattern):
    if not pattern:
        return list(range(len(text) + 1))
    prefix = prefix_function(pattern)
    matched = 0
    starts = []
    for position, symbol in enumerate(text):
        while matched > 0 and symbol != pattern[matched]:
            matched = prefix[matched - 1]
        if symbol == pattern[matched]:
            matched += 1
        if matched == len(pattern):
            starts.append(position - len(pattern) + 1)
            matched = prefix[matched - 1]
    return starts

class StreamMatcher:
    def __init__(self, pattern):
        self.pattern = pattern
        self.prefix = prefix_function(pattern)
        self.matched = 0
        self.offset = 0
        self.initial_boundary_emitted = False

    def feed(self, chunk):
        starts = []
        if not self.pattern and not self.initial_boundary_emitted:
            starts.append(0)
            self.initial_boundary_emitted = True
        for symbol in chunk:
            if not self.pattern:
                self.offset += 1
                starts.append(self.offset)
                continue
            while self.matched > 0 and symbol != self.pattern[self.matched]:
                self.matched = self.prefix[self.matched - 1]
            if symbol == self.pattern[self.matched]:
                self.matched += 1
            self.offset += 1
            if self.matched == len(self.pattern):
                starts.append(self.offset - len(self.pattern))
                self.matched = self.prefix[self.matched - 1]
        return starts
