# Generated by scripts/build-dsa-library-bridges.mjs
# Owner: src/learn/data/tree-examples.js; examples: deletion, orderedQueries, ceilingPractice
# Rebuild; do not maintain a second hand-edited implementation here.

class Node:
    def __init__(self, key, left=None, right=None):
        self.key, self.left, self.right = key, left, right

def insert(root, key):
    if root is None:
        return Node(key)
    current = root
    while True:
        if key == current.key:
            return root  # This is a set: ignore an existing key.
        side = "left" if key < current.key else "right"
        child = getattr(current, side)
        if child is None:
            setattr(current, side, Node(key))
            return root
        current = child

def build(keys):
    root = None
    for key in keys:
        root = insert(root, key)
    return root

def inorder(root):
    result, stack, current = [], [], root
    while current is not None or stack:
        while current is not None:
            stack.append(current)
            current = current.left
        current = stack.pop()
        result.append(current.key)
        current = current.right
    return result

def delete(root, key):
    if root is None:
        return None
    if key < root.key:
        root.left = delete(root.left, key)
    elif key > root.key:
        root.right = delete(root.right, key)
    else:
        if root.left is None:
            return root.right
        if root.right is None:
            return root.left
        successor = root.right
        while successor.left is not None:
            successor = successor.left
        root.key = successor.key
        root.right = delete(root.right, successor.key)
    return root

def floor_key(root, target):
    candidate = None
    while root is not None:
        if root.key == target:
            return root.key
        if root.key < target:
            candidate = root.key
            root = root.right
        else:
            root = root.left
    return candidate

def range_keys(root, low, high):
    if low > high:
        raise ValueError("low must not exceed high")
    result = []
    def visit(node):
        if node is None: return
        if low < node.key: visit(node.left)
        if low <= node.key <= high: result.append(node.key)
        if node.key < high: visit(node.right)
    visit(root)
    return result

def ceiling_key(root, target):
    candidate = None
    while root is not None:
        if root.key == target: return root.key
        if root.key > target:
            candidate = root.key
            root = root.left
        else:
            root = root.right
    return candidate
