# Generated by scripts/build-dsa-library-bridges.mjs
# Owner: src/learn/data/range-query-examples.js; examples: segment, fenwick, lazy
# Rebuild; do not maintain a second hand-edited implementation here.

from math import inf

class SegmentTree:
    def __init__(self, values, combine, identity):
        self.n = len(values)
        self.combine, self.identity = combine, identity
        self.size = 1
        while self.size < self.n:
            self.size *= 2
        self.tree = [identity] * (2 * self.size)
        self.tree[self.size:self.size + self.n] = values
        for node in range(self.size - 1, 0, -1):
            self.tree[node] = combine(self.tree[2 * node], self.tree[2 * node + 1])

    def set(self, index, value):
        if not 0 <= index < self.n:
            raise IndexError("Array index out of range")
        node = self.size + index
        self.tree[node] = value
        while node > 1:
            node //= 2
            self.tree[node] = self.combine(self.tree[2 * node], self.tree[2 * node + 1])

    def query(self, left, right):
        if not 0 <= left <= right <= self.n:
            raise IndexError("Use a half-open range within the array")
        left += self.size
        right += self.size
        before = after = self.identity
        while left < right:
            if left % 2:
                before = self.combine(before, self.tree[left])
                left += 1
            if right % 2:
                right -= 1
                after = self.combine(self.tree[right], after)
            left //= 2
            right //= 2
        return self.combine(before, after)

class Fenwick:
    def __init__(self, values):
        self.values = list(values)
        self.n = len(values)
        self.tree = [0] + list(values)
        for index in range(1, self.n + 1):
            parent = index + (index & -index)
            if parent <= self.n:
                self.tree[parent] += self.tree[index]

    def add(self, index, delta):
        if not 0 <= index < self.n:
            raise IndexError("Array index out of range")
        self.values[index] += delta
        internal = index + 1
        while internal <= self.n:
            self.tree[internal] += delta
            internal += internal & -internal

    def set(self, index, value):
        if not 0 <= index < self.n:
            raise IndexError("Array index out of range")
        self.add(index, value - self.values[index])

    def prefix(self, end):
        if not 0 <= end <= self.n:
            raise IndexError("Prefix boundary out of range")
        result = 0
        while end > 0:
            result += self.tree[end]
            end -= end & -end
        return result

    def range_sum(self, left, right):
        if not 0 <= left <= right <= self.n:
            raise IndexError("Use a half-open range within the array")
        return self.prefix(right) - self.prefix(left)

class LazySum:
    def __init__(self, values):
        self.n = len(values)
        self.size = 1
        while self.size < self.n:
            self.size *= 2
        self.total = [0] * (2 * self.size)
        self.multiplier = [1] * (2 * self.size)
        self.addition = [0] * (2 * self.size)
        self.total[self.size:self.size + self.n] = values
        for node in range(self.size - 1, 0, -1):
            self.total[node] = self.total[2 * node] + self.total[2 * node + 1]

    def _apply(self, node, length, multiplier, addition):
        self.total[node] = multiplier * self.total[node] + addition * length
        if length > 1:
            # New map AFTER old map: m*(old_m*x + old_b) + b.
            self.multiplier[node] = multiplier * self.multiplier[node]
            self.addition[node] = multiplier * self.addition[node] + addition

    def _push(self, node, length):
        multiplier, addition = self.multiplier[node], self.addition[node]
        if length > 1 and (multiplier != 1 or addition != 0):
            self._apply(2 * node, length // 2, multiplier, addition)
            self._apply(2 * node + 1, length // 2, multiplier, addition)
            self.multiplier[node], self.addition[node] = 1, 0

    def _check(self, left, right):
        if not 0 <= left <= right <= self.n:
            raise IndexError("Invalid half-open range")

    def _change(self, left, right, multiplier, addition):
        self._check(left, right)
        def visit(node, low, high):
            if right <= low or high <= left or left == right:
                return
            if left <= low and high <= right:
                self._apply(node, high - low, multiplier, addition)
                return
            self._push(node, high - low)
            middle = (low + high) // 2
            visit(2 * node, low, middle)
            visit(2 * node + 1, middle, high)
            self.total[node] = self.total[2 * node] + self.total[2 * node + 1]
        visit(1, 0, self.size)

    def add(self, left, right, delta):
        self._change(left, right, 1, delta)

    def set(self, left, right, value):
        self._change(left, right, 0, value)

    def query(self, left, right):
        self._check(left, right)
        def visit(node, low, high):
            if right <= low or high <= left or left == right:
                return 0
            if left <= low and high <= right:
                return self.total[node]
            self._push(node, high - low)
            middle = (low + high) // 2
            return visit(2 * node, low, middle) + visit(2 * node + 1, middle, high)
        return visit(1, 0, self.size)
