// Full current manuscript generated by scripts/render-geometric-graph-lesson.mjs.
import {Prose,H2,H3,CodeBlock} from '../../components/content';
import {Math as InlineMath,MathBlock} from '../../components/content/Math.jsx';
import {LessonIntro} from '../../components/lesson-labs/LessonElements.jsx';
import {NeuralTable} from '../../components/lesson-labs/NeuralLessonElements.jsx';
import {GeometricFigure} from '../../components/lesson-labs/GeometricGraphFigures.jsx';
import {GeoIdentityLab,GeoReadLab,GeoWalkLab,GeoBasisLab,GeoSquareLab,GeoActionLab,GeoUpdateLab,GeoGpsLab,GeoForceLab,GeoChiralityLab,GeoBudgetLab} from '../../components/lesson-labs/GeometricGraphLabs.jsx';
import {GeoProgram,GeoObservedFigure,GeoStudyLab} from '../../components/lesson-labs/GeometricGraphStudy.jsx';
import '../../components/lesson-labs/neural-lesson-neutral.css';
export default {title:'Graph Transformers & Geometric Deep Learning',readTime:'~110 min read + experiments and practice',hasIntegratedGuide:true,content:()=> <div className="neural-lesson neural-lesson-neutral geometric-graph-lesson"><LessonIntro prerequisites="Weighted sums, neural layers and graph message passing; each physical transformation is defined locally." sections={[["1-three-things-a-graph-drawing-can-conceal","1. Three things a graph drawing can conceal"],["2-give-an-attention-read-structural-information","2. Give an attention read structural information"],["3-structural-encodings-are-measurements-of-a-graph","3. Structural encodings are measurements of a graph"],["4-more-global-access-has-limits","4. More global access has limits"],["5-state-the-symmetry-contract-before-choosing-a-network","5. State the symmetry contract before choosing a network"],["6-move-from-node-permutations-to-physical-rotations","6. Move from node permutations to physical rotations"],["7-build-an-equivariant-coordinate-update","7. Build an equivariant coordinate update"],["8-run-a-complete-experiment-with-real-graph-data","8. Run a complete experiment with real graph data"],["9-deeper-choose-outputs-that-match-geometry-and-physics","9. Deeper: choose outputs that match geometry and physics"],["10-applications-and-engineering-decisions","10. Applications and engineering decisions"],["11-practice-with-new-inputs","11. Practice with new inputs"],["references-and-another-way-to-learn","References and another way to learn"]]}>Give a node access to distant information while keeping track of what the graph means. Then decide how an output should follow a relabeling, rotation or reflection.</LessonIntro>
<Prose opening="exploration">{""}<strong>{"Explore as you read."}</strong>{" Change a graph connection and follow its effect on a global read. Then rotate a sensor array or a set of points and compare the two routes through the same rule. Edit the inputs to find what changes, what stays fixed, and which transformation belongs to the output."}</Prose>

<Prose>{"A molecular diagram tells you which atoms are bonded. A set of three-dimensional coordinates tells you where the atoms are. These are different kinds of information. Two conformations can have the same bonds and different shapes; rotating the entire molecule changes its coordinates without changing those internal distances."}</Prose>

<Prose>{"This lesson asks two connected questions: "}<strong>{"How can a node consult distant parts of a graph while retaining information about its structure? How should predictions change when we relabel nodes or transform physical coordinates?"}</strong>{" Graph transformers address the first. Geometric deep learning provides a framework for the second, including architectures that satisfy the required transformation rule by construction."}</Prose>

<Prose>{"In the previous "}<a href={"/learn/path/full-curriculum/message-passing-graph-convolutions-gcn-gat-graphsage?module=deep-learning-fundamentals"}>{"message-passing lesson"}</a>{", information traveled along local edges. Keep that mechanism: global attention is another information route, and geometric constraints can apply to either route. Neither attention nor symmetry alone guarantees that a model makes accurate predictions."}</Prose>

<Prose opening="route">{""}<strong>{"First pass:"}</strong>{" §§1–4 explain graph structure and global reads; §§5–7 build the symmetry contract from a square to a point cloud; §8 gives a complete real-data experiment. Attempt practice 1–5. Sections 9–10 and practice 6–8 extend the lesson into tensor features, physical outputs, applications and resource decisions. Allow separate reading and experiment sessions. You need weighted sums, graph adjacency and a learned neural layer. The earlier "}<a href={"/learn/path/full-curriculum/abstract-algebra-groups-symmetry-actions?module=math-foundations"}>{"groups and symmetry actions lesson"}</a>{" supplies additional algebra, but each transformation used below is defined locally."}</Prose>

<H2>{"1. Three things a graph drawing can conceal"}</H2>

<Prose>{"Separate "}<strong>{"node identity"}</strong>{", "}<strong>{"connectivity"}</strong>{" and "}<strong>{"physical position"}</strong>{". A graph-layout program might move nodes apart to make edges readable. That motion does not change the graph. An atom-coordinate measurement has a different meaning: moving one atom while holding the others fixed changes distances and potentially the predicted property."}</Prose>

<Prose>{"For N nodes, write H as an N×d table of node features and A as an N×N adjacency matrix. We use receiver rows: Aᵢⱼ indicates that i receives from j. A geometric graph additionally has X, an N×3 coordinate table. Features such as atom type can be scalars under spatial rotations even when their numerical encoding is a vector of several channels. “Vector of features” does not automatically mean “physical vector.”"}</Prose>

<GeoIdentityLab />

<Prose>{"Let P be a permutation matrix: multiplying PH reorders node rows. For node outputs, the desired contract is"}</Prose>

<div className="neural-equation"><MathBlock>{"F(PH,PAP^T)=P F(H,A)."}</MathBlock></div>

<Prose>{"The output follows the node it describes. For a graph-level scalar, the output should instead be unchanged. A sum or mean of scalar node outputs can provide that invariance, although those choices preserve different information about graph size."}</Prose>

<p>The topology/layout and physical-position panels above use distinct inputs; their identical IDs do not make layout coordinates a measured geometric feature.</p>

<H3>{"A transformer cannot use information it never receives"}</H3>

<Prose>{"Self-attention on H alone compares every node with every other node. If A is never used in features, masks, biases or another branch, changing only A cannot change the result. Such a model processes a set of node features. It can be useful, but it does not become aware of bonds or citations merely because its inputs are called nodes."}</Prose>

<Prose>{"If the features already contain degree, triangle counts or message-passing states, some graph structure is present even without an explicit attention bias. An ablation called “no graph information” must remove those paths too. In our real experiment, every model retains degree and clustering features; the comparison isolates additional routes into graph structure."}</Prose>

<H2>{"2. Give an attention read structural information"}</H2>

<Prose>{"For receiver i and sender j, begin with a usual attention score, then add a structural bias:"}</Prose>

<div className="neural-equation"><MathBlock>{"s_{ij}=q_i^Tk_j/\\sqrt{d_k}+b_{ij},\\qquad\n\\alpha_{ij}=\\frac{e^{s_{ij}}}{\\sum_{u\\in\\mathcal A(i)}e^{s_{iu}}},\\qquad\ny_i=\\sum_{j\\in\\mathcal A(i)}\\alpha_{ij}v_j."}</MathBlock></div>

<Prose>{"Here q asks for relevant information, k determines a match, v supplies content and the allowed set A(i) determines which senders can participate. A "}<strong>{"bias"}</strong>{" changes relative preference; a "}<strong>{"mask"}</strong>{" removes access. A finite negative bias is not the same as forbidding a message."}</Prose>

<Prose>{"Use the path 0—1—2 with values (1,2,4). Give receiver 0 zero content scores and a bias of −distance×ln2. Its three exponentiated scores are (1,1/2,1/4). Dividing by their sum gives weights (4/7,2/7,1/7), and the output is"}</Prose>

<div className="neural-equation"><MathBlock>{"\\frac47\\cdot1+\\frac27\\cdot2+\\frac17\\cdot4=\\frac{12}{7}."}</MathBlock></div>

<Prose>{"Node 2 contributes immediately through global attention even though it is two graph hops away. If we mask attention to the closed one-hop neighborhood, the weights become (2/3,1/3,0) and the output becomes 4/3. If instead we retain global attention and change node 2's value from 4 to 11, the output rises by exactly 1. The mask would make this edit have no effect at receiver 0 in this layer."}</Prose>

<GeoReadLab />

<H3>{"Graphormer and GPS make different design choices"}</H3>

<Prose>{""}<a href={"https://arxiv.org/pdf/2106.05234"}>{"Graphormer"}</a>{" uses degree embeddings on nodes, shortest-path-dependent attention bias and an edge-feature bias along a selected shortest path. A learnable distance table can favor or discourage particular distances; it need not decrease monotonically. Disconnected pairs need a separate category, rather than being confused with a long finite path. Its special graph-summary node also has a distinct role from physical edges."}</Prose>

<Prose>{"Shortest-path length is invariant to node names. Selecting one of several equally short paths can be more delicate: if their edge features differ, a tie-break based on node index can affect the resulting bias. A claim of exact relabeling consistency must include this preprocessing, not only the attention formula. Our teaching model uses distances and no path-edge aggregation."}</Prose>

<Prose>{""}<a href={"https://arxiv.org/pdf/2205.12454"}>{"GPS"}</a>{" combines structural or positional inputs, a local message-passing branch and a global attention branch. Its layer combines those routes with residual/normalization operations and an MLP. This is useful when local edges supply meaningful inductive structure and distant interactions also matter. The global branch can use different attention operators; their mathematical and computational tradeoffs remain relevant."}</Prose>

<GeometricFigure kind="routes" /><GeometricFigure kind="gps" />

<H2>{"3. Structural encodings are measurements of a graph"}</H2>

<H3>{"Random-walk return probabilities"}</H3>

<Prose>{"On an unweighted undirected graph with positive degrees, define T=D⁻¹A. Row i is a probability distribution for one step from i to a uniformly selected neighbor. The entry (Tᵏ)ᵢᵢ is the probability of returning to i after k steps. A node can receive several such probabilities as additional features."}</Prose>

<Prose>{"The diagonal of Aᵏ instead counts walks on an unweighted graph. Counts and probabilities are different: each step of a random walk includes a degree-dependent denominator. For an isolated node, choose and document a policy. Our code uses a zero transition row, yielding zero positive-step return values; an absorbing self-loop would define a different walk."}</Prose>

<Prose>{"Consider a six-cycle and two disjoint triangles. Both have six nodes, all degree two. With identical initial features, plain local message passing cannot distinguish their nodes by repeated neighbor multisets. But a three-step return probability is zero on the six-cycle and 1/4 on a triangle. In a triangle there are two returning three-step routes, each with probability (1/2)³. This feature distinguishes the examples immediately."}</Prose>

<Prose>{"It does not follow that a trained model must use the feature successfully. Nor does it follow that a transformer is necessary: a small model reading that return probability can already separate this pair. A random output difference on two graphs is evidence of different representations at those weights, not an accuracy benchmark."}</Prose>

<GeometricFigure kind="walks" /><GeoWalkLab />

<H3>{"Laplacian modes"}</H3>

<Prose>{"The combinatorial Laplacian L=D−A is a symmetric matrix for an undirected graph. Its eigenvectors are patterns on nodes: Lu=λu means the operator scales that pattern by λ. Low eigenvalues correspond to patterns that vary relatively little across edges under the associated quadratic form. The number of zero eigenvalues equals the number of connected components."}</Prose>

<Prose>{"For a connected graph, the zero mode is constant. For a disconnected graph there is an entire space of componentwise constant patterns. The symmetric normalized Laplacian uses degree-scaled coordinates instead; do not silently transfer the constant-vector convention. Isolated-node definitions require additional care. These distinctions were developed in "}<a href={"/learn/path/full-curriculum/spectral-graph-theory?module=math-foundations"}>{"Spectral Graph Theory"}</a>{"."}</Prose>

<Prose>{"Rows of selected eigenvectors can become positional features. Yet the numerical eigenvectors are not unique. A unit eigenvector and its negative represent the same mode. If an eigenvalue repeats, any orthonormal basis of its eigenspace is valid. This happens in connected graphs too: a four-cycle has eigenvalues (0,2,2,4), so its eigenvalue-2 space has a freely rotatable two-vector basis."}</Prose>

<Prose>{"Making the first nonzero entry positive does not solve the full problem. “First” depends on node order, and sign choices do not remove rotations inside a repeated eigenspace. Selecting only part of a repeated eigenspace creates another ambiguity. Sorting connected components by arbitrary IDs is not a general relabeling-safe repair."}</Prose>

<Prose>{"An instructive invariant is the "}<strong>{"projector"}</strong>{" UUᵀ for a complete orthonormal eigenspace basis U. Replacing U by UQ for an orthogonal Q gives UQQᵀUᵀ=UUᵀ. Relabeling nodes still permutes its two node axes. "}<a href={"https://arxiv.org/html/2202.13013v4"}>{"SignNet and BasisNet"}</a>{" explicitly address sign and basis symmetries; the projector calculation shows why the distinction matters. It is a conceptual route, not a claim that dense projectors are the cheapest encoding for every graph."}</Prose>

<GeoBasisLab />

<H2>{"4. More global access has limits"}</H2>

<Prose>{"Full attention reduces the number of layers needed for a distant node to be reachable. It does not guarantee that its information survives the weighted sum, that all structures become distinguishable, or that the model can be trained effectively with the available labels."}</Prose>

<Prose>{"For example, if every value vector equals v, then every normalized attention row returns v, regardless of its distance biases. Different weight matrices alone do not create distinct outputs in this case. A downstream bias or nonlinear layer receiving identical node states preserves that equality when its rule is shared. Node features, degree information, edge values or other routes may remove the collision."}</Prose>

<GeometricFigure kind="access" />

<Prose>{"Graph spectra are also not complete graph fingerprints: different graphs can be cospectral. An encoding's conditions determine its expressiveness; the label “graph transformer” does not settle them. Separately measure access, distinguishability, fitting and held-out prediction."}</Prose>

<Prose>{""}<strong>{"Practice pause."}</strong>{" For the three-node path, replace all three values by 7. Calculate the global and locally masked outputs, despite their different weights."}</Prose>

<details><summary>Hint</summary>

<Prose>{"A weighted average of equal values has a simple result."}</Prose>

</details>

<details><summary>Solution</summary>

<Prose>{"Both outputs equal 7 because each allowed row is normalized. The attention distributions differ; the supplied messages do not expose that difference. This is a useful null case for an implementation and an interpretation warning."}</Prose>

</details>

<H2>{"5. State the symmetry contract before choosing a network"}</H2>

<Prose>{"A transformation g can act differently on inputs and outputs. Write those actions as P_g and Q_g. The architectural requirement is"}</Prose>

<div className="neural-equation"><MathBlock>{"F(P_g x)=Q_g F(x)."}</MathBlock></div>

<Prose>{"Invariance is the special case where Q_g leaves the output unchanged. It is not a universal ranking in which one kind of prediction is “weaker” than another: a scalar energy and a vector force require different output actions. The "}<a href={"https://geometricdeeplearning.com/book/algebraicpriors.html"}>{"geometric deep learning text"}</a>{" develops this representation-based view."}</Prose>

<H3>{"Start with four sensors on a square"}</H3>

<Prose>{"Number four sensors around a square. A quarter-turn moves their scalar readings cyclically: R(a,b,c,d)=(d,a,b,c). A reflection fixes positions 0 and 2 and swaps 1 and 3: S(a,b,c,d)=(a,d,c,b). A filter W=R copies the preceding sensor into each output."}</Prose>

<Prose>{"This filter commutes with quarter-turns because powers of R commute. It does not commute with reflection. On readings (1,2,4,8), reflecting after filtering gives (8,4,2,1), while filtering after reflecting gives (2,1,8,4). A constant input such as (1,1,1,1) hides the failure: both routes agree. One successful input test cannot prove a whole-map property."}</Prose>

<Prose>{"For a linear layer, WP_g=Q_gW proves the contract for every input. Averaging the eight square-symmetry conjugates of W produces a map commuting with the entire finite square group. Here it becomes (R+R⁻¹)/2, averaging the two adjacent readings. Its output on our example is (5,2.5,5,2.5). Eight discrete square symmetries do not cover all continuous planar rotations."}</Prose>

<GeoSquareLab />

<H2>{"6. Move from node permutations to physical rotations"}</H2>

<Prose>{"A spatial rotation is an orthogonal matrix R with determinant +1. It preserves lengths and angles. Adding a translation t changes a point x to Rx+t. SE(3) includes these proper rotations and translations in three dimensions. E(3) also allows reflections, whose orthogonal matrices have determinant −1."}</Prose>

<NeuralTable caption={"6. Move from node permutations to physical rotations"} headers={[<>{"Quantity"}</>,<>{"Under a common rotation/reflection Q and translation t"}</>]} rows={[[<>{"Position"}</>,<>{"Qx+t"}</>],[<>{"Displacement, velocity or ordinary force"}</>,<>{"Qv; translation adds nothing"}</>],[<>{"Scalar energy of an isolated system with the assumed symmetries"}</>,<>{"Same scalar"}</>],[<>{"Axial vector such as a cross product of two polar vectors"}</>,<>{"det(Q)Qv"}</>],[<>{"Node label/order"}</>,<>{"Follows the corresponding node permutation"}</>]]} />

<Prose>{"Forces and electric dipole vectors are ordinary polar vectors, not generally pseudovectors. Angular momentum is an axial vector. They transform the same way under proper rotations but differently under reflections. A charged system's dipole also depends on origin: translating all charges adds total-charge×translation. Specify the physical setting rather than treating the table as permission to ignore external fields or boundaries."}</Prose>

<H3>{"Scalar channels and vector channels need different nonlinearities"}</H3>

<Prose>{"Applying the same scalar ReLU to each channel commutes with a permutation of scalar channels. It generally fails for the Cartesian components of a rotating vector. With v=(1,−2) and a 90° rotation, ReLU(Rv)=(2,1), while R ReLU(v)=(0,1). The discrepancy is 2 in the first component."}</Prose>

<Prose>{"Multiplying a vector by a scalar function of its norm is rotation-equivariant: the norm is unchanged, so the same multiplier accompanies the rotated vector. Summing or averaging vectors that share the same rotation action is also equivariant. Averaging force vectors does not magically turn them into a rotation-invariant scalar; it yields another rotating vector."}</Prose>

<GeoActionLab />

<Prose>{"A finite image grid adds another distinction. A 90° rotation of a square array can permute pixels exactly; a 17° rotation usually needs interpolation and boundary handling. Repeated interpolation need not equal one resampling by the composed angle. A proof about continuous functions or exact point coordinates does not automatically prove exact equivariance for that raster pipeline. State the sampled domain, action, padding/cropping and error tolerance when applying the idea to images."}</Prose>

<H2>{"7. Build an equivariant coordinate update"}</H2>

<Prose>{"Start with scalar node states hᵢ, positions xᵢ and invariant edge attributes aᵢⱼ. Construct messages from quantities that do not change under the intended rigid transformation:"}</Prose>

<div className="neural-equation"><MathBlock>{"m_{ij}=\\phi_e(h_i,h_j,\\|x_i-x_j\\|^2,a_{ij}),\\qquad\ns_{ij}=\\phi_x(m_{ij})."}</MathBlock></div>

<Prose>{"Each sᵢⱼ is a scalar. An EGNN-style coordinate update has the form"}</Prose>

<div className="neural-equation"><MathBlock>{"x'_i=x_i+c\\sum_{j\\in\\mathcal N(i)}(x_i-x_j)s_{ij},\\qquad\nh'_i=\\phi_h\\left(h_i,\\sum_jm_{ij}\\right)."}</MathBlock></div>

<Prose>{"The "}<a href={"https://proceedings.mlr.press/v139/satorras21a/satorras21a.pdf"}>{"EGNN paper"}</a>{" develops this construction and related velocity/edge variants. State the normalization c and neighbor rule for an actual implementation; the paper's all-pairs coordinate update uses c=1/(N−1). Our next hand calculation uses a separately declared step coefficient and a fixed scalar function so we can inspect every contribution."}</Prose>

<H3>{"The proof is a sequence of simple checks"}</H3>

<Prose>{"Under xᵢ→Qxᵢ+t, relative positions become Q(xᵢ−xⱼ): translation cancels. Their squared lengths stay unchanged because QᵀQ=I. Consequently messages and scalar multipliers stay unchanged. Each directional contribution rotates or reflects by Q, and their sum does too. Adding the transformed starting point gives Qx′ᵢ+t. Scalar hidden-state updates remain unchanged. Relabeling nodes simply relabels the same sums."}</Prose>

<Prose>{"This proof requires invariant initial scalar features, compatible edges and correctly transforming attributes. Building neighbors with an axis-specific rule such as “larger x-coordinate” can violate it. Radius neighbors are compatible in exact arithmetic, but cutoffs, ties and floating-point tolerances still need a defined implementation policy."}</Prose>

<GeometricFigure kind="proof" />

<H3>{"Calculate the arrows"}</H3>

<Prose>{"Use three constructed points (0,0,0), (1,0,0), (0,2,0). Connect every pair and set"}</Prose>

<div className="neural-equation"><MathBlock>{"x'_i=x_i+0.1\\sum_{j\\ne i}\\frac{x_i-x_j}{1+\\|x_i-x_j\\|^2}."}</MathBlock></div>

<Prose>{"For point 0, the two relative vectors are (−1,0,0) and (0,−2,0), with multipliers 1/2 and 1/5. The displacement is (−.05,−.04,0). The three updated points are"}</Prose>

<div className="neural-equation"><MathBlock>{"(-.05,-.04,0),\\quad(1.066667,-.033333,0),\\quad(-.016667,2.073333,0)."}</MathBlock></div>

<Prose>{"Now rotate 90° around z and translate by (3,−2,1). Updating after the transform gives (3.04,−2.05,1), (3.033333,−.933333,1) and (.926667,−2.016667,1). These are the transformed original outputs. The retained double-precision calculation agrees to about 10⁻¹⁶ for this case."}</Prose>

<GeoUpdateLab />

<Prose>{"This coordinate update is not automatically a stable physical simulator. Equivariance permits large coefficients, explosive repeated updates and inaccurate predictions. Replacing a relative vector by a norm-normalized direction preserves rigid-motion equivariance if done consistently, but does not bound unbounded learned scalars or guarantee stability. A degree normalization, residual scale or bounded gate changes numerical behavior and must be evaluated as part of the model. Applying arbitrary coordinatewise normalization can destroy the geometric contract."}</Prose>

<Prose>{"The complete "}<a href={"/learn-code/graph-transformers-geometric-deep-learning/geometry-calculations.py"}>{"geometry-calculations.py"}</a>{" reproduces the attention arithmetic, return walks, eigenspace projector, square action, coordinate update and changed-output checks. These are constructed mathematical examples. They are separate from the observed graph experiment below."}</Prose>

<GeoProgram file="geometry-calculations.py" title="Complete executed geometry, walks, eigenbasis and finite-action calculations" />

<H2>{"8. Run a complete experiment with real graph data"}</H2>

<Prose>{"We reuse the observed 34-node, 78-edge karate-club graph from the preceding lesson. This creates a useful controlled continuation: same source IDs, binary edges, affiliation labels and supervision split. The small offline "}<a href={"/learn-code/graph-transformers-geometric-deep-learning/karate-club.json"}>{"graph data"}</a>{" and "}<a href={"/learn-code/graph-transformers-geometric-deep-learning/data-provenance.md"}>{"provenance"}</a>{" retain the licensed NetworkX representation and explain the original interaction weights, which this experiment does not use."}</Prose>

<Prose>{"Each node receives three structural features: constant 1, degree/33 and clustering coefficient. A full known-graph transductive task permits those features and edges at all nodes. Only ten affiliation labels enter the fitting loss; six development and eighteen assessment labels are separate. The split is fixed before fitting. This is one historically observed dependent network, not a population study or a test on unseen graphs."}</Prose>

<GeoObservedFigure />

<Prose>{"Compare four deliberately small models:"}</Prose>

<ol start={1}><li>{"A two-layer GCN with 16 hidden units."}</li><li>{"A two-block set-attention model on the same structural features, with two heads of width 8."}</li><li>{"The same attention model with learned shortest-path-distance biases."}</li><li>{"Attention receiving four random-walk return features in addition to the original three."}</li></ol>

<Prose>{"The GCN has far fewer parameters. The comparison is a small learning investigation, not a parameter-matched benchmark or a reproduction of Graphormer/GPS. All fits use 300 epochs, AdamW learning rate .003, weight decay .01 and seeds 11,29,47. We keep every run, without choosing an epoch or tuning parameters from the assessment scores. This GCN's learning rate differs from the preceding lesson's .02; compare the variants within this table, not two lessons as if they were one matched experiment."}</Prose>

<Prose>{""}<strong>{"Compare the actual structural variants:"}</strong>{" inspect whether extra structural information improves the assessment score in this experiment. Follow one node from input features to q/k/v, two residual blocks, logits, supervised loss and a parameter update."}</Prose>

<GeometricFigure kind="pipeline" />

<H3>{"Complete offline program"}</H3>

<Prose>{"Save this program beside karate-club.json. It requires NumPy and CPU PyTorch; it downloads nothing and does not need a graph library. It computes shortest paths with an explicit unreachable category, return probabilities, normalized GCN propagation, attention blocks, fitting, assessment and node-relabeling checks."}</Prose>

<GeoProgram file="graph-transformer-study.py" title="Complete executed offline graph transformer and GCN study" />

<H3>{"Read the actual result"}</H3>

<NeuralTable caption={"Read the actual result"} headers={[<>{"Model"}</>,<>{"Seed"}</>,<>{"Parameters"}</>,<>{"Fit /10"}</>,<>{"Development /6"}</>,<>{"Assessment /18"}</>]} rows={[[<>{"gcn"}</>,<>{"11"}</>,<>{"98"}</>,<>{"9"}</>,<>{"2"}</>,<>{"9"}</>],[<>{"gcn"}</>,<>{"29"}</>,<>{"98"}</>,<>{"9"}</>,<>{"2"}</>,<>{"9"}</>],[<>{"gcn"}</>,<>{"47"}</>,<>{"98"}</>,<>{"8"}</>,<>{"2"}</>,<>{"10"}</>],[<>{"set"}</>,<>{"11"}</>,<>{"4546"}</>,<>{"10"}</>,<>{"1"}</>,<>{"10"}</>],[<>{"set"}</>,<>{"29"}</>,<>{"4546"}</>,<>{"10"}</>,<>{"1"}</>,<>{"10"}</>],[<>{"set"}</>,<>{"47"}</>,<>{"4546"}</>,<>{"10"}</>,<>{"1"}</>,<>{"10"}</>],[<>{"distance"}</>,<>{"11"}</>,<>{"4616"}</>,<>{"10"}</>,<>{"1"}</>,<>{"9"}</>],[<>{"distance"}</>,<>{"29"}</>,<>{"4616"}</>,<>{"10"}</>,<>{"1"}</>,<>{"9"}</>],[<>{"distance"}</>,<>{"47"}</>,<>{"4616"}</>,<>{"10"}</>,<>{"1"}</>,<>{"9"}</>],[<>{"walk"}</>,<>{"11"}</>,<>{"4610"}</>,<>{"10"}</>,<>{"2"}</>,<>{"10"}</>],[<>{"walk"}</>,<>{"29"}</>,<>{"4610"}</>,<>{"10"}</>,<>{"2"}</>,<>{"9"}</>],[<>{"walk"}</>,<>{"47"}</>,<>{"4610"}</>,<>{"10"}</>,<>{"2"}</>,<>{"10"}</>]]} />

<Prose>{"Always predicting one affiliation scores 9/18 on this balanced assessment. Most models fit their ten supervised labels perfectly yet score only 9 or 10 on assessment. More parameters, global access and extra structural features do not establish improved generalization here. The preceding lesson's fixed label-propagation baseline scored 16/18 under the same graph/label split; it remains a useful practical comparison, not a reason to tune these networks against exposed assessment answers."}</Prose>

<GeometricFigure kind="results" />

<Prose>{"The code also removes edge (0,1) after fitting, holds the original degree/clustering inputs fixed and recomputes each model's explicit graph operators. This isolates propagation, distances or return-feature paths without claiming to erase every trace of topology. The set-attention model is exactly unchanged because it receives the same feature table and no other graph input. The other changes can be small: for the seed-11 distance model, the largest assessment probability change is about .0001265. Sensitivity is not guaranteed to be large merely because a pathway exists."}</Prose>

<GeoStudyLab />

<H3>{"Build the local/global composition, then use GPSConv"}</H3>

<Prose>{"The earlier real-data study deliberately isolates distance bias and random-walk features; it is not GPS. Now compose the two routes GPS makes explicit: one local graph update and one graph-wide attention read. Reuse "}<a href={"/learn/path/full-curriculum/message-passing-graph-convolutions-gcn-gat-graphsage?module=deep-learning-fundamentals#move-the-same-layer-from-a-matrix-to-an-edge-list"}>{"Message Passing's sparse GCN and edge convention"}</a>{". The preceding lesson develops and executes that sparse layer. Its "}<a href={"/learn-code/graph-transformers-geometric-deep-learning/graph_library_bridge.py"}>{"complete helper"}</a>{" is supplied with the "}<a href={"/learn-code/graph-transformers-geometric-deep-learning/gps_library_bridge.py"}>{"GPS composition program"}</a>{"; place both files in the same directory when running them."}</Prose>

<Prose>{"Our comparison holds normalization and dropout off to expose composition. The two branches each carry their own residual:"}</Prose>

<div className="neural-equation"><MathBlock>{"h=(x+\\operatorname{GCN}(x))+(x+\\operatorname{Attention}_{graph}(x)),\\qquad y=h+\\operatorname{MLP}(h)."}</MathBlock></div>

<Prose>{"There are "}<strong>{"two copies of x in the sum"}</strong>{", not one. Replacing this with "}<code>{"x + local + global"}</code>{" is a different function. "}<code>{"LocalGlobalBlock"}</code>{" writes these operations directly. Its global attention reuses the projections/mixing taught in "}<a href={"/learn/path/full-curriculum/self-attention-multi-head-attention?module=deep-learning-fundamentals#5-implement-the-operation-you-just-traced"}>{"Self-Attention §5"}</a>{"; rebuilding that primitive here would obscure the new graph-level boundary. The complete paired program copies every local, attention and MLP parameter into "}<code>{"GPSConv(norm=None, dropout=0, heads=2, attn_type=\"multihead\")"}</code>{". "}<a href={"https://pytorch-geometric.readthedocs.io/en/2.8.0/_modules/torch_geometric/nn/conv/gps_conv.html"}>{"The PyG source"}</a>{" is the contract for this concrete composition."}</Prose>

<Prose>{"Each node receives three declared scalar features plus its two-step return probability. These structural scalars move with a node under relabeling. They are "}<strong>{"not spatial vector coordinates"}</strong>{" and need no rotation matrix. "}<code>{"Batch.from_data_list"}</code>{" offsets each graph's edge indices and supplies its node-to-graph vector. The manual block reads one graph at a time; PyG pads graphs for its global attention and masks padding. A missing batch vector would let all five nodes communicate as one graph, even though local edge indices still contain no cross-graph edge."}</Prose>

<GeoGpsLab />

<Prose>{"Run "}<code>{"python gps_library_bridge.py"}</code>{" with PyTorch and "}<code>{"torch-geometric==2.8.0.post1"}</code>{". This route was executed on 27 September 2026 with PyTorch 2.14.0 CPU and PyG 2.8.0.post1. The checks establish: manual and package outputs/gradients/one SGD update agree within the supplied tolerances; the three-node and two-node graph outputs agree whether evaluated separately or together; editing graph B cannot change graph A; consistently relabeling nodes, structural features and edges relabels outputs. An additional executed case adds a third, isolated graph: its output stays fixed when graph B changes with the proper batch vector, and changes when that vector is omitted. These are value, derivative and communication checks; no training-quality or runtime measurement is inferred."}</Prose>

<GeoProgram file="gps_library_bridge.py" title="Complete executed manual/PyG GPS composition, gradients and batching" /><GeoProgram file="graph_library_bridge.py" title="Required sparse GCN/SAGE/GAT helper from the preceding lesson" />

<Prose>{"Why disable normalization here? The package's default batch normalization shares batch statistics during training, so independently evaluating a graph and evaluating it in a batch need not produce the same answer. "}<code>{"norm=None"}</code>{" isolates the intended communication relation. Later choose per-node LayerNorm, per-graph normalization or BatchNorm deliberately and revise the corresponding invariance test. Dropout also changes the comparison unless modes and random masks match."}</Prose>

<Prose>{"The local route stores edges, while dense global attention still incurs pairwise work inside each graph. The manual per-graph loop avoids cross-graph N_total² storage; PyG's padded route can pay for the largest graph in a batch. Batch similarly sized graphs or choose a justified alternative attention backend when padding dominates. The small loop is a correctness composition, not an accelerator benchmark."}</Prose>

<Prose>{""}<strong>{"Take control."}</strong>{" Add a third graph containing one isolated node. Then intentionally omit the batch vector in the package call and compare that node's output after editing a feature in another graph."}</Prose>

<details><summary>Hint</summary>The self-looped local update works for an isolate. Global attention needs a graph boundary independently of edge boundaries.</details>

<details><summary>Solution and success criteria</summary>With the correct batch vector, all three separate outputs concatenate to the batched result. Without it, the global branch can read every node and the isolated graph's output can change. Restore the vector; then relabel nodes within each graph and verify output equivariance. Arbitrarily interleaving graph IDs may violate a dense-batching utility's sorted-ID contract, so group nodes by graph and keep the inverse permutation for restoring the application order.</details>

<H2>{"9. Deeper: choose outputs that match geometry and physics"}</H2>

<H3>{"Chirality and reflection"}</H3>

<Prose>{"Distances alone cannot distinguish a configuration from its mirror image. For four ordered, distinguishable points define"}</Prose>

<div className="neural-equation"><MathBlock>{"\\chi=\\det[x_1-x_0,\\;x_2-x_0,\\;x_3-x_0]."}</MathBlock></div>

<Prose>{"Translation cancels; a proper rotation preserves χ; a reflection reverses its sign. The unit-axis tetrahedron gives +1 and its x-reflection gives −1. This is six times oriented volume, with cubed-length units. Swapping two of the ordered points also reverses the sign. A chirality feature therefore needs chemically meaningful roles or a suitable permutation-consistent construction, not arbitrary index ordering."}</Prose>

<Prose>{"A reflection-sensitive target may need information that an E(3)-invariant scalar model discards. But not every molecular property should distinguish enantiomers in every environment. A chiral environment must be represented when its interaction matters. Requiring a physically incorrect symmetry can make the target impossible to learn; omitting a useful symmetry can increase the burden on data. Evaluate the specific target and inputs."}</Prose>

<GeoChiralityLab />

<H3>{"An energy-derived force adds another contract"}</H3>

<Prose>{"If a differentiable scalar energy E(X) is invariant under rigid motions, forces defined by Fᵢ=−∇ₓᵢE transform as polar vectors. The chain rule establishes their rotational behavior. Translation invariance additionally gives zero total internal force when all relevant positions are included. Rotational invariance similarly constrains total torque under the smooth isolated-system assumptions."}</Prose>

<Prose>{"Use a constructed spring-like energy E=½Σᵢ<ⱼ‖xᵢ−xⱼ‖², in declared arbitrary units. For our triangle E=5, and the forces are (1,2,0), (−2,2,0), (1,−4,0). They sum to zero. The program checks them against central finite differences, with maximum error about 3.8×10⁻¹¹ at its stated step. This is a mathematical force example, not a fitted molecular potential."}</Prose>

<GeoForceLab />

<Prose>{"A directly predicted equivariant vector field need not be the gradient of a scalar energy and need not conserve energy during simulation. Even exact energy gradients require an appropriate numerical integrator; equivariance is not a substitute for conservation, stability or empirical validation."}</Prose>

<H3>{"Beyond scalar and vector states"}</H3>

<Prose>{"A three-component vector rotates through a 3×3 representation matrix. More general features can transform in irreducible blocks: for SO(3), a degree-ℓ block has 2ℓ+1 components. ℓ=0 is a scalar, ℓ=1 is vector-like and ℓ=2 can encode a symmetric traceless rank-two tensor with five independent components. A general 3×3 matrix has nine components and is not just one ℓ=2 block."}</Prose>

<GeometricFigure kind="types" />

<Prose>{""}<a href={"https://arxiv.org/abs/2006.10503"}>{"SE(3)-Transformers"}</a>{" combine invariant attention weights with appropriately transforming features. Spherical harmonics encode directions; tensor-product rules combine representation types without treating arbitrary Cartesian components as unrelated scalars. "}<a href={"https://docs.e3nn.org/en/stable/api/o3/o3_irreps.html"}>{"e3nn's representation documentation"}</a>{" makes rotation degree and reflection parity explicit. These are additional representational tools, not a universal speed or accuracy ranking over EGNN."}</Prose>

<H2>{"10. Applications and engineering decisions"}</H2>

<Prose>{""}<strong>{"Molecular property prediction:"}</strong>{" graph connectivity describes bonds; geometric inputs describe conformations. Hold out appropriate molecules or chemical families when the intended claim concerns new chemistry. Near-duplicate conformers across splits can exaggerate generalization. Record target units, whether coordinates are available at prediction time and whether the property is extensive or intensive. A model requiring optimized coordinates cannot silently be compared with one receiving only a bond graph."}</Prose>

<Prose>{""}<strong>{"Protein frames:"}</strong>{" a residue can carry a local coordinate frame. Invariant point attention compares points after placing them in a common global frame; applying one common rigid motion preserves their pairwise distances. Pulling a global weighted point back into a residue's local frame supplies a frame-consistent local quantity. This helps explain the structure module discussed in the "}<a href={"https://geometricdeeplearning.com/book/geometricgraphs.html"}>{"geometric-graphs chapter's AlphaFold 2 case study"}</a>{". It is a design principle, not a claim that this small lesson implements protein folding or that all folding architectures are interchangeable."}</Prose>

<GeometricFigure kind="frames" />

<Prose>{""}<strong>{"Sensor and robotic geometry:"}</strong>{" an output displacement should rotate when the entire sensor frame rotates. Yet gravity, walls, camera calibration and fixed world directions can be meaningful inputs. If those are held fixed while the scene rotates, the task may no longer have the same symmetry. Transform the whole relevant input representation or state exactly what remains anchored."}</Prose>

<H3>{"Count the resource, not a universal node cutoff"}</H3>

<Prose>{"Materializing H attention heads for one N-node graph in b-byte precision requires HN²b bytes for that tensor. With eight heads and float32, N=1,000 gives 32,000,000 bytes; N=10,000 gives 3,200,000,000 bytes, before other activations or gradients. These are decimal MB/GB, not MiB/GiB. Multiple layers and a batch add more tensors, but exact peak memory depends on saved intermediates and execution strategy."}</Prose>

<GeoBudgetLab />

<Prose>{"Exact tiled attention can avoid retaining the entire score matrix while still performing dense pair interactions. Structural bias tensors and shortest-path preprocessing can remain quadratic even when the attention kernel is memory-efficient. Sparse masks change the allowed computation; kernel-feature methods change or approximate the attention operator; pooling changes the representations. Attention on a coarsened graph is not generally identical to attention on the original graph."}</Prose>

<Prose>{"For local geometric layers, costs depend on edge count, MLP widths, radial features and representation channels. An edge MLP can cost O(d²), so “O(E·d)” is not a complete universal layer estimate. There is no fixed node threshold or fixed EGNN-to-tensor-network speed ratio that settles all choices."}</Prose>

<Prose>{"The current "}<a href={"https://pytorch-geometric.readthedocs.io/en/latest/generated/torch_geometric.nn.conv.GPSConv.html"}>{"PyG GPSConv documentation"}</a>{" places positional/structural encodings in preprocessing and exposes local/global components. An API does not infer the intended encodings or certify the whole action contract for you. Check mask, graph batching, normalization, edge feature and representation conventions with small known examples before scaling."}</Prose>

<section className="lesson-ending lesson-ending--practice" data-lesson-ending="practice"><H2>{"11. Practice with new inputs"}</H2>

<div className="lesson-exercise" data-lesson-exercise=""><H3>{"1. A changed remote message — core"}</H3>

<Prose>{"Use the path attention weights (4/7,2/7,1/7), but values (2,0,7). Compute the global output and the one-hop masked output for receiver 0. Explain the difference."}</Prose>

<details><summary>Hint</summary>

<Prose>{"The local read renormalizes the first two weights; it does not simply discard a contribution without renormalizing."}</Prose>

</details>

<details><summary>Solution</summary>

<Prose>{"Global output is 15/7. The local weights are (2/3,1/3,0), giving 4/3. The remote value enters globally in one layer; local access forbids that route."}</Prose>

</details></div>

<div className="lesson-exercise" data-lesson-exercise=""><H3>{"2. Count walks and probabilities — core"}</H3>

<Prose>{"At the center of a three-node path, what are (A²)₁₁ and (T²)₁₁ without self-loops? Explain why they differ."}</Prose>

<details><summary>Hint</summary>

<Prose>{"There are two choices on the first step, but each endpoint has only one return neighbor."}</Prose>

</details>

<details><summary>Solution</summary>

<Prose>{"There are two length-two returning walks, so the count is 2. Each has probability 1/2×1, so total return probability is 1. A probability feature requires degree normalization."}</Prose>

</details></div>

<div className="lesson-exercise" data-lesson-exercise=""><H3>{"3. Find a concealed symmetry failure — core"}</H3>

<Prose>{"Use square readings (1,0,0,0) and W=R from §5. Compare SRx and RSx. Why would the all-ones input have missed the bug?"}</Prose>

<details><summary>Hint</summary>

<Prose>{"Track the single nonzero reading through the two operations."}</Prose>

</details>

<details><summary>Solution</summary>

<Prose>{"SRx=(0,0,0,1), while RSx=(0,1,0,0). A constant reading vector is fixed by both permutations, so it supplies no distinguishing input. A matrix commutation identity, rather than that one passing input, establishes an all-input linear contract."}</Prose>

</details></div>

<div className="lesson-exercise" data-lesson-exercise=""><H3>{"4. Choose the output action — core"}</H3>

<Prose>{"Rotate a point cloud by 90° around z and translate it by (3,4,0). How should a predicted point (1,0,0), a displacement (1,0,0) and an invariant scalar 5 transform?"}</Prose>

<details><summary>Hint</summary>

<Prose>{"Translations act on positions, not on free displacement vectors."}</Prose>

</details>

<details><summary>Solution</summary>

<Prose>{"The point becomes (3,5,0), the displacement becomes (0,1,0), and the scalar stays 5. Applying the same numerical transformation to every output type would be wrong."}</Prose>

</details></div>

<div className="lesson-exercise" data-lesson-exercise=""><H3>{"5. Interpret the real comparison — core"}</H3>

<Prose>{"A distance-biased model fits 10/10 labels and scores 9/18 on assessment. The set model scores 10/18. Does this establish that graph distances hurt learning? Propose one useful follow-up without tuning repeatedly on those assessment answers."}</Prose>

<details><summary>Hint</summary>

<Prose>{"Separate this small fixed protocol from a general architectural claim."}</Prose>

</details>

<details><summary>Solution</summary>

<Prose>{"It establishes the displayed outcomes for these models, features, labels and training budget. Investigate fitting/development behavior, input features and errors, then evaluate a justified new comparison on fresh appropriate held-out data. Preserve a strong simple baseline. Neither one-point difference nor perfect fitting supports a universal ranking."}</Prose>

</details></div>

<div className="lesson-exercise" data-lesson-exercise=""><H3>{"6. Repair an eigenspace claim — deeper"}</H3>

<Prose>{"A connected graph has a repeated nonzero Laplacian eigenvalue. A colleague flips each eigenvector so its first nonzero entry is positive and declares all ambiguity removed. Give the missing transformation and a basis-invariant representation of the entire eigenspace."}</Prose>

<details><summary>Hint</summary>

<Prose>{"An orthogonal rotation can mix the columns while preserving the same subspace."}</Prose>

</details>

<details><summary>Solution</summary>

<Prose>{"U and UQ are both valid orthonormal bases for any orthogonal Q within the repeated eigenspace. Sign fixing does not remove that freedom and an index-based sign rule can itself conflict with relabeling. UUᵀ is unchanged by U→UQ; under node permutation it becomes PUUᵀPᵀ. A truncated portion of a repeated eigenspace is not the same complete object."}</Prose>

</details></div>

<div className="lesson-exercise" data-lesson-exercise=""><H3>{"7. Verify a force and its units — deeper"}</H3>

<Prose>{"For two points (0,0,0) and (2,0,0), use E=½‖x₀−x₁‖² with unit spring coefficient. Compute E and both forces. What happens under a common translation? What extra claim does a conservative energy-derived force make beyond equivariance?"}</Prose>

<details><summary>Hint</summary>

<Prose>{"Differentiate with respect to each point, with the force defined as the negative gradient."}</Prose>

</details>

<details><summary>Solution</summary>

<Prose>{"E=2; forces are (2,0,0) and (−2,0,0). Common translation changes neither differences, energy nor forces. A force derived from a smooth scalar potential has the corresponding conservative structure; a general equivariant vector predictor need not. For physical units, the spring coefficient carries energy/length² and force has energy/length units. Numerical time stepping still needs its own accuracy/stability analysis."}</Prose>

</details></div>

<div className="lesson-exercise" data-lesson-exercise=""><H3>{"8. Build a complete action test — deeper"}</H3>

<Prose>{"Design a test for a geometric graph model with scalar node states, coordinates and vector outputs. Include a genuine null, a failing control and one independent prediction-quality test."}</Prose>

<details><summary>Hint</summary>

<Prose>{"Transform input and output representations correctly, and do not confuse algebraic agreement with a useful prediction."}</Prose>

</details>

<details><summary>Solution</summary>

<Prose>{"Permute nodes and both adjacency axes, and apply a valid orthogonal transformation plus translation to coordinates. Scalars follow nodes; vector outputs rotate without translation. Compare both routes with a scale-aware tolerance and check the transformation matrix itself. Identity is a null; a coordinatewise ReLU or axis-dependent edge rule supplies a controlled failing case on a non-symmetric input. Separately score appropriate held-out targets with declared units and split boundaries. A zero or constant predictor can pass a symmetry check while predicting poorly."}</Prose>

</details></div></section>

<section className="lesson-ending lesson-ending--resources" data-lesson-ending="resources"><H2>{"References and another way to learn"}</H2>

<ul><li>{""}<a href={"https://geometricdeeplearning.com/book/"}>{"Geometric Deep Learning book and free draft chapters"}</a>{": Chapters 3,5 and 8 connect actions, graphs and geometric graphs. Use the chapter route matching your current hurdle; the whole book is not a prerequisite for this lesson."}</li><li>{""}<a href={"https://arxiv.org/pdf/2106.05234"}>{"Graphormer"}</a>{", §3: compare the three structural inputs with our deliberately smaller distance-bias model. "}<a href={"https://arxiv.org/pdf/2205.12454"}>{"GPS"}</a>{", §3/Figure 1: trace local and global branches and note how its encoding choices also help message passing."}</li><li>{""}<a href={"https://arxiv.org/html/2202.13013v4"}>{"SignNet and BasisNet"}</a>{", §2: follow the sign-versus-basis distinction after reproducing the four-cycle projector."}</li><li>{""}<a href={"https://proceedings.mlr.press/v139/satorras21a/satorras21a.pdf"}>{"EGNN"}</a>{", §3 and Appendix A: read the invariant messages and coordinate proof together, then identify the assumptions in your own code."}</li><li>{""}<a href={"https://arxiv.org/abs/2006.10503"}>{"SE(3)-Transformers"}</a>{" and "}<a href={"https://docs.e3nn.org/en/stable/api/o3/o3_irreps.html"}>{"e3nn representations"}</a>{": a deeper route into feature types and reflection parity."}</li><li>{""}<a href={"https://geometricdeeplearning.com/lectures/"}>{"The authors' GDL lecture recordings and exercises"}</a>{": Geometric Priors I/II and Graphs & Sets I/II offer a spoken/visual alternative; the site links each YouTube recording and accompanying material. The author course page and lesson associations were inspected; the full recordings were not watched for this packet."}</li></ul>

<Prose>{"Next in this module is "}<a href={"/learn/path/full-curriculum/boltzmann-machines-restricted-boltzmann-machines-rbm?module=deep-learning-fundamentals"}>{"Boltzmann Machines & Restricted Boltzmann Machines"}</a>{". That changes the modeling question: instead of arranging information routes to predict a target, we assign probabilities to configurations through an energy function. Keep the distinction between an architectural property, an optimization procedure and empirical evidence—it will matter there too."}</Prose></section>
</div>};
