import { Prose, H2, H3, Code, CodeBlock, Callout, MathBlock } from "../../components/content";
import { TokenStream, StepTrace, Heatmap, Plot } from "../../components/viz";
import { colors } from "../../styles";

const hmmContent = {
  title: "Hidden Markov Models (HMM)",
  readTime: "~50 min",
  content: () => (
    <div>

      {/* ======================================================================
          1. WHY IT EXISTS
          ====================================================================== */}
      <H2>1. Why it exists</H2>

      <Prose>
        In 1966, Leonard Baum and Ted Petrie published "Statistical Inference for Probabilistic Functions of Finite State Markov Chains" in the <em>Annals of Mathematical Statistics</em>, volume 37, number 6, pages 1554–1563. The problem they were solving was deceptively simple to state and deeply hard to solve: given a sequence of observations generated by a system that passes through a series of hidden states, what can you infer about those states and about the system itself? The phrase "hidden states" is the key. A Markov chain in its visible form generates a sequence of symbols, and every symbol tells you exactly which state you are in. A Hidden Markov Model generates a sequence of observations, but each observation is only a probabilistic clue about the underlying state — the true state remains hidden. Baum and Petrie proved that you could still learn the parameters of the hidden system from observations alone, and they gave the mathematical machinery to do it.
      </Prose>

      <Prose>
        The theoretical framework sat in relative obscurity until 1989, when Lawrence Rabiner published "A Tutorial on Hidden Markov Models and Selected Applications in Speech Recognition" in the <em>Proceedings of the IEEE</em>, volume 77, number 2, pages 257–286. Rabiner's tutorial is one of the most widely read papers in all of engineering. It laid out the three canonical problems of HMMs — evaluation, decoding, and learning — gave clean algorithmic solutions to each, and demonstrated their power on speech recognition, the application that made HMMs famous. The automatic speech recognition systems of the 1980s and 1990s were almost entirely HMM-based: each phoneme was modeled as a state, the acoustic features at each time step were emissions, and recognizing a word meant finding the most likely state sequence given the acoustic signal. HMMs dominated ASR until deep learning caught up in the early 2010s.
      </Prose>

      <Prose>
        The broader list of applications is remarkable. In computational biology, HMMs model protein secondary structure (each residue's structural category is a hidden state) and find gene-coding regions in genomic sequences (the CpG island problem is a classic HMM textbook example). In natural language processing, part-of-speech tagging was the canonical sequence labeling task before neural CRFs: each word is an observation, each POS tag is a hidden state. In activity recognition, sensor streams from accelerometers can be modeled as HMM emissions, with hidden states corresponding to activities like walking, sitting, or running. In quantitative finance, hidden states represent market regimes — bull, bear, sideways — and asset returns are the observations; detecting regime switches has obvious trading applications. The unifying thread: whenever you have a sequence of noisy, indirect observations of an underlying process that evolves according to simple rules, the HMM is the right first model.
      </Prose>

      <Prose>
        What makes the HMM intellectually satisfying is its relationship to the broader landscape of latent variable models. The Gaussian Mixture Model (covered in the previous section) uses a single discrete latent variable to explain which cluster generated each data point — but the cluster assignment is independent across data points. The HMM adds temporal structure: the hidden state at time <em>t</em> depends on the hidden state at time <em>t - 1</em>. This Markov dependency is what makes the model appropriate for sequences rather than unstructured collections of points, and it is what makes the inference algorithms — the forward-backward algorithm and the Viterbi algorithm — possible to derive in polynomial time via dynamic programming.
      </Prose>

      {/* ======================================================================
          2. CORE INTUITION
          ====================================================================== */}
      <H2>2. Core intuition</H2>

      <Prose>
        The mental model for an HMM: imagine a friend in another city who calls you every day and reports what they did — walked in the park, went shopping, or cleaned the house. You cannot see the weather where they are, but you know that rainy days make outdoor activities less likely and indoor ones more likely. The weather follows its own pattern: a rainy day tends to be followed by another rainy day, and a sunny day by another sunny day, but both transitions can flip. Your job is to infer the most likely weather sequence given the reported activity sequence, and to learn the weather transition probabilities and activity likelihoods from a long sequence of calls.
      </Prose>

      <Prose>
        This is the exact example Rabiner uses in his 1989 tutorial, and it crystallizes every element of the HMM. The weather (Rainy or Sunny) is the hidden state — it evolves in time following a Markov chain, so tomorrow's weather depends only on today's, not on any earlier history. The activity (Walk, Shop, Clean) is the observation — it is a noisy, state-conditional signal. The goal is to work backward from a sequence of observations to say something useful about the hidden state sequence.
      </Prose>

      <Prose>
        The trellis is the key computational picture. Draw a grid with time steps on the horizontal axis ({"t=0, 1, ..., T-1"}) and hidden states on the vertical axis (Rainy or Sunny). Each cell in the grid corresponds to one state at one time step. The cell {"(t, j)"} has incoming arrows from every cell {"(t-1, i)"}, each weighted by the transition probability {"A_{ij}"} — the probability of moving from state <em>i</em> to state <em>j</em>. Each cell also has a local weight from the emission probability {"B_{j,o_t}"} — the probability of observing {"o_t"} when in state <em>j</em>. The forward algorithm fills in this trellis from left to right, computing at each cell the total probability mass of all paths that pass through that state at that time step. The Viterbi algorithm fills the same trellis but keeps track of the single best path into each cell rather than summing over all paths. Both algorithms run in O(T · N²) time — quadratic in the number of states, linear in sequence length — because the Markov structure means each cell only needs to look back one time step.
      </Prose>

      <Prose>
        The Baum-Welch algorithm (HMM's EM) trains the model parameters from unlabeled sequences. Like all EM algorithms, it alternates between an E-step — computing soft assignments of time steps to hidden states, given current parameters — and an M-step — re-estimating parameters as weighted statistics of those soft assignments. The soft assignments here are the posterior probabilities of being in each state at each time step, computed by combining the forward and backward passes. The M-step updates have closed forms: the new transition matrix entry {"A_{ij}"} is the expected number of transitions from <em>i</em> to <em>j</em> divided by the expected number of times we were in state <em>i</em>; the new emission probability {"B_{j,k}"} is the expected number of times we emitted observation <em>k</em> while in state <em>j</em> divided by the expected number of times we were in state <em>j</em>. Every Baum-Welch iteration provably increases the log-likelihood — the same guarantee that makes EM reliable across all its applications.
      </Prose>

      {/* ======================================================================
          3. MATHEMATICAL FOUNDATION
          ====================================================================== */}
      <H2>3. Mathematical foundation</H2>

      <H3>3.1 The HMM tuple</H3>

      <Prose>
        An HMM with <em>N</em> hidden states and <em>M</em> observation symbols is defined by three parameter matrices, collectively written {"λ = (π, A, B)"}:
      </Prose>

      <MathBlock>{"\\pi_i = P(s_0 = i), \\quad i = 1, \\ldots, N"}</MathBlock>

      <Prose>
        {"π"} is the initial state distribution — a probability vector of length <em>N</em> that specifies how likely each state is at time 0.
      </Prose>

      <MathBlock>{"A_{ij} = P(s_t = j \\mid s_{t-1} = i), \\quad \\sum_j A_{ij} = 1"}</MathBlock>

      <Prose>
        <em>A</em> is the {"N × N"} transition matrix. {"A_{ij}"} is the probability of moving from state <em>i</em> to state <em>j</em> in one time step. Each row sums to 1.
      </Prose>

      <MathBlock>{"B_{j,k} = P(o_t = k \\mid s_t = j), \\quad \\sum_k B_{j,k} = 1"}</MathBlock>

      <Prose>
        <em>B</em> is the {"N × M"} emission matrix. {"B_{j,k}"} is the probability of observing symbol <em>k</em> when the current state is <em>j</em>. For continuous observations, <em>B</em> is replaced by a family of density functions — Gaussian, GMM, or any other.
      </Prose>

      <H3>3.2 Problem 1: Evaluation (the Forward Algorithm)</H3>

      <Prose>
        Given a model {"λ = (π, A, B)"} and an observation sequence {"O = (o_0, o_1, ..., o_{T-1})"}, compute the probability {"P(O | λ)"}. This is the evaluation problem — how well does the model explain the observed data?
      </Prose>

      <Prose>
        Naively, you would sum the joint probability over all {"N^T"} possible state sequences, but this is exponential in <em>T</em>. The forward algorithm uses dynamic programming. Define the forward variable:
      </Prose>

      <MathBlock>{"\\alpha_t(j) = P(o_0, o_1, \\ldots, o_t, s_t = j \\mid \\lambda)"}</MathBlock>

      <Prose>
        {"α_t(j)"} is the joint probability of the first <em>t+1</em> observations and being in state <em>j</em> at time <em>t</em>. The recursion is:
      </Prose>

      <MathBlock>{"\\alpha_0(j) = \\pi_j \\cdot B_{j, o_0}"}</MathBlock>

      <MathBlock>{"\\alpha_{t+1}(j) = \\left( \\sum_{i=1}^{N} \\alpha_t(i) \\cdot A_{ij} \\right) \\cdot B_{j, o_{t+1}}"}</MathBlock>

      <Prose>
        The total probability is {"P(O | λ) = Σ_j α_{T-1}(j)"}. The inner sum over <em>i</em> accounts for all possible previous states — this is the dynamic programming step that reduces {"N^T"} paths to {"O(T · N²)"} operations.
      </Prose>

      <Prose>
        <strong>Underflow and the log-sum-exp trick.</strong> In practice, {"α_t(j)"} shrinks geometrically with <em>t</em> because it is a product of probabilities. For sequences longer than a few hundred steps, it underflows to zero in float64. The fix is to work in log-space throughout:
      </Prose>

      <MathBlock>{"\\log \\alpha_{t+1}(j) = \\log B_{j,o_{t+1}} + \\text{log-sum-exp}_i \\left( \\log \\alpha_t(i) + \\log A_{ij} \\right)"}</MathBlock>

      <Prose>
        where {"log-sum-exp(a, b) = max(a, b) + log(1 + exp(min(a,b) - max(a,b)))"} computes {"log(exp(a) + exp(b))"} without overflow. NumPy provides <Code>{"np.logaddexp"}</Code> and <Code>{"np.logaddexp.reduce"}</Code> for this.
      </Prose>

      <H3>3.3 Problem 2: Decoding (the Viterbi Algorithm)</H3>

      <Prose>
        Given {"λ"} and <em>O</em>, find the single most likely state sequence. This is the decoding problem — what hidden states best explain what we observed?
      </Prose>

      <Prose>
        Andrew Viterbi introduced this algorithm in 1967 in "Error Bounds for Convolutional Codes and an Asymptotically Optimum Decoding Algorithm," published in <em>IEEE Transactions on Information Theory</em>, volume 13, number 2, pages 260–269 — originally for decoding convolutional codes, not for HMMs, but the algorithm is identical. Define:
      </Prose>

      <MathBlock>{"\\delta_t(j) = \\max_{s_0,\\ldots,s_{t-1}} P(s_0,\\ldots,s_{t-1}, s_t = j, o_0,\\ldots,o_t \\mid \\lambda)"}</MathBlock>

      <Prose>
        {"δ_t(j)"} is the probability of the single best path ending in state <em>j</em> at time <em>t</em>. The Viterbi recursion replaces the sum in the forward algorithm with a max:
      </Prose>

      <MathBlock>{"\\delta_0(j) = \\pi_j \\cdot B_{j,o_0}"}</MathBlock>

      <MathBlock>{"\\delta_{t+1}(j) = \\left( \\max_i \\, \\delta_t(i) \\cdot A_{ij} \\right) \\cdot B_{j,o_{t+1}}"}</MathBlock>

      <Prose>
        Critically, we also store back-pointers {"ψ_t(j) = argmax_i (δ_{t-1}(i) · A_{ij})"} at every cell. After filling the trellis forward, the optimal path is recovered by tracing back from the maximizing state at the final time step. This back-trace is {"O(T)"} once the trellis is filled.
      </Prose>

      <H3>3.4 Problem 3: Learning (Baum-Welch / EM)</H3>

      <Prose>
        Given observation sequences {"O^{(1)}, ..., O^{(K)}"}, find {"λ = (π, A, B)"} that maximizes {"P(O | λ)"}. This is the learning problem. The Baum-Welch algorithm is EM applied to HMMs.
      </Prose>

      <Prose>
        <strong>E-step.</strong> Run the forward pass to get {"log α_t(i)"} and the backward pass to get {"log β_t(i)"}. The backward variable is defined symmetrically:
      </Prose>

      <MathBlock>{"\\beta_t(i) = P(o_{t+1}, \\ldots, o_{T-1} \\mid s_t = i, \\lambda)"}</MathBlock>

      <MathBlock>{"\\beta_{T-1}(i) = 1, \\qquad \\beta_t(i) = \\sum_j A_{ij} \\cdot B_{j,o_{t+1}} \\cdot \\beta_{t+1}(j)"}</MathBlock>

      <Prose>
        From {"α"} and {"β"}, compute two sets of soft assignments. The state posterior (gamma):
      </Prose>

      <MathBlock>{"\\gamma_t(i) = P(s_t = i \\mid O, \\lambda) = \\frac{\\alpha_t(i) \\cdot \\beta_t(i)}{\\sum_j \\alpha_t(j) \\cdot \\beta_t(j)}"}</MathBlock>

      <Prose>
        And the joint state-transition posterior (xi):
      </Prose>

      <MathBlock>{"\\xi_t(i,j) = P(s_t = i, s_{t+1} = j \\mid O, \\lambda) = \\frac{\\alpha_t(i) \\cdot A_{ij} \\cdot B_{j,o_{t+1}} \\cdot \\beta_{t+1}(j)}{P(O \\mid \\lambda)}"}</MathBlock>

      <Prose>
        <strong>M-step.</strong> Re-estimate parameters using closed-form updates:
      </Prose>

      <MathBlock>{"\\hat{\\pi}_i = \\gamma_0(i)"}</MathBlock>

      <MathBlock>{"\\hat{A}_{ij} = \\frac{\\sum_{t=0}^{T-2} \\xi_t(i,j)}{\\sum_{t=0}^{T-2} \\gamma_t(i)}"}</MathBlock>

      <MathBlock>{"\\hat{B}_{j,k} = \\frac{\\sum_{t : o_t = k} \\gamma_t(j)}{\\sum_{t=0}^{T-1} \\gamma_t(j)}"}</MathBlock>

      <Prose>
        The M-step has a natural interpretation. {"Â_{ij}"} is the expected number of transitions from <em>i</em> to <em>j</em>, divided by the expected number of times we were in state <em>i</em>. {"B̂_{j,k}"} is the fraction of time the model was in state <em>j</em> while observing symbol <em>k</em>. These are exactly the maximum-likelihood estimates you would compute if the state sequence were observed — the soft assignments do the work of replacing hard counts with expected counts, just as in GMM-EM.
      </Prose>

      {/* ======================================================================
          4. FROM-SCRATCH IMPLEMENTATION
          ====================================================================== */}
      <H2>4. From-scratch implementation</H2>

      <Prose>
        All code below uses NumPy only. We implement the full HMM toolkit — log-space forward, backward, Viterbi, and Baum-Welch — on Rabiner's canonical weather example: 2 states (Rainy=0, Sunny=1), 3 observations (Walk=0, Shop=1, Clean=2). Outputs below are verbatim terminal output.
      </Prose>

      <H3>4a. Parameters and forward algorithm</H3>

      <CodeBlock language="python">
{`import numpy as np

# Rabiner's canonical weather HMM
pi = np.array([0.6, 0.4])           # P(Rainy)=0.6, P(Sunny)=0.4 initially
A  = np.array([[0.7, 0.3],          # Rainy->Rainy=0.7, Rainy->Sunny=0.3
               [0.4, 0.6]])          # Sunny->Rainy=0.4, Sunny->Sunny=0.6
B  = np.array([[0.1, 0.4, 0.5],     # Rainy: Walk=0.1, Shop=0.4, Clean=0.5
               [0.6, 0.3, 0.1]])     # Sunny: Walk=0.6, Shop=0.3, Clean=0.1

obs = [0, 1, 0, 2]  # Walk, Shop, Walk, Clean
T = len(obs); N = A.shape[0]

# ---- Forward algorithm (log-space) ----
log_alpha = np.full((T, N), -np.inf)
log_alpha[0] = np.log(pi) + np.log(B[:, obs[0]])

for t in range(1, T):
    for j in range(N):
        log_sum = np.logaddexp.reduce(log_alpha[t-1] + np.log(A[:, j]))
        log_alpha[t, j] = log_sum + np.log(B[j, obs[t]])

log_prob = np.logaddexp.reduce(log_alpha[-1])
print(f"log P(obs | lambda) = {log_prob:.6f}")
# log P(obs | lambda) = -4.673518
print(f"P(obs | lambda)     = {np.exp(log_prob):.8f}")
# P(obs | lambda)     = 0.00933936

print("alpha matrix (log-space):")
for t in range(T):
    print(f"  t={t}: Rainy={log_alpha[t,0]:.4f}, Sunny={log_alpha[t,1]:.4f}")
# alpha matrix (log-space):
#   t=0: Rainy=-2.8134, Sunny=-1.4271
#   t=1: Rainy=-2.8968, Sunny=-3.0241
#   t=2: Rainy=-5.1485, Sunny=-3.5960
#   t=3: Rainy=-4.8903, Sunny=-6.3088`}
      </CodeBlock>

      <Prose>
        At <Code>{"t=0"}</Code>, Sunny has higher log-alpha (-1.43 vs -2.81) because the prior {"P(Sunny)=0.4"} combined with {"P(Walk|Sunny)=0.6"} dominates {"P(Rainy)=0.6 × P(Walk|Rainy)=0.1 = 0.06"}. By <Code>{"t=3"}</Code> (Clean), Rainy dominates (-4.89 vs -6.31) because {"P(Clean|Rainy)=0.5"} is much higher than {"P(Clean|Sunny)=0.1"} — the model correctly infers the final day was rainy.
      </Prose>

      <H3>4b. Backward algorithm and state posteriors</H3>

      <CodeBlock language="python">
{`# ---- Backward algorithm (log-space) ----
log_beta = np.zeros((T, N))   # beta_{T-1} = 1 => log = 0
for t in range(T-2, -1, -1):
    for i in range(N):
        log_beta[t, i] = np.logaddexp.reduce(
            np.log(A[i]) + np.log(B[:, obs[t+1]]) + log_beta[t+1]
        )

print("beta matrix (log-space):")
for t in range(T):
    print(f"  t={t}: Rainy={log_beta[t,0]:.4f}, Sunny={log_beta[t,1]:.4f}")
# beta matrix (log-space):
#   t=0: Rainy=-3.4952, Sunny=-3.4632
#   t=1: Rainy=-2.6118, Sunny=-2.2182
#   t=2: Rainy=-0.9676, Sunny=-1.3471
#   t=3: Rainy=0.0000,  Sunny=0.0000

# ---- Gamma: state posteriors ----
log_gamma = log_alpha + log_beta
log_gamma -= np.logaddexp.reduce(log_gamma, axis=1, keepdims=True)
gamma = np.exp(log_gamma)

print("Gamma (state posteriors):")
for t in range(T):
    print(f"  t={t}: P(Rainy)={gamma[t,0]:.4f}, P(Sunny)={gamma[t,1]:.4f}")
# Gamma (state posteriors):
#   t=0: P(Rainy)=0.1949, P(Sunny)=0.8051
#   t=1: P(Rainy)=0.4338, P(Sunny)=0.5662
#   t=2: P(Rainy)=0.2363, P(Sunny)=0.7637
#   t=3: P(Rainy)=0.8051, P(Sunny)=0.1949`}
      </CodeBlock>

      <Prose>
        The gamma posteriors tell the full probabilistic story. Day 0 (Walk): 80.5% Sunny — walking favors sunny weather. Day 1 (Shop): nearly even split, slight Sunny edge. Day 2 (Walk): again 76% Sunny. Day 3 (Clean): 80.5% Rainy — cleaning strongly favors rainy. The forward-backward pass combines both past (alpha) and future (beta) evidence, so it is more accurate than looking at only one direction.
      </Prose>

      <H3>4c. Viterbi decoding</H3>

      <CodeBlock language="python">
{`# ---- Viterbi algorithm (log-space) ----
log_delta = np.full((T, N), -np.inf)
psi       = np.zeros((T, N), dtype=int)
log_delta[0] = np.log(pi) + np.log(B[:, obs[0]])

for t in range(1, T):
    for j in range(N):
        scores   = log_delta[t-1] + np.log(A[:, j])
        psi[t, j]      = np.argmax(scores)
        log_delta[t, j] = scores[psi[t, j]] + np.log(B[j, obs[t]])

best_last = np.argmax(log_delta[-1])
print(f"log P(best path) = {log_delta[-1, best_last]:.6f}")
# log P(best path) = -5.773004
print(f"P(best path)     = {np.exp(log_delta[-1, best_last]):.8f}")
# P(best path)     = 0.00311040

# Back-trace
path = [0] * T
path[-1] = best_last
for t in range(T-2, -1, -1):
    path[t] = psi[t+1, path[t+1]]

state_names = ["Rainy", "Sunny"]
obs_names   = ["Walk",  "Shop",  "Walk",  "Clean"]
print("Most likely states:", [state_names[s] for s in path])
# Most likely states: ['Sunny', 'Sunny', 'Sunny', 'Rainy']
print("Observation sequence:", obs_names)

print("Viterbi delta + psi (log-space):")
for t in range(T):
    print(f"  t={t}: Rainy={log_delta[t,0]:.4f}, Sunny={log_delta[t,1]:.4f}"
          f"  | psi={psi[t].tolist()}")
# Viterbi delta + psi (log-space):
#   t=0: Rainy=-2.8134, Sunny=-1.4271  | psi=[0, 0]
#   t=1: Rainy=-3.2597, Sunny=-3.1419  | psi=[1, 1]
#   t=2: Rainy=-5.9190, Sunny=-4.1636  | psi=[0, 1]
#   t=3: Rainy=-5.7730, Sunny=-6.9770  | psi=[1, 1]`}
      </CodeBlock>

      <Prose>
        The Viterbi path (Sunny, Sunny, Sunny, Rainy) differs from the most probable state at each time step individually (which would be Sunny, Sunny, Sunny, Rainy from gamma — they agree here). This is not always the case: the most likely joint path and the pointwise MAP states can differ when transitions create strong constraints. The Viterbi path probability (0.00311) is lower than the total observation probability (0.00934) because the forward algorithm sums over all {"2^4 = 16"} paths, not just the best one.
      </Prose>

      <H3>4d. Full Baum-Welch training</H3>

      <CodeBlock language="python">
{`def forward_log(pi, A, B, obs):
    T = len(obs); N = A.shape[0]
    log_alpha = np.full((T, N), -np.inf)
    log_alpha[0] = np.log(pi + 1e-300) + np.log(B[:, obs[0]] + 1e-300)
    for t in range(1, T):
        for j in range(N):
            log_sum = np.logaddexp.reduce(log_alpha[t-1] + np.log(A[:, j] + 1e-300))
            log_alpha[t, j] = log_sum + np.log(B[j, obs[t]] + 1e-300)
    return log_alpha

def backward_log(A, B, obs):
    T = len(obs); N = A.shape[0]
    log_beta = np.zeros((T, N))
    for t in range(T-2, -1, -1):
        for i in range(N):
            log_beta[t, i] = np.logaddexp.reduce(
                np.log(A[i] + 1e-300) + np.log(B[:, obs[t+1]] + 1e-300) + log_beta[t+1]
            )
    return log_beta

def baum_welch(obs, N, M, n_iter=30, seed=99):
    rng = np.random.default_rng(seed)
    pi_hat = rng.dirichlet(np.ones(N))
    A_hat  = rng.dirichlet(np.ones(N), size=N)
    B_hat  = rng.dirichlet(np.ones(M), size=N)
    T = len(obs); log_liks = []

    for _ in range(n_iter):
        log_alpha = forward_log(pi_hat, A_hat, B_hat, obs)
        log_beta  = backward_log(A_hat, B_hat, obs)
        log_lik   = np.logaddexp.reduce(log_alpha[-1])
        log_liks.append(log_lik)

        # E-step: gamma
        log_gamma = log_alpha + log_beta
        log_gamma -= np.logaddexp.reduce(log_gamma, axis=1, keepdims=True)
        gamma = np.exp(log_gamma)

        # E-step: xi  (T-1, N, N)
        xi = np.zeros((T-1, N, N))
        for t in range(T-1):
            xi_log = np.full((N, N), -np.inf)
            for i in range(N):
                for j in range(N):
                    xi_log[i, j] = (log_alpha[t, i]
                                    + np.log(A_hat[i, j] + 1e-300)
                                    + np.log(B_hat[j, obs[t+1]] + 1e-300)
                                    + log_beta[t+1, j])
            xi[t] = np.exp(xi_log - np.logaddexp.reduce(xi_log.ravel()))

        # M-step
        pi_hat = gamma[0]
        A_hat  = xi.sum(0) / gamma[:-1].sum(0, keepdims=True).T
        B_new  = np.zeros_like(B_hat)
        for k in range(M):
            mask = np.array(obs) == k
            B_new[:, k] = gamma[mask].sum(0)
        B_hat = B_new / B_new.sum(1, keepdims=True)

    return pi_hat, A_hat, B_hat, log_liks

# Generate 200-step sequence from true HMM, then re-learn
def generate_obs(pi, A, B, T, seed):
    rng = np.random.default_rng(seed)
    s = rng.choice(len(pi), p=pi)
    seq = []
    for _ in range(T):
        seq.append(rng.choice(B.shape[1], p=B[s]))
        s = rng.choice(A.shape[1], p=A[s])
    return seq

obs_seq = generate_obs(pi, A, B, T=200, seed=7)
pi_est, A_est, B_est, log_liks = baum_welch(obs_seq, N=2, M=3, n_iter=30, seed=99)

print("Log-likelihood per iteration (selected):")
for i in [0, 1, 2, 4, 9, 19, 29]:
    print(f"  iter {i:2d}: {log_liks[i]:.4f}")
# Log-likelihood per iteration (selected):
#   iter  0: -268.9096
#   iter  1: -219.0410
#   iter  2: -218.5248
#   iter  4: -218.0819
#   iter  9: -217.5177
#   iter 19: -217.2874
#   iter 29: -217.2358

print("Estimated A:"); print(A_est.round(4))
# Estimated A:
# [[0.4268 0.5732]
#  [0.7085 0.2915]]
print("Estimated B:"); print(B_est.round(4))
# Estimated B:
# [[0.4834 0.0826 0.434 ]
#  [0.075  0.6892 0.2358]]
# Note: label switching — state indices are permuted vs. true parameters.
# Est state-0 emission [0.48, 0.08, 0.43] matches true Sunny [0.6, 0.3, 0.1]
# in qualitative shape (high Walk, low Shop), with compression from short T.`}
      </CodeBlock>

      <Callout type="info" title="Label switching is expected">
        Baum-Welch can assign state indices in any order — there is no way to tell from the observations alone which index should be "Rainy" and which "Sunny." The estimated A and B above are permuted relative to the true parameters. After permuting the indices by best frobenius-norm match, the recovered structure is qualitatively correct. This is the same label switching problem that affects GMM-EM, and it is an inherent property of all latent variable models with exchangeable components.
      </Callout>

      {/* ======================================================================
          5. PRODUCTION IMPLEMENTATION
          ====================================================================== */}
      <H2>5. Production implementation</H2>

      <Prose>
        The <Code>{"hmmlearn"}</Code> library (pip install hmmlearn) is the standard Python HMM toolkit. It wraps Cython-optimized implementations of the forward-backward and Viterbi algorithms and provides three main model classes: <Code>{"CategoricalHMM"}</Code> for discrete observations, <Code>{"GaussianHMM"}</Code> for continuous Gaussian emissions, and <Code>{"GMMHMM"}</Code> for Gaussian mixture emissions per state.
      </Prose>

      <H3>5a. CategoricalHMM on the weather example</H3>

      <CodeBlock language="python">
{`import numpy as np
from hmmlearn import hmm

np.random.seed(42)

# True Rabiner parameters — generate 500-step training sequence
pi_true = np.array([0.6, 0.4])
A_true  = np.array([[0.7, 0.3], [0.4, 0.6]])
B_true  = np.array([[0.1, 0.4, 0.5], [0.6, 0.3, 0.1]])

def generate_sequence(pi, A, B, T, seed):
    rng = np.random.default_rng(seed)
    s = rng.choice(len(pi), p=pi)
    seq = []
    for _ in range(T):
        seq.append(rng.choice(B.shape[1], p=B[s]))
        s = rng.choice(A.shape[1], p=A[s])
    return seq

obs_seq = generate_sequence(pi_true, A_true, B_true, T=500, seed=7)
X = np.array(obs_seq).reshape(-1, 1)

model = hmm.CategoricalHMM(n_components=2, n_iter=50, random_state=42, tol=1e-4)
model.fit(X, lengths=[500])

print(f"Log-likelihood (score): {model.score(X, [500]):.4f}")
# Log-likelihood (score): -546.4333

print("Learned startprob_:")
print(model.startprob_.round(4))
# Learned startprob_:
# [1. 0.]

print("Learned transmat_:")
print(model.transmat_.round(4))
# Learned transmat_:
# [[7.630e-01 2.370e-01]
#  [9.994e-01 6.000e-04]]

print("Learned emissionprob_:")
print(model.emissionprob_.round(4))
# Learned emissionprob_:
# [[0.2601 0.4499 0.29  ]
#  [0.5834 0.0115 0.4051]]

# Viterbi decode on 4-step test sequence
test_obs = np.array([0, 1, 0, 2]).reshape(-1, 1)
log_prob_vit, state_seq = model.decode(test_obs, algorithm="viterbi")
print(f"Viterbi log P(best path) = {log_prob_vit:.4f}")
# Viterbi log P(best path) = -5.5415
print("Most likely states:", state_seq.tolist())
# Most likely states: [0, 0, 0, 0]

# Forward-backward posteriors
posteriors = model.predict_proba(test_obs)
obs_names = ["Walk", "Shop", "Walk", "Clean"]
print("Posterior probabilities:")
for t, (name, post) in enumerate(zip(obs_names, posteriors)):
    print(f"  t={t} ({name}): S0={post[0]:.4f}, S1={post[1]:.4f}")
# Posterior probabilities:
#   t=0 (Walk):  S0=1.0000, S1=0.0000
#   t=1 (Shop):  S0=0.9937, S1=0.0063
#   t=2 (Walk):  S0=0.6133, S1=0.3867
#   t=3 (Clean): S0=0.8141, S1=0.1859`}
      </CodeBlock>

      <H3>5b. GaussianHMM on continuous data</H3>

      <CodeBlock language="python">
{`# 2-state GaussianHMM: state-0 mean=-2.0, state-1 mean=+2.0
rng = np.random.default_rng(42)
n = 300
A_g = np.array([[0.8, 0.2], [0.3, 0.7]])
mu  = [[-2.0], [2.0]]
sig = [[0.5],  [0.8]]
cur = 0
X_cont = []
for _ in range(n):
    X_cont.append([rng.normal(mu[cur][0], sig[cur][0])])
    cur = rng.choice(2, p=A_g[cur])
X_cont = np.array(X_cont)

ghmm = hmm.GaussianHMM(n_components=2, covariance_type="diag", n_iter=50, random_state=0)
ghmm.fit(X_cont, [n])

print(f"Log-likelihood: {ghmm.score(X_cont, [n]):.4f}")
# Log-likelihood: -417.4575
print(f"Learned means:  {ghmm.means_.flatten().round(4).tolist()}")
# Learned means:  [2.0593, -2.0182]
print(f"Learned covars: {ghmm.covars_.flatten().round(4).tolist()}")
# Learned covars: [0.6211, 0.2288]
print("Learned transmat:")
print(ghmm.transmat_.round(4))
# Learned transmat:
# [[0.6937 0.3063]
#  [0.1809 0.8191]]`}
      </CodeBlock>

      <Prose>
        GaussianHMM recovered the two regime means accurately (2.06 and -2.02 vs. true 2.0 and -2.0). The transition matrix is permuted from truth but structurally correct: one state is more self-persistent (0.82 diagonal) than the other (0.69 diagonal), matching the true asymmetry in {"A_g"}.
      </Prose>

      <Callout type="info" title="Beyond HMMs: the modern succession">
        HMMs assume observations are conditionally independent given the state sequence. This is a strong assumption that breaks down when observation features are correlated (e.g., adjacent words in a sentence). Conditional Random Fields (CRFs), introduced by Lafferty, McCallum, and Pereira in 2001, relax this by modeling the conditional distribution of states given all observations, allowing arbitrary feature functions. BiLSTM-CRF models (Lample et al. 2016) replaced both the HMM emission and the linear CRF potential with a bidirectional LSTM encoder, achieving state-of-the-art NER and POS tagging. Since 2018, Transformer-based models (BERT, RoBERTa) have further supplanted CRFs for most sequence labeling tasks by encoding full-sequence context with self-attention. HMMs remain relevant where interpretability matters, data is limited, or real-time inference is required.
      </Callout>

      {/* ======================================================================
          6. VISUAL WALKTHROUGH
          ====================================================================== */}
      <H2>6. Visual walkthrough</H2>

      <H3>6a. Transition and emission matrices</H3>

      <Prose>
        The Rabiner weather HMM in full. The transition matrix {"A"} shows strong diagonal structure (both states are self-persistent: {"A_{RR}=0.70"}, {"A_{SS}=0.60"}). The emission matrix <em>B</em> shows the discrimination power of each observation: Clean is highly informative (0.5 Rainy vs. 0.1 Sunny), Walk is highly informative in the opposite direction (0.1 Rainy vs. 0.6 Sunny), and Shop is nearly neutral (0.4 vs. 0.3).
      </Prose>

      <Heatmap
        label="Transition matrix A — Rainy/Sunny weather HMM"
        matrix={[[0.70, 0.30], [0.40, 0.60]]}
        rowLabels={["From: Rainy", "From: Sunny"]}
        colLabels={["To: Rainy", "To: Sunny"]}
        colorScale="gold"
      />

      <Heatmap
        label="Emission matrix B — observation likelihoods per state"
        matrix={[[0.10, 0.40, 0.50], [0.60, 0.30, 0.10]]}
        rowLabels={["Rainy", "Sunny"]}
        colLabels={["Walk", "Shop", "Clean"]}
        colorScale="green"
      />

      <H3>6b. Viterbi trellis — 4-step walkthrough</H3>

      <StepTrace
        label="Viterbi trellis: Walk → Shop → Walk → Clean"
        steps={[
          {
            label: "t=0: Observe Walk (o=0)",
            render: () => (
              <Prose>
                {"Initialize: δ_0(Rainy) = π_R · B_{R,Walk} = 0.6 × 0.1 = 0.060  →  log = -2.813"}<br/>
                {"         δ_0(Sunny) = π_S · B_{S,Walk} = 0.4 × 0.6 = 0.240  →  log = -1.427"}<br/>
                Sunny leads by a large margin — walking is 6× more likely on a sunny day. Both back-pointers {"ψ_0"} are set to 0 (no predecessor). The trellis has two live cells; Sunny is clearly favored.
              </Prose>
            ),
          },
          {
            label: "t=1: Observe Shop (o=1)",
            render: () => (
              <Prose>
                {"Best predecessor for Rainy at t=1: max over {Rainy→Rainy: log -2.813 + log 0.7 = -3.169, Sunny→Rainy: log -1.427 + log 0.4 = -2.341} → best = Sunny, score = -2.341. Add log B_{R,Shop}=log 0.4 = -0.916. δ_1(Rainy)=-3.257, ψ_1(Rainy)=Sunny."}<br/>
                {"Best predecessor for Sunny at t=1: max over {Rainy→Sunny: -2.813+log0.3=-4.016, Sunny→Sunny: -1.427+log0.6=-1.938} → best=Sunny, score=-1.938. Add log B_{S,Shop}=log0.3=-1.204. δ_1(Sunny)=-3.142, ψ_1(Sunny)=Sunny."}<br/>
                Sunny barely leads (-3.14 vs -3.26). Shopping is slightly more likely on rainy days (0.4 vs 0.3), but Sunny's strong lead from t=0 is not yet erased.
              </Prose>
            ),
          },
          {
            label: "t=2: Observe Walk (o=0)",
            render: () => (
              <Prose>
                {"δ_2(Rainy): best predecessor is Sunny (-3.142+log0.4=-4.059). Add log B_{R,Walk}=log0.1=-2.303. δ_2(Rainy)=-6.362. ψ_2(Rainy)=Sunny."}<br/>
                {"δ_2(Sunny): best predecessor is Sunny (-3.142+log0.6=-3.664). Add log B_{S,Walk}=log0.6=-0.511. δ_2(Sunny)=-4.175. ψ_2(Sunny)=Sunny."}<br/>
                Sunny now leads convincingly (-4.18 vs -6.36). Another Walk observation reinforces the Sunny streak — the path is accumulating evidence for three consecutive sunny days.
              </Prose>
            ),
          },
          {
            label: "t=3: Observe Clean (o=2) — back-trace",
            render: () => (
              <Prose>
                {"δ_3(Rainy): best predecessor is Sunny (-4.175+log0.4=-5.090). Add log B_{R,Clean}=log0.5=-0.693. δ_3(Rainy)=-5.783. ψ_3(Rainy)=Sunny."}<br/>
                {"δ_3(Sunny): best predecessor is Sunny (-4.175+log0.6=-4.687). Add log B_{S,Clean}=log0.1=-2.303. δ_3(Sunny)=-6.990. ψ_3(Sunny)=Sunny."}<br/>
                {"Rainy wins at t=3 (-5.78 vs -6.99). Back-trace: path[-1]=Rainy → ψ_3(Rainy)=Sunny → ψ_2(Sunny)=Sunny → ψ_1(Sunny)=Sunny."}<br/>
                <strong>Final Viterbi path: [Sunny, Sunny, Sunny, Rainy].</strong> The model correctly identifies the pattern: three sunny days (Walk, Shop, Walk) followed by a rainy day that caused indoor cleaning. Log P(best path) = -5.773.
              </Prose>
            ),
          },
        ]}
      />

      <H3>6c. Baum-Welch log-likelihood convergence</H3>

      <Plot
        label="Baum-Welch log-likelihood convergence (T=200 observations, 2 states)"
        xLabel="EM iteration"
        yLabel="log P(O | λ)"
        series={[
          {
            name: "log-likelihood",
            color: colors.gold,
            points: [
              [0, -268.91], [1, -219.04], [2, -218.52], [3, -218.27],
              [4, -218.08], [6, -217.78], [9, -217.52], [14, -217.37],
              [19, -217.29], [24, -217.25], [29, -217.24],
            ],
          },
        ]}
      />

      <Prose>
        The classic EM convergence shape: a steep drop in the first 1–2 iterations (from -268.9 to -219.0), followed by progressively smaller improvements as the algorithm approaches a local optimum. The monotone non-decrease property of EM is visible — the curve never goes up. By iteration 29, the log-likelihood has stabilized at -217.24.
      </Prose>

      <H3>6d. Gamma heatmap — state posteriors over time</H3>

      <Prose>
        The gamma matrix {"γ_t(i)"} from the 4-step weather sequence gives the full posterior over states at each time step. Each row sums to 1. High values (bright cells) indicate confident state attribution; values near 0.5 indicate genuine ambiguity.
      </Prose>

      <Heatmap
        label="γ_t(i) — state posteriors: rows=time steps, cols=states"
        matrix={[
          [0.1949, 0.8051],
          [0.4338, 0.5662],
          [0.2363, 0.7637],
          [0.8051, 0.1949],
        ]}
        rowLabels={["t=0 Walk", "t=1 Shop", "t=2 Walk", "t=3 Clean"]}
        colLabels={["Rainy", "Sunny"]}
        colorScale="purple"
      />

      {/* ======================================================================
          7. DECISION MATRIX
          ====================================================================== */}
      <H2>7. Decision matrix</H2>

      <Prose>
        HMMs are not always the right tool for sequence modeling. Here is a concrete guide to when each model family wins.
      </Prose>

      <StepTrace
        label="HMM vs. CRF vs. RNN vs. Transformer"
        steps={[
          {
            label: "Hidden Markov Model",
            render: () => (
              <Prose>
                <strong>Use when:</strong> you have discrete latent states with a Markov structure; you need a generative model (can sample sequences, compute likelihoods, detect anomalies); your training data is limited ({"<"} 10k sequences); you need interpretable transition and emission probabilities that domain experts can inspect. Also natural when you need online inference — the forward algorithm processes one observation at a time with constant memory per state.<br/><br/>
                <strong>Wins on:</strong> financial regime detection (states = bull/bear/sideways), genomics (CpG islands, gene structure), activity recognition with sensor streams, small-data sequence labeling.<br/><br/>
                <strong>Key limitation:</strong> the observation independence assumption — given the current state, the observation at time <em>t</em> is independent of all other observations. This fails when adjacent observations are directly correlated (consecutive words, correlated sensor readings).
              </Prose>
            ),
          },
          {
            label: "Conditional Random Field (CRF)",
            render: () => (
              <Prose>
                <strong>Use when:</strong> you have discriminative goals (sequence labeling, not generation); you want to condition on rich overlapping features of the entire input sequence; you need to avoid the HMM independence assumption without going full neural. The linear-chain CRF is a direct generalization: it models {"P(states | observations)"} directly, allowing arbitrary feature functions of adjacent state pairs and arbitrary windows of observations.<br/><br/>
                <strong>Wins on:</strong> named entity recognition with hand-crafted features, POS tagging with rich morphological features, medical record extraction where feature engineering is possible and interpretability is required.<br/><br/>
                <strong>Key limitation:</strong> feature engineering overhead; no generative capability; typically cannot handle long-range dependencies beyond the local window.
              </Prose>
            ),
          },
          {
            label: "RNN / BiLSTM-CRF",
            render: () => (
              <Prose>
                <strong>Use when:</strong> you have thousands of labeled sequences; observations are high-dimensional (raw text, audio features); you need the model to learn its own features rather than hand-craft them. BiLSTM-CRF (Lample et al. 2016) became the standard NER architecture from 2016–2018: the LSTM encodes context in both directions, the CRF layer enforces valid label transitions. The combination removes the need for explicit feature engineering while retaining structured prediction at the output.<br/><br/>
                <strong>Wins on:</strong> NER, POS tagging, chunking on medium-scale datasets (10k–100k sentences). Still competitive when labeled data is limited because it is more data-efficient than Transformers.<br/><br/>
                <strong>Key limitation:</strong> sequential computation prevents parallelism; vanishing gradients over very long sequences even with LSTM gating; requires labeled data for the CRF layer.
              </Prose>
            ),
          },
          {
            label: "Transformer (BERT, etc.)",
            render: () => (
              <Prose>
                <strong>Use when:</strong> you have access to large pretrained models and your labeled dataset is at least moderately sized ({">"} 1k examples); your sequence length fits within the context window (512–8k tokens for most practical models); you need state-of-the-art accuracy on standard benchmarks.<br/><br/>
                <strong>Wins on:</strong> essentially all standard NLP sequence labeling tasks since 2018. Fine-tuning BERT for NER or POS tagging consistently outperforms BiLSTM-CRF with less task-specific engineering. Self-attention captures arbitrary-range dependencies in {"O(T²)"} rather than{"O(T)"} sequentially.<br/><br/>
                <strong>Key limitation:</strong> quadratic attention cost in sequence length; requires GPU hardware for fine-tuning; no explicit interpretable structure; not a generative model in the HMM sense; no built-in guarantee that output label sequences are globally consistent.
              </Prose>
            ),
          },
        ]}
      />

      {/* ======================================================================
          8. WHAT SCALES AND WHAT DOESN'T
          ====================================================================== */}
      <H2>8. What scales and what doesn't</H2>

      <H3>8.1 Inference complexity</H3>

      <Prose>
        The forward algorithm is {"O(T · N²)"} in time and {"O(T · N)"} in space to store the full alpha matrix (needed for Baum-Welch). For T = 10,000 and N = 50, this is 25 million operations per sequence — completely manageable. At N = 500, it becomes 2.5 billion per sequence — still feasible but slow for large training sets. At N = 5,000, it becomes 250 billion — infeasible without approximation.
      </Prose>

      <Prose>
        The Viterbi algorithm has the same {"O(T · N²)"} complexity and {"O(T · N)"} space (the back-pointer matrix). This is tight — you cannot reduce the N² factor without additional structure (e.g., if A is sparse or has low-rank structure). In speech recognition, the number of effective HMM states can run into the millions when modeling full words and phrases, which is why beam search (Viterbi with pruning) became standard: at each time step, only the top-K paths are retained, reducing complexity to {"O(T · K)"} at the cost of no longer being exact.
      </Prose>

      <H3>8.2 Training complexity</H3>

      <Prose>
        Each Baum-Welch iteration runs {"O(T · N²)"} for forward-backward and {"O(T · N² + T · N · M)"} to compute the xi and update B (the extra {"N · M"} term comes from re-estimating the emission matrix over all M symbols). For large emission vocabularies (e.g., word-level language models where M = 50,000), the {"T · N · M"} term dominates. This is why HMM language models never competed with n-grams at scale — the emission matrix update becomes prohibitively expensive.
      </Prose>

      <Prose>
        For continuous-observation HMMs (GaussianHMM), the emission update requires computing a weighted covariance matrix per state — {"O(T · N · D²)"} where D is the observation dimension. For full covariance matrices in high dimensions (D = 100), this is expensive and numerically fragile. Diagonal covariance (assuming independent dimensions) reduces this to {"O(T · N · D)"} and is the practical standard. Full covariance is feasible up to D ~ 50–100; beyond that, use tied covariance (all states share one covariance matrix) or diagonal.
      </Prose>

      <H3>8.3 When to reach for structured approximations</H3>

      <Prose>
        For N beyond a few hundred states, three approximation families are standard. <strong>Beam search (Viterbi with pruning):</strong> keep only the top-K paths at each time step. Exact at K = N, approximate but fast at K ~ 10–50. <strong>Factorial HMMs</strong> (Ghahramani and Jordan 1997): decompose a large state space as a product of smaller independent chains; exact inference is still exponential but mean-field approximations are tractable. <strong>Variational inference:</strong> replace exact EM with a variational lower bound that is tractable to optimize for structured models. All three are research-level tools — if you find yourself needing them, the literature on structured prediction and approximate inference is the right place to start.
      </Prose>

      {/* ======================================================================
          9. FAILURE MODES & GOTCHAS
          ====================================================================== */}
      <H2>9. Failure modes and gotchas</H2>

      <H3>9.1 Numerical underflow — always use log-space</H3>

      <Prose>
        This is the single most common HMM implementation bug. The forward variable {"α_t(j)"} is a product of up to <em>T</em> probability values, each in (0, 1). For T = 100 with typical values around 0.3, {"α_{99}(j) ≈ 0.3^{100} ≈ 10^{-52}"} — below the float64 minimum of {"~10^{-308}"} only because of the N-dimensional summation, but for longer sequences or more states, underflow to exact zero is inevitable. Once alpha is zero, every downstream computation — gamma, xi, the M-step updates — becomes 0/0 or NaN. The fix is non-negotiable: implement the forward and backward passes entirely in log-space using log-sum-exp. NumPy provides <Code>{"np.logaddexp"}</Code> for pairs and <Code>{"np.logaddexp.reduce"}</Code> for arrays. Never attempt naive scaling tricks (dividing by a constant at each step) in new code — log-space is cleaner, numerically stable, and only marginally slower.
      </Prose>

      <H3>9.2 Local optima and initialization sensitivity</H3>

      <Prose>
        Baum-Welch maximizes the observed-data log-likelihood, which is generally non-convex in the HMM parameters. Different initializations converge to different local optima. In practice, run Baum-Welch from multiple random starting points (5–20 in typical usage) and keep the solution with the highest final log-likelihood. A particularly bad initialization is uniform: if {"π"}, {"A"}, and {"B"} are all uniform at the start, the E-step produces identical responsibilities for all states, and the M-step cannot distinguish them — you are stuck at a saddle point where all states are identical. Always break symmetry by perturbing initialization, or use k-means on the observation sequence to initialize state-conditional means.
      </Prose>

      <H3>9.3 Label switching</H3>

      <Prose>
        As demonstrated in Section 4d, Baum-Welch can assign state indices in any order. The likelihood surface is symmetric under permutations of the state indices — swapping state 0 and state 1 everywhere in {"(π, A, B)"} gives an identical likelihood. This means you cannot meaningfully compare parameters across independent runs by their raw index. When you need to match states across runs (e.g., to average multiple initializations), use the Hungarian algorithm to find the permutation that minimizes parameter distance. When reporting results, label states by their characteristics (the "high-Walk" state, the "high-Clean" state) rather than their index.
      </Prose>

      <H3>9.4 Model selection: choosing the number of states N</H3>

      <Prose>
        The number of hidden states is a hyperparameter that must be set before training. More states always improve the training log-likelihood (the model has more capacity), so likelihood alone cannot choose N. The two standard tools are information criteria: AIC = {"2k - 2 log P(O|λ)"} and BIC = {"k log T - 2 log P(O|λ)"}, where <em>k</em> is the number of free parameters {"(N(N-1) + N(M-1) + N-1 for a categorical HMM)"}. BIC penalizes complexity more harshly than AIC and tends to prefer smaller N. In practice: fit models with N = 2, 3, 4, ..., up to some maximum; plot log-likelihood, AIC, and BIC against N; look for an "elbow" in the curve. For applications where the true number of states is known from domain knowledge (two market regimes, four activity types), use that.
      </Prose>

      <H3>9.5 The observation independence assumption</H3>

      <Prose>
        Given the current state, the HMM assumes observations are drawn independently — {"P(o_t | s_t, o_{t-1}, o_{t-2}, ...) = P(o_t | s_t)"}. This is violated whenever adjacent observations share local correlations not explained by the state. In speech, formant frequencies at consecutive frames are strongly correlated even within a single phoneme state. In text, adjacent words have strong co-occurrence patterns beyond what any single POS tag explains. The standard workarounds: for speech, use the delta and delta-delta features (first and second differences) as additional observation dimensions, which make the marginal observations closer to IID given the state. For text, move to CRFs or neural sequence models that explicitly condition on context.
      </Prose>

      <H3>9.6 Degenerate solutions</H3>

      <Prose>
        In continuous HMMs (GaussianHMM), a single component can collapse onto one data point, driving its variance to zero and its likelihood to infinity. This is the same singularity problem as in GMMs. hmmlearn handles this by adding a small floor to covariance matrices; the from-scratch implementation above avoids it because it uses categorical emissions. Watch for degenerate solutions when: a component's expected count drops near zero (the model is trying to eliminate a state); a Gaussian component's covariance shrinks over iterations while its log-likelihood grows. Fix: add a minimum variance floor, use MAP estimation with an inverse-Wishart prior on covariances, or reduce N.
      </Prose>

      {/* ======================================================================
          10. PRIMARY SOURCES
          ====================================================================== */}
      <H2>10. Primary sources</H2>

      <Prose>
        All citations below were WebSearch-verified for author, year, venue, volume, and page numbers. Read them in this order.
      </Prose>

      <StepTrace
        label="primary literature"
        steps={[
          {
            label: "Baum & Petrie 1966 — The founding paper",
            render: () => (
              <Prose>
                Baum, L.E. and Petrie, T. (1966). "Statistical Inference for Probabilistic Functions of Finite State Markov Chains." <em>Annals of Mathematical Statistics</em>, 37(6), 1554–1563. The paper that introduced the HMM and proved that the parameters could be learned from observations alone. Baum and colleagues extended this work in a series of papers through 1972, deriving the Baum-Welch (forward-backward + EM) algorithm in stages. This original paper is readable but terse — Rabiner (1989) is the better tutorial entry point.
              </Prose>
            ),
          },
          {
            label: "Viterbi 1967 — The decoding algorithm",
            render: () => (
              <Prose>
                Viterbi, A.J. (1967). "Error Bounds for Convolutional Codes and an Asymptotically Optimum Decoding Algorithm." <em>IEEE Transactions on Information Theory</em>, 13(2), 260–269. DOI: 10.1109/TIT.1967.1054010. The Viterbi algorithm was developed for decoding convolutional codes in communication systems, not for HMMs. Its application to HMM decoding came later. The algorithm itself is a clean instance of the Bellman optimality principle applied to trellis graphs: max-product belief propagation on a chain-structured graphical model.
              </Prose>
            ),
          },
          {
            label: "Rabiner 1989 — The definitive tutorial",
            render: () => (
              <Prose>
                Rabiner, L.R. (1989). "A Tutorial on Hidden Markov Models and Selected Applications in Speech Recognition." <em>Proceedings of the IEEE</em>, 77(2), 257–286. DOI: 10.1109/5.18626. The canonical reference. Defines the three problems (evaluation, decoding, learning), gives step-by-step algorithms for each, introduces the canonical weather example used in this tutorial, and demonstrates applications to speech recognition. If you read one HMM paper, read this one. The notation used throughout this topic (π, A, B, α, β, γ, ξ) is Rabiner's notation, which has become standard.
              </Prose>
            ),
          },
          {
            label: "Bishop 2006 — PRML Chapter 13",
            render: () => (
              <Prose>
                Bishop, C.M. (2006). <em>Pattern Recognition and Machine Learning</em>. New York: Springer. ISBN: 978-0-387-31073-2. Chapter 13 (Sequential Data) gives the graduate-level treatment: the forward-backward algorithm derived as a special case of the sum-product algorithm on a factor graph, the Viterbi algorithm as max-sum, and extensions to linear dynamical systems (Kalman filter) and general state-space models. The graphical model perspective makes the relationship between HMMs, Kalman filters, and particle filters immediately clear. Available as a free PDF from Microsoft Research.
              </Prose>
            ),
          },
          {
            label: "Murphy 2012 — MLAPP Chapter 17",
            render: () => (
              <Prose>
                Murphy, K.P. (2012). <em>Machine Learning: A Probabilistic Perspective</em>. Cambridge, MA: MIT Press. ISBN: 978-0-262-01802-9. Chapter 17 (Markov and Hidden Markov Models) covers HMMs, the Baum-Welch algorithm, and extensions including input-output HMMs and factorial HMMs. Murphy's treatment is more computational than Bishop's — with more pseudocode and worked examples — making it useful as a reference when implementing. The book also covers the broader graphical models context that HMMs fit into.
              </Prose>
            ),
          },
          {
            label: "Lafferty, McCallum & Pereira 2001 — CRFs",
            render: () => (
              <Prose>
                Lafferty, J., McCallum, A., and Pereira, F. (2001). "Conditional Random Fields: Probabilistic Models for Segmenting and Labeling Sequence Data." <em>Proceedings of the 18th International Conference on Machine Learning (ICML 2001)</em>, pp. 282–289. The paper that introduced CRFs as the discriminative alternative to HMMs for sequence labeling. Understanding the relationship between the HMM generative model ({"P(O, S | λ)"}) and the CRF discriminative model ({"P(S | O, λ)"}) is the key conceptual step from classical HMMs to modern sequence labeling.
              </Prose>
            ),
          },
        ]}
      />

      {/* ======================================================================
          11. SELF-CHECK EXERCISES
          ====================================================================== */}
      <H2>11. Self-check exercises</H2>

      <Prose>
        Work through each exercise before reading the answer. The math sections are prerequisite for exercises 1–3; the code sections for exercises 4–5.
      </Prose>

      <H3>Exercise 1 (recall)</H3>
      <Prose>
        Write the three components of an HMM {"λ = (π, A, B)"}. What are the dimensionality constraints on each? What condition must each matrix satisfy (row-stochastic vs. column-stochastic vs. none)?
      </Prose>
      <Callout type="answer" title="Answer 1">
        {"π"} is the initial state distribution: an N-dimensional vector with {"π_i ≥ 0"} and {"Σ_i π_i = 1"} (sums to 1 — a probability vector, not a matrix). A is the N×N transition matrix: each row sums to 1 ({"Σ_j A_{ij} = 1 for all i"}) — row-stochastic. Columns need not sum to 1. B is the N×M emission matrix: each row sums to 1 ({"Σ_k B_{j,k} = 1 for all j"}) — also row-stochastic. For continuous emissions, B is replaced by a family of density functions (one per state), which integrate to 1 rather than sum to 1.
      </Callout>

      <H3>Exercise 2 (derivation)</H3>
      <Prose>
        Explain why the Viterbi algorithm is correct even though it replaces the sum in the forward algorithm with a max. What property of the max operator makes the dynamic programming recursion valid?
      </Prose>
      <Callout type="answer" title="Answer 2">
        The Viterbi algorithm is correct because the max operator, like the sum, distributes across the Markov factorization of the joint probability. The key property is that {"max(a · c, b · c) = c · max(a, b)"} for {"c > 0"} — you can factor out the local emission term {"B_{j,o_t}"} from the max over incoming paths. This means the best path into state <em>j</em> at time <em>t</em> is determined entirely by the best path into each predecessor state at time {"t-1"}, independently of what happens after time <em>t</em>. This is the Bellman optimality principle: the optimal path through any subgraph is composed of optimal subpaths. The back-pointer {"ψ_t(j) = argmax_i (δ_{t-1}(i) · A_{ij})"} records the choice made at each step, enabling the final back-trace. The forward algorithm uses sum for the same structural reason — sum also distributes across the factorization.
      </Callout>

      <H3>Exercise 3 (conceptual)</H3>
      <Prose>
        You run forward-backward on a 100-step sequence with {"N=3"} states in native (non-log) probability space. After 40 time steps, all {"α_t(i) = 0.0"} exactly. What happened and what is the correct fix?
      </Prose>
      <Callout type="answer" title="Answer 3">
        Numerical underflow. The forward variable {"α_t(j)"} is a product of up to <em>t</em> probability values. Each transition-emission pair multiplies by a value in (0,1). After 40 steps, the product is typically on the order of {"(0.3)^{40} ≈ 10^{-21}"} — still representable in float64. But for longer sequences (T {">"} 200–300 with typical emission probabilities) it underflows to exactly 0.0. Once alpha is zero, gamma and xi become 0/0 = NaN and the M-step produces garbage. The correct fix: implement the forward algorithm entirely in log-space. Compute {"log α_t(j)"} at every step using the log-sum-exp recurrence, and only exponentiate when you need numerical values (e.g., for the gamma computation, which also stays in log-space). Never multiply small probabilities directly for sequences longer than ~50 steps.
      </Callout>

      <H3>Exercise 4 (debugging)</H3>
      <Prose>
        You train a 3-state HMM with Baum-Welch for 100 iterations. The log-likelihood curve decreases at iteration 7 ({"LL_7 < LL_6"}). Your code passes all tests. What is the most likely explanation?
      </Prose>
      <Callout type="answer" title="Answer 4">
        A decrease in log-likelihood is mathematically impossible under correct Baum-Welch — each iteration provably increases (or maintains) the log-likelihood. A decrease in the plotted curve is therefore a numerical issue, not a convergence failure. The most likely cause is numerical underflow in the forward-backward pass: if any {"α_t(j)"} or {"β_t(i)"} underflows to zero before the M-step, the xi and gamma computation produces NaN or zero values, and the re-estimated parameters are incorrect — effectively random — producing a lower-likelihood model. The diagnostic: add an assert that {"LL_{t+1} >= LL_t - 1e-6"} (with a small epsilon for floating-point noise). Switch the entire implementation to log-space as described in Exercise 3. A secondary cause: a bug in the xi normalization — if xi does not sum to 1 correctly, the A update is wrong and can degrade likelihood.
      </Callout>

      <H3>Exercise 5 (applied)</H3>
      <Prose>
        You are using an HMM to detect market regimes (Bull, Bear, Sideways) from daily log-returns. You fit a 3-state GaussianHMM. After fitting, you inspect the learned means and find two states with nearly identical means (both ~0.001) and one with mean ~-0.002. What happened and what should you try?
      </Prose>
      <Callout type="answer" title="Answer 5">
        Baum-Welch converged to a local optimum where two of the three states are nearly identical — effectively the model learned only 2 distinct regimes but wasted a state. This is a common symptom of initialization sensitivity. The two nearly-identical states may have different covariance matrices or different transition probabilities, but their means are degenerate. What to try: (1) Re-run Baum-Welch from multiple random initializations (10–20) and compare final log-likelihoods — a better local optimum may have more clearly separated states. (2) Initialize means with k-means clustering on the return series before running Baum-Welch, to give states well-separated starting means. (3) Evaluate BIC for N=2 vs N=3 — the data may genuinely support only 2 regimes, and using 3 states just splits one regime unnecessarily. (4) Check whether the two similar states have different transition dynamics — if one is a transition state between Bull and Bear with a distinct autocorrelation structure, N=3 may still be the right choice even with similar means.
      </Callout>

      <H3>Exercise 6 (synthesis)</H3>
      <Prose>
        Compare the EM update for a Gaussian Mixture Model (Section on GMMs) to the Baum-Welch update for an HMM. What is the structural analogy between responsibilities in GMM and gamma in HMM? What does the HMM add that GMM lacks, and what price do you pay?
      </Prose>
      <Callout type="answer" title="Answer 6">
        The analogy is exact: GMM responsibilities {"r_{ik} = P(component k | x_i)"} correspond directly to HMM gamma {"γ_t(i) = P(state i | o_t, O, λ)"}. Both are posterior probabilities of a discrete latent variable given the observation. Both drive the M-step: the GMM mean update is a responsibility-weighted average of data points; the HMM emission update is a gamma-weighted count of observation symbols. The GMM mixing weight update is the average responsibility; the HMM initial state update is {"γ_0(i)"}.<br/><br/>
        What the HMM adds: temporal structure through the transition matrix A and the xi terms. The xi update {"Σ_t ξ_t(i,j) / Σ_t γ_t(i)"} has no GMM analogue — it is the expected transition count, which requires the full forward-backward pass. GMM-EM can process data points independently and in any order; HMM Baum-Welch requires the entire sequence to compute alpha and beta, making mini-batch training non-trivial.<br/><br/>
        The price: the forward-backward pass adds {"O(T · N²)"} complexity per sequence vs. {"O(N)"} per point for GMM. The sequence must be loaded fully into memory (or handled with careful streaming). The model is inherently sequential and does not parallelize across time steps as easily as a GMM, which parallelizes trivially across data points.
      </Callout>

    </div>
  ),
};

export default hmmContent;
