# Generated by scripts/build-dsa-library-bridges.mjs
# Owner: src/learn/data/weighted-graph-examples.js; examples: dijkstra, bellman, kruskal, topological
# Rebuild; do not maintain a second hand-edited implementation here.

from math import inf

def adjacency(n, edges, directed=True):
    if not isinstance(n, int) or n < 0:
        raise ValueError("n must be a nonnegative integer")
    graph = [[] for _ in range(n)]
    for edge_id, (u, v, weight) in enumerate(edges):
        if not (isinstance(u, int) and isinstance(v, int) and 0 <= u < n and 0 <= v < n):
            raise ValueError("Vertex outside 0..n-1")
        if not isinstance(weight, int):
            raise ValueError("This exact model requires integer weights")
        graph[u].append((v, weight, edge_id))
        if not directed:
            graph[v].append((u, weight, edge_id))
    return graph

def check_source(n, source):
    if not isinstance(source, int) or not 0 <= source < n:
        raise ValueError("Source outside 0..n-1")

def route(parent, source, target):
    vertices, edge_ids = [target], []
    while target != source:
        if parent[target] is None:
            return None
        previous, edge_id = parent[target]
        edge_ids.append(edge_id)
        vertices.append(previous)
        target = previous
    return vertices[::-1], edge_ids[::-1]

from heapq import heappop, heappush

from itertools import count

def dijkstra(n, edges, source):
    graph = adjacency(n, edges)
    check_source(n, source)
    if any(weight < 0 for _, _, weight in edges):
        raise ValueError("Dijkstra requires nonnegative weights")
    distance, parent = [inf] * n, [None] * n
    distance[source] = 0
    tickets = count()
    heap = [(0, next(tickets), source)]
    stale = []
    while heap:
        cost, _, u = heappop(heap)
        if cost != distance[u]:
            stale.append((u, cost))
            continue
        # This non-stale extraction finalizes u under nonnegative weights.
        for v, weight, edge_id in graph[u]:
            candidate = cost + weight
            if candidate < distance[v]:
                distance[v] = candidate
                parent[v] = (u, edge_id)
                heappush(heap, (candidate, next(tickets), v))
    return distance, parent, stale

from collections import deque

def bellman_ford(n, edges, source):
    graph = adjacency(n, edges)
    check_source(n, source)
    distance = [inf] * n
    distance[source] = 0
    for _ in range(n - 1):
        previous = distance
        distance = previous.copy()
        for u, v, weight in edges:
            if previous[u] != inf:
                distance[v] = min(distance[v], previous[u] + weight)
    affected = {v for u, v, weight in edges
                if distance[u] != inf and distance[u] + weight < distance[v]}
    queue = deque(affected)
    while queue:
        u = queue.popleft()
        for v, _, _ in graph[u]:
            if v not in affected:
                affected.add(v)
                queue.append(v)
    for v in affected:
        distance[v] = -inf
    # Recover finite witnesses through tight edges, avoiding zero-cycle parents.
    parent, seen = [None] * n, set()
    if distance[source] == 0:
        seen.add(source)
        queue.append(source)
    while queue:
        u = queue.popleft()
        for v, weight, edge_id in graph[u]:
            if v not in seen and distance[v] not in (inf, -inf) and distance[u] + weight == distance[v]:
                seen.add(v)
                parent[v] = (u, edge_id)
                queue.append(v)
    return distance, parent

class DisjointSets:
    def __init__(self, n):
        self.parent = list(range(n))
        self.size = [1] * n

    def find(self, vertex):
        while self.parent[vertex] != vertex:
            self.parent[vertex] = self.parent[self.parent[vertex]]
            vertex = self.parent[vertex]
        return vertex

    def union(self, a, b):
        a, b = self.find(a), self.find(b)
        if a == b:
            return False
        if self.size[a] < self.size[b]:
            a, b = b, a
        self.parent[b] = a
        self.size[a] += self.size[b]
        return True

def kruskal(n, edges):
    adjacency(n, edges, directed=False)
    sets = DisjointSets(n)
    accepted, total = [], 0
    for edge_id in sorted(range(len(edges)), key=lambda i: (edges[i][2], i)):
        u, v, weight = edges[edge_id]
        if sets.union(u, v):
            accepted.append(edge_id)
            total += weight
    return total, accepted, n - len(accepted)

def topological_order(n, edges):
    graph = adjacency(n, edges)
    indegree = [0] * n
    for _, v, _ in edges:
        indegree[v] += 1
    ready = deque(v for v in range(n) if indegree[v] == 0)
    order = []
    while ready:
        u = ready.popleft()
        order.append(u)
        for v, _, _ in graph[u]:
            indegree[v] -= 1
            if indegree[v] == 0:
                ready.append(v)
    if len(order) != n:
        raise ValueError("Directed cycle: no complete topological order")
    return order

def dfs_order_or_cycle(n, edges):
    graph = adjacency(n, edges)
    color, finished = [0] * n, []
    for start in range(n):
        if color[start]:
            continue
        color[start] = 1
        frames = [(start, 0)]
        active = [start]
        positions = {start: 0}
        while frames:
            u, index = frames[-1]
            if index == len(graph[u]):
                frames.pop()
                active.pop()
                del positions[u]
                color[u] = 2
                finished.append(u)
                continue
            frames[-1] = (u, index + 1)
            v = graph[u][index][0]
            if color[v] == 1:
                return None, active[positions[v]:] + [v]
            if color[v] == 0:
                color[v] = 1
                positions[v] = len(active)
                active.append(v)
                frames.append((v, 0))
    return finished[::-1], None
