# Generated by scripts/build-dsa-library-bridges.mjs
# Owner: src/learn/data/graph-traversal-examples.js; examples: breadthFirst, depthFirst, components
# Rebuild; do not maintain a second hand-edited implementation here.

from collections import deque

def build_graph(vertices, edges, directed=False):
    vertices = list(vertices)
    if any(vertex is None for vertex in vertices):
        raise ValueError("None is reserved for a missing parent")
    if len(set(vertices)) != len(vertices):
        raise ValueError("vertex labels must be unique")
    graph = {vertex: [] for vertex in vertices}
    neighbors_seen = {vertex: set() for vertex in vertices}
    def connect(first, second):
        if second not in neighbors_seen[first]:
            graph[first].append(second)
            neighbors_seen[first].add(second)
    for first, second in edges:
        if first not in graph or second not in graph:
            raise ValueError("every endpoint must be a declared vertex")
        connect(first, second)
        if not directed:
            connect(second, first)
    return graph

def bfs(graph, source):
    if source not in graph:
        raise KeyError("unknown source")
    distance = {source: 0}
    parent = {source: None}
    queue = deque([source])
    order = []
    while queue:
        vertex = queue.popleft()
        order.append(vertex)
        for neighbor in graph[vertex]:
            if neighbor not in distance:
                distance[neighbor] = distance[vertex] + 1
                parent[neighbor] = vertex
                queue.append(neighbor)
    return order, distance, parent

def path_to(parent, target):
    if target not in parent:
        return None
    path = []
    while target is not None:
        path.append(target)
        target = parent[target]
    path.reverse()
    return path

def dfs_frames(graph, source):
    if source not in graph:
        raise KeyError("unknown source")
    parent = {source: None}
    entered = [source]
    finished = []
    stack = [(source, iter(graph[source]))]
    while stack:
        vertex, neighbors = stack[-1]
        try:
            neighbor = next(neighbors)
        except StopIteration:
            finished.append(vertex)
            stack.pop()
            continue
        if neighbor not in parent:
            parent[neighbor] = vertex
            entered.append(neighbor)
            stack.append((neighbor, iter(graph[neighbor])))
    return entered, finished, parent

def connected_components(graph):
    # Requires an undirected graph with every vertex declared.
    label = {}
    groups = []
    for start in graph:
        if start in label:
            continue
        component_id = len(groups)
        group = []
        queue = deque([start])
        label[start] = component_id
        while queue:
            vertex = queue.popleft()
            group.append(vertex)
            for neighbor in graph[vertex]:
                if neighbor not in label:
                    label[neighbor] = component_id
                    queue.append(neighbor)
        groups.append(group)
    return groups, label
