# Generated by scripts/build-dsa-library-bridges.mjs
# Owner: src/learn/data/persistent-structures-examples.js; examples: point
# Rebuild; do not maintain a second hand-edited implementation here.

from dataclasses import dataclass

@dataclass(frozen=True, eq=False)
class Node:
    low: int
    high: int
    total: int
    left: "Node | None" = None
    right: "Node | None" = None

def build(values):
    values = tuple(values)
    if any(type(value) is not int for value in values):
        raise ValueError("Integer payloads required")
    def visit(low, high):
        if low == high:
            return None
        if high - low == 1:
            return Node(low, high, values[low])
        middle = (low + high) // 2
        left, right = visit(low, middle), visit(middle, high)
        return Node(low, high, left.total + right.total, left, right)
    return visit(0, len(values))

def assign(root, index, value):
    if type(index) is not int or root is None or not root.low <= index < root.high:
        raise IndexError("Index outside this array")
    if type(value) is not int:
        raise ValueError("Integer payload required")
    def visit(node):
        if node.high - node.low == 1:
            return node if node.total == value else Node(node.low, node.high, value)
        middle = (node.low + node.high) // 2
        left = visit(node.left) if index < middle else node.left
        right = visit(node.right) if index >= middle else node.right
        if left is node.left and right is node.right:
            return node
        return Node(node.low, node.high, left.total + right.total, left, right)
    return visit(root)

def range_sum(root, low, high):
    size = 0 if root is None else root.high
    if type(low) is not int or type(high) is not int or not 0 <= low <= high <= size:
        raise ValueError("Use a half-open range inside the array")
    def visit(node):
        if node is None or low == high or node.high <= low or high <= node.low:
            return 0
        if low <= node.low and node.high <= high:
            return node.total
        return visit(node.left) + visit(node.right)
    return visit(root)

def identities(roots):
    reached = set()
    def visit(node):
        if node is None or node in reached:
            return
        reached.add(node)
        visit(node.left)
        visit(node.right)
    for root in roots:
        visit(root)
    return reached
