# Generated by scripts/build-dsa-library-bridges.mjs
# Owner: src/learn/data/randomized-algorithm-examples.js; examples: shuffle, weighted, reservoir
# Rebuild; do not maintain a second hand-edited implementation here.

from collections import Counter

from itertools import product

from random import Random

def shuffled(values, rng):
    result = list(values)
    for end in range(len(result) - 1, 0, -1):
        chosen = rng.randrange(end + 1)
        result[end], result[chosen] = result[chosen], result[end]
    return result

def all_three_paths():
    counts = Counter()
    for first, second in product(range(3), range(2)):
        values = list("ABC")
        for end, chosen in [(2, first), (1, second)]:
            values[end], values[chosen] = values[chosen], values[end]
        counts["".join(values)] += 1
    return sorted(counts.items())

from bisect import bisect_right

from itertools import accumulate

class WeightedPicker:
    def __init__(self, weights):
        if not weights or any(type(w) is not int or w < 0 for w in weights):
            raise ValueError("weights must be nonnegative integers")
        self.ends = list(accumulate(weights))
        if self.ends[-1] == 0:
            raise ValueError("total weight must be positive")

    def pick(self, rng):
        ticket = rng.randrange(self.ends[-1])
        return bisect_right(self.ends, ticket)

def reservoir(stream, capacity, rng):
    if type(capacity) is not int or capacity < 0:
        raise ValueError("capacity must be a nonnegative integer")
    sample = []
    if capacity == 0:
        return sample
    for seen, record in enumerate(stream, start=1):
        if seen <= capacity:
            sample.append(record)
        else:
            chosen = rng.randrange(seen)
            if chosen < capacity:
                sample[chosen] = record
    return sample
