import { useState } from 'react';
import { NeuralLab, NeuralSelect, NeuralTable, NeuralPlot as BasePlot, formatNeural as f } from './NeuralLessonElements.jsx';
import { NeuralNumber } from './NeuralNumberControl.jsx';
import { lionTrace, sampledCurvature, hessianProbes, prodigyTrace, scheduleFreeTrace } from '../../data/advanced-optimizer-models.js';
import { OptimizerFigure, OptimizerNumberLine } from './AdvancedOptimizerDiagrams.jsx';
import './advanced-optimizer-labs.css';
import './neural-lesson-neutral.css';
export const vector = row => `[${row.map(v => f(v, 6)).join(', ')}]`;
export function OptimizerPlot(props) { return <div className="optimizer-plot" tabIndex={0} role="region" aria-label={`${props.title}: horizontally scrollable chart`}><BasePlot {...props} /></div>; }
function SequenceEditor({ label, values, onChange, min, max }) {
  const [selected, setSelected] = useState(0);
  const index = Math.min(selected, values.length - 1);
  return <fieldset><legend>{label}</legend><div className="optimizer-controls"><NeuralSelect label={`${label}: selected step`} value={index} onChange={v => setSelected(Number(v))} options={values.map((v, i) => [i, `${i + 1}: ${f(v, 3)}`])} /><NeuralNumber label={`${label}: current value`} value={values[index]} min={min} max={max} range={false} onChange={v => onChange(values.map((old, i) => i === index ? v : old))} /></div><p>Current sequence: {vector(values)}.</p><div className="optimizer-actions"><button disabled={values.length >= 12} onClick={() => { onChange([...values, 0]); setSelected(values.length); }}>Append zero step</button><button disabled={values.length <= 1} onClick={() => { onChange(values.filter((_, i) => i !== index)); setSelected(Math.max(0, index - 1)); }}>Remove selected step</button></div></fieldset>;
}
const lionInitial = { initial: -.4, momentum: -.3, gradients: [2, 2, 2], rate: .02, decay: .1, beta1: .9, beta2: .99 };
export function LionDirectionLab() {
  const [state, setState] = useState(lionInitial), [index, setIndex] = useState(0);
  const rows = lionTrace(state), row = rows[Math.min(index, rows.length - 1)];
  return <NeuralLab id="optimizer-lion" title="When does new evidence beat stored history?">
    <p>Fresh constructed sequence. The full trace is already computed; selecting a step inspects its actual old history and update. Every edit restarts from the stated initial weight/history.</p>
    <div className="optimizer-controls">{[['initial', 'Initial weight', -10, 10], ['momentum', 'Initial momentum', -10, 10], ['rate', 'Learning rate η', 0, .2], ['decay', 'Weight decay λ', 0, 1]].map(([key, label, min, max]) => <NeuralNumber key={key} label={label} value={state[key]} min={min} max={max} range={false} onChange={v => setState(s => ({ ...s, [key]: v }))} />)}</div>
    <SequenceEditor label="Gradient sequence" values={state.gradients} min={-10} max={10} onChange={gradients => setState(s => ({ ...s, gradients }))} />
    <NeuralSelect label="Inspect Lion update" value={Math.min(index, rows.length - 1)} onChange={v => setIndex(Number(v))} options={rows.map((r, i) => [i, `Update ${r.step}`])} />
    <OptimizerNumberLine title={`Update ${row.step}: add before taking a sign`} values={[{ label: 'old-history contribution β₁m', value: row.historyPart }, { label: 'current-gradient contribution (1−β₁)g', value: row.freshPart }, { label: `blend; sign ${row.direction}`, value: row.blend }]} caption={`The sign is computed from the sum, not from the current gradient alone. The selected weight moves from ${f(row.parameter, 6)} to ${f(row.shrunk, 6)} by decay, then to ${f(row.next, 6)} by the signed step.`} />
    <NeuralTable caption="Complete current parameter and memory trajectory" headers={['Step', 'Old θ', 'Old m', 'g', 'Blend', 'Sign', 'After decay', 'New θ', 'New m']} rows={rows.map(r => [r.step, r.parameter, r.memory, r.gradient, r.blend, r.direction, r.shrunk, r.next, r.nextMemory].map((v, i) => i === 0 ? v : f(v, 7)))} />
    <p>New memory uses β₂={state.beta2}: {f(state.beta2 * row.memory, 6)} + {f((1 - state.beta2) * row.gradient, 6)} = {f(row.nextMemory, 6)}. β₁={state.beta1} instead chooses the present step. With η=0, memory can still change.</p>
    <details><summary>Edit the two distinct blend coefficients</summary><div className="optimizer-controls">{['beta1', 'beta2'].map(key => <NeuralNumber key={key} label={key} value={state[key]} min={0} max={.999} range={false} onChange={v => setState(s => ({ ...s, [key]: v }))} />)}</div></details>
    <div className="optimizer-actions"><button onClick={() => setState(s => ({ ...s, gradients: [4, 4, 4] }))}>Same positive signs, larger magnitudes</button><button onClick={() => setState(s => ({ ...s, momentum: 0, gradients: [0], decay: 0 }))}>Zero-history no-decay null</button><button onClick={() => { setState(lionInitial); setIndex(0); }}>Reset Lion</button></div>
  </NeuralLab>;
}
export function SophiaInstrumentsLab() {
  const [inputs, setInputs] = useState([3, 1]), [probabilities, setProbabilities] = useState([.25, .6]), [labels, setLabels] = useState([1, 0]);
  const [matrix, setMatrix] = useState([4, -2, 1]), [probe, setProbe] = useState(0);
  const result = sampledCurvature(inputs, probabilities, labels), h = hessianProbes(...matrix);
  const edit = (setter, i, v) => setter(a => a.map((old, j) => i === j ? v : old));
  return <NeuralLab id="optimizer-sophia" title="Two curvature instruments, two different inputs">
    <h4>Enumerate model-sampled labels</h4><p>Two independent binary examples. Real labels define the training gradient. Model probabilities define the separate sampled-label instrument.</p>
    <div className="optimizer-controls">{[0, 1].map(i => <fieldset key={i}><legend>Example {i + 1}</legend><NeuralNumber label={`Input x${i + 1}`} value={inputs[i]} min={-5} max={5} range={false} onChange={v => edit(setInputs, i, v)} /><NeuralNumber label={`Probability p${i + 1}`} value={probabilities[i]} min={.01} max={.99} range={false} onChange={v => edit(setProbabilities, i, v)} /><NeuralSelect label={`Real label ${i + 1}`} value={labels[i]} onChange={v => edit(setLabels, i, Number(v))} options={[[0, '0'], [1, '1']]} /></fieldset>)}</div>
    <OptimizerFigure title="Four independent label pairs exhaust this instrument" width={660} height={265} description="Each path multiplies its two sampling probabilities. Its leaf contains B=2 times the squared mean gradient. Summing probability × estimate across all four leaves matches the analytic average curvature.">{marker => <>
      <text x="30" y="138">sample y₁</text>{[0, 1].map(a => <g key={a}><path d={`M95 133 L200 ${65 + a * 140}`} fill="none" stroke="#dcb764" markerEnd={marker} /><text x="208" y={70 + a * 140}>y₁={a}: {f(a ? probabilities[0] : 1 - probabilities[0])}</text>{[0, 1].map(b => { const r = result.outcomes[a * 2 + b]; return <g key={b}><path d={`M295 ${65 + a * 140} L355 ${30 + a * 140 + b * 60}`} fill="none" stroke="#aaa" markerEnd={marker} /><text x="362" y={35 + a * 140 + b * 60}>({a},{b}) mass {f(r.probability)}; estimate {f(r.estimate)}</text></g>; })}</g>)}
    </>}</OptimizerFigure>
    <NeuralTable caption="Exact outcome enumeration" headers={['Sampled pair', 'Probability', 'Mean ĝ', '2ĝ²', 'Weighted contribution']} rows={result.outcomes.map(r => [r.sampled.join(', '), f(r.probability, 6), f(r.gradient, 6), f(r.estimate, 6), f(r.contribution, 6)])} />
    <p>Expected sampled estimate <strong>{f(result.expectation, 8)}</strong>; analytic mean x²p(1−p) <strong>{f(result.exact, 8)}</strong>; real-label mean gradient squared <strong>{f(result.trueSquare, 8)}</strong>. Omitting B gives {f(result.expectation / 2, 8)}. Changing only real labels leaves the first two quantities unchanged.</p>
    <h4>Probe an actual symmetric Hessian</h4><div className="optimizer-controls">{['H₁₁', 'H₁₂ = H₂₁', 'H₂₂'].map((label, i) => <NeuralNumber key={label} label={label} value={matrix[i]} min={-6} max={6} range={false} onChange={v => edit(setMatrix, i, v)} />)}<NeuralSelect label="Highlighted sign probe" value={probe} onChange={v => setProbe(Number(v))} options={h.values.map((r, i) => [i, vector(r.u)])} /></div>
    <OptimizerNumberLine title={`Selected u⊙Hu: ${vector(h.values[probe].u)}`} values={h.values[probe].estimate.map((v, i) => ({ label: `estimated diagonal coordinate ${i + 1}`, value: v }))} caption={`True diagonal ${vector(h.mean)}. Eigenvalues ${vector(h.eigenvalues)}. A negative sampled coordinate alone does not determine the matrix's eigenvalues.`} />
    <NeuralTable caption="All four equally weighted probes" headers={['u', 'u⊙Hu']} rows={h.values.map(r => [vector(r.u), vector(r.estimate)])} />
    <div className="optimizer-actions"><button onClick={() => setMatrix(m => [m[0], 0, m[2]])}>Remove off-diagonal coupling</button><button onClick={() => { setInputs([0, 0]); setMatrix([0, 0, 0]); }}>Zero-input and zero-H nulls</button><button onClick={() => { setInputs([3, 1]); setProbabilities([.25, .6]); setLabels([1, 0]); setMatrix([4, -2, 1]); setProbe(0); }}>Reset instruments</button></div>
  </NeuralLab>;
}
export function ProdigyScaleLab({ worked = false }) {
  const [settings, setSettings] = useState({ initial: 1, target: -2, distance: .01, rate: .3, steps: 12 }), [selected, setSelected] = useState(2);
  const s = worked ? { initial: 0, target: 3, distance: .01, rate: 1, steps: 12 } : settings;
  const result = prodigyTrace(s.initial, s.target, s.distance, s.rate, s.steps), rows = result.rows, row = rows[Math.min(selected, rows.length - 1)];
  const first = rows.find(r => r.distance_next > r.distance_used + 1e-15);
  const trace = <><OptimizerPlot title="Paper Algorithm 4: parameter trajectory" xLabel="update" yLabel="parameter θ" xDomain={[0, s.steps]} yDomain={[Math.min(s.initial, s.target, ...rows.map(r => r.after)) - .25, Math.max(s.initial, s.target, ...rows.map(r => r.after)) + .25]} series={[{ label: 'Calculated θ', values: [[0, s.initial], ...rows.map(r => [r.step, r.after])], color: '#e4b65a' }, { label: 'Declared bowl target', values: [[0, s.target], [s.steps, s.target]], color: '#aaa', dashed: true }]} /><NeuralTable caption="Scale used now versus retained next" headers={['Step', 'θ after', 'Loss', 'd used', 'd next']} rows={rows.map(r => [r.step, f(r.after, 7), f(r.loss, 7), f(r.distance_used, 8), f(r.distance_next, 8)])} /></>;
  if (worked) return <figure className="optimizer-figure"><figcaption>Worked trace: automatic scale growth includes the overshoot</figcaption>{trace}<OptimizerNumberLine title="Worked update 3: observed displacement supplies evidence" values={[{ label: 'initial', value: s.initial }, { label: 'before', value: row.before }, { label: 'after', value: row.after }, { label: 'objective target', value: s.target }]} caption={`Gradient ${f(row.gradient, 7)}; g(θ₀−θ)=${f(row.gradient * (s.initial - row.before), 7)}; accumulated numerator ${row.numerator.toExponential(5)}; denominator |s|=${row.denominator.toExponential(5)}. Old d=${f(row.distance_used, 8)} is used now; new d=${f(row.distance_next, 8)} is stored for the next step.`} /><p>The target defines the quadratic gradient. It is not supplied to the distance estimator as an oracle.</p></figure>;
  return <NeuralLab id="optimizer-prodigy" title="An adapting scale can cross the target and keep moving">
    <div className="optimizer-controls">{[['initial', 'Initial θ', -5, 5], ['target', 'Bowl target', -5, 5], ['distance', 'Initial d', 1e-6, .1], ['rate', 'Multiplier γ', .1, 1], ['steps', 'Updates', 1, 24]].map(([key, label, min, max]) => <NeuralNumber key={key} label={label} value={s[key]} min={min} max={max} integer={key === 'steps'} range={false} onChange={v => setSettings(old => ({ ...old, [key]: v }))} />)}</div>
    {trace}<p>First retained scale increase: {first ? `after update ${first.step}; used by the next update` : 'none in this trace'}. {result.stopped ? `The calculation became nonfinite at update ${result.stopped}; only finite earlier states are shown.` : 'Every shown state is finite.'}</p>
    <NeuralSelect label="Inspect adaptation state" value={Math.min(selected, rows.length - 1)} onChange={v => setSelected(Number(v))} options={rows.map((r, i) => [i, `Update ${r.step}`])} />
    <OptimizerNumberLine title="Observed progress, not the exact target distance" values={[{ label: 'initial parameter', value: s.initial }, { label: 'parameter before step', value: row.before }, { label: 'parameter after step', value: row.after }, { label: 'declared target, only used in objective', value: s.target }]} caption={`The current gradient is ${f(row.gradient, 7)}. Its displacement product g(θ_initial−θ) is ${f(row.gradient * (s.initial - row.before), 7)}. The signed accumulated numerator is ${row.numerator.toExponential(5)} and |s| is ${row.denominator.toExponential(5)}.`} />
    <p>This update uses d={f(row.distance_used, 8)}, including d in m and d² in v. New stored d={f(row.distance_next, 8)} belongs to the next update. Betas .9/.999; ε=1e−8; no decay or bias correction in this paper variant.</p>
    <div className="optimizer-actions"><button onClick={() => setSettings(old => ({ ...old, rate: 1 }))}>Compare γ=1</button><button onClick={() => setSettings(old => ({ ...old, initial: old.target, distance: 1e-6 }))}>Start exactly at target</button><button onClick={() => { setSettings({ initial: 1, target: -2, distance: .01, rate: .3, steps: 12 }); setSelected(2); }}>Reset Prodigy</button></div>
  </NeuralLab>;
}
export function ScheduleFreeLab({ worked = false }) {
  const [settings, setSettings] = useState({ initial: -1, target: 1, rate: .2, beta: .9, noise: [-.5, .5, 1, -1] }), [selected, setSelected] = useState(2);
  const s = worked ? { initial: 2, target: 0, rate: .2, beta: .9, noise: [1, -1, .5, -.5] } : settings;
  const rows = scheduleFreeTrace(s.initial, s.target, s.noise, s.beta, s.rate), row = rows[Math.min(selected, rows.length - 1)];
  const display = <><OptimizerNumberLine title={`Update ${row.step}: gradient here, fast update there`} values={[{ label: 'x before: evaluation average', value: row.oldAverage }, { label: 'z before: fast point', value: row.oldFast }, { label: 'y = βx + (1−β)z: gradient location', value: row.training }, { label: 'z after gradient update', value: row.fast }, { label: 'x after averaging', value: row.average }]} arrows={[{ from: row.oldAverage, to: row.training }, { from: row.oldFast, to: row.fast }, { from: row.oldAverage, to: row.average }]} caption={`Gradient at y is ${f(row.gradient, 7)}, including the declared perturbation. It updates z, then coefficient 1/${row.step} averages the new z into x. The reported evaluation loss is at x: ${f(row.loss, 7)}.`} /><NeuralTable caption="Calculated SGD variant, post-update averaging" headers={['Step', 'y used', 'Gradient', 'New z', 'New x', 'Next y', 'Loss at x']} rows={rows.map(r => [r.step, ...['training', 'gradient', 'fast', 'average', 'nextTraining', 'loss'].map(key => f(r[key], 7))])} /></>;
  if (worked) return <figure className="optimizer-figure"><figcaption>Worked x/y/z calculation</figcaption>{display}</figure>;
  return <NeuralLab id="optimizer-schedule-free" title="Which parameter point are you measuring?">
    <div className="optimizer-controls">{[['initial', 'Initial x=z', -5, 5], ['target', 'Bowl target', -5, 5], ['rate', 'Rate η', 0, .4], ['beta', 'Interpolation β', 0, 1]].map(([key, label, min, max]) => <NeuralNumber key={key} label={label} value={s[key]} min={min} max={max} range={false} onChange={v => setSettings(old => ({ ...old, [key]: v }))} />)}</div><SequenceEditor label="Gradient perturbations" values={s.noise} min={-2} max={2} onChange={noise => setSettings(old => ({ ...old, noise }))} />
    <NeuralSelect label="Inspect Schedule-Free update" value={Math.min(selected, rows.length - 1)} onChange={v => setSelected(Number(v))} options={rows.map((r, i) => [i, `Update ${r.step}`])} />{display}
    <NeuralTable caption="Same objective and perturbations, different interpolation" headers={['β', 'Final x', 'Loss at x']} rows={[0, .9, 1].map(beta => { const r = scheduleFreeTrace(s.initial, s.target, s.noise, beta, s.rate).at(-1); return [beta, f(r.average, 7), f(r.loss, 7)]; })} />
    <p>Endpoint β=0 or 1 is valid for this directly stored mathematical SGD recurrence. The compact package's mode reconstruction is a different implementation boundary. Perturbations are declared arithmetic inputs, not a measured noise process.</p>
    <div className="optimizer-actions"><button onClick={() => setSettings(old => ({ ...old, initial: old.target, noise: old.noise.map(() => 0) }))}>Stationary zero-noise null</button><button onClick={() => { setSettings({ initial: -1, target: 1, rate: .2, beta: .9, noise: [-.5, .5, 1, -1] }); setSelected(2); }}>Reset averaging</button></div>
  </NeuralLab>;
}
export function OptimizerMemoryLab() {
  const [billions, setBillions] = useState(70), [buffers, setBuffers] = useState(2), [bytes, setBytes] = useState(4), [ranks, setRanks] = useState(8), [shard, setShard] = useState('moments');
  const [rows, setRows] = useState(4096), [columns, setColumns] = useState(4096);
  const allocations = [['Model weights', billions * 1e9 * 2, shard === 'all'], ['Gradients', billions * 1e9 * 4, shard === 'all'], ['Optimizer buffers', billions * 1e9 * buffers * bytes, shard !== 'none']].map(([name, total, sharded]) => ({ name, total, sharded, local: total / (sharded ? ranks : 1) }));
  const total = allocations.reduce((s, r) => s + r.local, 0);
  return <NeuralLab id="optimizer-memory" title="Count owned arrays, then apply the actual sharding rule">
    <p>Hypothetical tensor payload, not a measured peak. Weights are BF16 (2 bytes), gradients FP32 (4 bytes). You choose the optimizer-buffer count/dtype and which listed arrays are evenly sharded.</p>
    <div className="optimizer-controls"><NeuralNumber label="Billions of parameters" value={billions} min={.001} max={1000} range={false} onChange={setBillions} /><NeuralSelect label="Additional parameter-sized buffers" value={buffers} onChange={v => setBuffers(Number(v))} options={[[1, '1: Lion'], [2, '2: AdamW / Sophia / efficient base Schedule-Free'], [3, '3: readable Schedule-Free'], [4, '4: paper Prodigy']]} /><NeuralSelect label="Bytes per buffer entry" value={bytes} onChange={v => setBytes(Number(v))} options={[[2, '2 bytes'], [4, '4 bytes'], [8, '8 bytes: classroom NumPy']]} /><NeuralNumber label="Sharding ranks" value={ranks} min={1} max={128} integer step={1} range={false} onChange={setRanks} /><NeuralSelect label="Arrays evenly sharded" value={shard} onChange={setShard} options={[['none', 'None: all replicated'], ['moments', 'Optimizer buffers only'], ['all', 'All three listed allocations']]} /></div>
    <OptimizerFigure title="Per-rank listed payload: each segment retains its owner" width={650} height={190} description="The bar partitions the calculated sum of these three named local allocations. Sharding changes only the selected terms. Activation, workspace and possible master-weight storage are not included because this input does not specify them.">{() => <>{allocations.map((r, i) => { const start = allocations.slice(0, i).reduce((s, v) => s + v.local, 0) / total; return <g key={r.name}><rect x={20 + 610 * start} y="30" width={610 * r.local / total} height="45" fill={['#e4b65a', '#9ebde4', '#b7a1d4'][i]} /><text x="20" y={108 + i * 27}>{r.name}: {f(r.local / 1e9, 3)} GB, {r.sharded ? `global payload ÷ ${ranks}` : 'replicated in full'}</text></g>; })}</>}</OptimizerFigure>
    <NeuralTable caption="Global and local payload" headers={['Array', 'Global GB', 'Per-rank GB', 'Per-rank GiB']} rows={allocations.map(r => [r.name, f(r.total / 1e9, 3), f(r.local / 1e9, 3), f(r.local / 2 ** 30, 3)])} />
    <h4>Factoring depends on matrix shape</h4><div className="optimizer-controls"><NeuralNumber label="Matrix rows n" value={rows} min={1} max={16384} integer range={false} onChange={setRows} /><NeuralNumber label="Matrix columns m" value={columns} min={1} max={16384} integer range={false} onChange={setColumns} /></div><p>Dense FP32 second moment: 4nm = {(4 * rows * columns).toLocaleString()} bytes. Two factors: 4(n+m) = {(4 * (rows + columns)).toLocaleString()} bytes. This counts the factor arrays, not all Adafactor state or an assumed quality loss.</p>
    <button onClick={() => { setBillions(70); setBuffers(2); setBytes(4); setRanks(8); setShard('moments'); setRows(4096); setColumns(4096); }}>Reset allocation ledger</button>
  </NeuralLab>;
}
