import {useState} from 'react';
import {NeuralTable,NeuralSelect,NeuralPlot,formatNeural as f} from './NeuralLessonElements.jsx';
import {crossRead,shapeContract} from '../../data/cross-attention-models.js';
import examples from '../../data/cross-attention-examples.json';
import './cross-attention.css';
export const vector=xs=>`[${xs.map(x=>f(x,5)).join(', ')}]`;
export function CrossDiagram({title,height=250,children,width=440}){return <figure className="cross-diagram"><figcaption>{title}</figcaption><div role="region" tabIndex={0} aria-label={`${title}; scroll horizontally if needed`}><svg style={{minWidth:width}} viewBox={`0 0 ${width} ${height}`} role="img" aria-label={title}>{children}</svg></div></figure>;}
export function CrossBox({x,y,w=105,text}){return <g><rect x={x} y={y} width={w} height={34} rx={3} fill="#24262a" stroke="#8a8e97"/><text x={x+w/2} y={y+22} textAnchor="middle">{text}</text></g>;}
export function CrossBars({title,values,labels=values.map((_,i)=>String(i)),signed=false,limit}){const bound=limit??Math.max(...values.map(Math.abs),1e-12);return <figure><figcaption>{title} · {signed?`−${f(bound)} to ${f(bound)}`:`0 to ${f(bound)}`}</figcaption>{values.map((v,i)=><div className="cross-bar" key={i}><span>{labels[i]}</span><div className={signed?'signed':''}><i style={{left:`${signed?(v<0?50+50*v/bound:50):0}%`,width:`${Math.abs(v)/bound*(signed?50:100)}%`}}/></div><output>{f(v)}</output></div>)}</figure>;}
export function CrossMatrix({title,values,rowLabels,columnLabels,binary=false}){return <NeuralTable caption={title} headers={['Reader / donor',...(columnLabels??values[0].map((_,i)=>i))]} rows={values.map((row,i)=>[rowLabels?.[i]??i,...row.map(value=>binary?<span className={value?'cross-allowed':'cross-forbidden'}>{value?'allowed':'×'}</span>:f(value))])}/>;}
export function CrossPixels({pixels,title,patch=null}){return <figure className="cross-pixels"><figcaption>{title}</figcaption><div className="cross-pixel-grid">{pixels.map((v,i)=>{const selected=patch!==null&&Math.floor(Math.floor(i/8)/2)*4+Math.floor(i%8/2)===patch;return <span key={i} className={selected?'selected':''} style={{background:`rgb(${15+Math.round(v/16*230)} ${15+Math.round(v/16*230)} ${15+Math.round(v/16*230)})`,color:v>8?'#111':'#eee'}}>{v}</span>;})}</div></figure>;}
export function ReadContributions({query,keyRows,values,result,reader=0}){const row=result.weights[reader];return <>{row?<><CrossDiagram title={`Reader ${reader}: ${values.length} memory slots return one vector`} height={95+48*values.length}><CrossBox x={4} y={25+24*values.length} w={76} text={`reader ${reader}`}/>{values.map((v,i)=>{const y=20+i*48,active=row[i]>0;return <g key={i}><path d={`M80 ${42+24*values.length} L147 ${y+16} M255 ${y+16} L352 ${42+24*values.length}`} stroke={active?'#e4b752':'#656b76'} strokeWidth={active?1+3*row[i]:1} strokeDasharray={active?undefined:'4 4'} fill="none"/><CrossBox x={147} y={y} w={108} text={`slot ${i}: ${f(row[i],3)}`}/><text x={149} y={y+46}>{vector(v)}</text></g>;})}<CrossBox x={352} y={25+24*values.length} w={82} text="Σ values"/><text x={7} y={80+48*values.length}>Returned {vector(result.output[reader])}; dashed = unavailable</text></CrossDiagram><div className="cross-pair">{[0,1].map(c=><CrossBars key={c} title={`Products for output coordinate ${c}`} values={result.products[reader].map(v=>v[c])} labels={values.map((_,i)=>`slot ${i}`)} signed/>)}</div><NeuralTable caption={`Every operation for reader ${reader}`} headers={['Memory slot','Query · key / √d','Weight','Value','Weighted contribution']} rows={values.map((v,i)=>[i,f(result.scores[reader][i]),f(row[i]),vector(v),vector(result.products[reader][i])])}/></>:<p role="status">Reader {reader} has no available memory entry. A normalized read is undefined; its output is deliberately absent. Enable at least one slot.</p>}<NeuralTable caption="One result per query, even though memory length differs" headers={['Reader','Query','Output']} rows={query.map((q,i)=>[i,vector(q),result.output[i]?vector(result.output[i]):'undefined: no allowed memory'])}/></>;}
export function ShapeTiles({settings}){const s=shapeContract(settings),{readers:t,memory:m,heads:h,keyWidth:k,valueWidth:v,readerWidth:d,memoryWidth:dm}=settings;return <><CrossDiagram title="Projected keys match query width; value width determines the returned vector" height={260}><CrossBox x={4} y={20} w={100} text={`X: ${t} × ${d}`}/><CrossBox x={4} y={105} w={100} text={`M: ${m} × ${dm}`}/><path d="M104 37 L148 37 M104 122 L148 100 M104 122 L148 161 M246 37 L280 78 M246 100 L280 95 M310 110 L310 160 M246 177 L280 177 M335 177 L378 177" fill="none" stroke="#e4b752"/><CrossBox x={148} y={20} w={97} text={`Q: ${t} × ${k}`}/><CrossBox x={148} y={83} w={97} text={`K: ${m} × ${k}`}/><CrossBox x={148} y={160} w={97} text={`V: ${m} × ${v}`}/><rect x={280} y={65} width={Math.max(28,m*4)} height={Math.max(24,t*4)} fill="#4f4227" stroke="#e4b752"/><text x={278} y={58}>{t} × {m} weights</text><CrossBox x={278} y={160} w={70} text={`${t} × ${v}`}/><text x={355} y={209}>{h} heads</text><text x={8} y={245}>Concat {t} × {h*v} → project {h*v} to {d} → residual {t} × {d}</text></CrossDiagram><NeuralTable caption="Exact dimensions, including required projections" headers={['Object','Shape']} rows={Object.entries(s).map(([name,shape])=>[name,shape.join(' × ')])}/></>;}
export function TeacherForcingFigure(){const[sentence,setSentence]=useState('red bicycle'),[selected,setSelected]=useState(0),[questionLoss,setQuestionLoss]=useState(false);const words=sentence.split(' ');return <figure><figcaption>Supervised targets sit one step after their predictor's input</figcaption><NeuralSelect label="Example answer" value={sentence} onChange={setSentence} options={[['red bicycle','red bicycle'],['three birds','three birds']]}/><NeuralSelect label="Supervised answer position to inspect" value={selected} onChange={v=>setSelected(+v)} options={[[0,'First word'],[1,'Second word']]}/><CrossDiagram title="Separate attention context from the loss mask" height={220}><CrossBox x={3} y={20} w={115} text="image + question"/><CrossBox x={148} y={20} w={115} text="answer start"/><CrossBox x={294} y={20} w={135} text={`input: ${words[0]}`}/><path d="M118 37 L148 37 M263 37 L294 37 M205 54 L205 119 M361 54 L361 119" fill="none" stroke="#e4b752"/><CrossBox x={148} y={125} w={115} text={`target: ${words[0]}`}/><CrossBox x={294} y={125} w={135} text={`target: ${words[1]}`}/><text x={5} y={100}>loss: {questionLoss?'question also supervised':'question ignored'}</text><text x={175} y={181}>answer loss on</text><text x={8} y={210}>The first target word is absent from its own predictor input.</text></CrossDiagram><label><input type="checkbox" checked={questionLoss} onChange={e=>setQuestionLoss(e.target.checked)}/> Also supervise question targets (changes the objective)</label><p>To predict <strong>{words[selected]}</strong>, the reader can use image, question, answer-start{selected===1?` and ${words[0]}`:''}. The attention context is unchanged when question loss is toggled; question tokens remain available. No future answer word is admitted.</p></figure>;}
export function CrossFigure({kind}){
 const e=examples.exact;
 if(kind==='pairs'){const stream=['V0','V1','T0','T1','T2'],text=['T0','T1','T2'];return <><div className="cross-pair"><CrossMatrix title="Causal shared stream: 15 permitted pairs" rowLabels={stream} columnLabels={stream} binary values={stream.map((_,r)=>stream.map((_,c)=>c<=r))}/><CrossMatrix title="Separate text self-read plus visual read: 6 + 6 pairs" rowLabels={text} columnLabels={stream} binary values={text.map((_,r)=>stream.map((_,c)=>c<2||c-2<=r))}/></div><p>This small exact illustration uses two visual tokens and three text tokens. The shared stream also updates the visual rows; separate reads return only three text rows. Ignoring causality would count 25 and 15 candidate pairs respectively. The calculator below changes the actual counts without drawing millions of cells.</p></>;}
 if(kind==='read')return <ReadContributions query={e.query} keyRows={e.key} values={e.value} result={crossRead(e.query,e.key,e.value)}/>;
 if(kind==='shapes')return <ShapeTiles settings={{readers:2,memory:5,heads:3,keyWidth:2,valueWidth:2,readerWidth:6,memoryWidth:8}}/>;
 if(kind==='teacher')return <TeacherForcingFigure/>;
 if(kind==='resampler')return <CrossDiagram title="Learned latent readers compress before later text readers fuse information" height={255}>{Array.from({length:8},(_,i)=><rect key={i} x={6+i*18} y={15} width={13} height={26} fill="#888e99"/>)}<text x={5} y={60}>S image features</text>{Array.from({length:8},(_,source)=>[0,1,2,3].map(i=><path key={`${source}-${i}`} d={`M${12+source*18} 42 L${57+i*107} 120`} stroke="#5d626c" strokeWidth={.7}/>))}{[0,1,2,3].map(i=><g key={i}><CrossBox x={7+i*107} y={120} w={100} text={`latent ${i}`}/></g>)}<CrossBox x={152} y={195} w={130} text="later text query"/>{[0,1,2,3].map(i=><path key={i} d={`M217 195 L${57+i*107} 154`} stroke="#e4b752" fill="none"/>)}<text x={8} y={244}>Latent numbers are learned slots, not image quadrants.</text></CrossDiagram>;
 if(kind==='frozen')return <CrossDiagram title="Frozen weights and a severed derivative are different computation graphs" height={310}>{[false,true].map((cut,i)=><g key={String(cut)}><text x={8} y={18+i*148}>{cut?'Same backbone under no_grad: derivative route is cut':'Frozen parameter, tracked operations: input derivative continues'}</text><CrossBox x={5} y={32+i*148} w={116} text="trainable adapter"/><CrossBox x={163} y={32+i*148} w={125} text={cut?'no_grad backbone':'frozen backbone'}/><CrossBox x={340} y={32+i*148} w={90} text="loss"/><path d={`M121 ${49+i*148} L163 ${49+i*148} M288 ${49+i*148} L340 ${49+i*148}`} fill="none" stroke="#e4b752" strokeWidth={2}/>{cut?<><path d="M385 215 L385 242 L309 242" fill="none" stroke="#83b4e8" strokeDasharray="5 4"/><path d="M301 232 L316 251 M316 232 L301 251" stroke="#e89b87" strokeWidth={2}/><text x={7} y={284}>No loss derivative reaches the adapter through this route.</text></>:<><path d="M385 66 L385 91 L226 91 L226 122 L66 122 L66 66" fill="none" stroke="#83b4e8" strokeWidth={2}/><text x={162} y={142}>Weights fixed; input derivative retained.</text></>}</g>)}</CrossDiagram>;
 if(kind==='named')return <>{[['Flamingo, 2022','image encoder','64 resampled slots','gated cross reads','frozen LM','Vision + LM frozen; resampler and inserted blocks train.'],['BLIP-2, 2023','frozen vision','32 Q-Former queries','project query outputs','frozen LM','Stage 2: query module/projector connect the frozen backbones.'],['LLaVA, 2023','frozen CLIP','linear projection','image/text prefix','language model','Alignment: projection trains. Instruction stage: projection + LM.'],['Idefics2, 2024','vision features','projection + pooling','64-token prefix','shared LM stream','Pooling changes token count; it does not create separate visual reads.']].map(([name,a,b,c,d,note])=><div key={name}><CrossDiagram title={name} height={135}><CrossBox x={5} y={16} w={130} text={a}/><CrossBox x={170} y={16} w={170} text={b}/><path d="M135 33 L170 33 M340 33 L417 33 L417 100 L340 100 M170 100 L137 100" fill="none" stroke="#e4b752"/><CrossBox x={170} y={83} w={170} text={c}/><CrossBox x={5} y={83} w={132} text={d}/></CrossDiagram><p>{note}</p></div>)}</>;
 if(kind==='blip'){const names=['Q0','Q1','T0','T1'];return <><div className="cross-pair">{['contrastive','matching','generation'].map(mode=><CrossMatrix key={mode} title={`Q-Former shared self-attention: ${mode}`} rowLabels={names} columnLabels={names} binary values={names.map((_,r)=>names.map((_,c)=>mode==='matching'||mode==='contrastive'?(mode==='matching'||(r<2)===(c<2)):r<2?c<2:c<2||c<=r))}/>)}</div><p>Rows receive from columns. Generation text can read queries and earlier/current shifted text; queries never read text. Only the query stream's separate cross-attention reads frozen visual features. Loss targets remain shifted as shown above.</p></>;}
 if(kind==='pipeline')return <CrossDiagram title="Actual question-conditioned digit model, with all tensor widths" height={240}><CrossBox x={4} y={20} w={112} text="8 × 8 counts"/><CrossBox x={153} y={20} w={128} text="16 × 4 patches"/><CrossBox x={312} y={20} w={124} text="16 × 24 memory"/><path d="M116 37 L153 37 M281 37 L312 37 M374 54 L374 113 L276 113 M124 113 L150 113 M215 132 L215 177" stroke="#e4b752" fill="none"/><CrossBox x={4} y={96} w={120} text="question: 1 × 24"/><CrossBox x={150} y={96} w={126} text="3 heads, 1 × 16"/><CrossBox x={133} y={181} w={166} text="residual / FFN / 12 logits"/><text x={8} y={233}>Flat baseline instead maps 64 pixels + 24 query → 48 → 12.</text></CrossDiagram>;
 if(kind==='results')return <><div className="cross-chart-scroll" role="region" tabIndex={0} aria-label="Recorded outcomes; scroll horizontally if needed"><NeuralPlot title="Nine fixed fits: original versus shuffled image pairs" xLabel="run index (no connecting line)" yLabel="correct / 160 questions" xDomain={[0,8]} yDomain={[0,1]} series={[]} points={examples.summary.flatMap((r,i)=>[{x:i,y:r.assessment.correct/160,color:'#e4b752',label:`${r.mode}, seed ${r.seed}: ${r.assessment.correct}/160`},{x:i,y:r.mismatched_image_correct/160,color:'#83b4e8',label:`Shuffled: ${r.mismatched_image_correct}/160`}])}/></div><p>Amber: original image/question pairing. Blue: seeded image shuffle. Question-only baseline: 48/160. Seeds are separate fits, not sequential epochs.</p><NeuralTable caption="All recorded architecture outcomes" headers={['Index: model / seed','Parameters','Digit / 80','Parity / 80','Original / 160','Cyclic / 160','Shuffle / 160']} rows={examples.summary.map((r,i)=>[`${i}: ${r.mode} / ${r.seed}`,r.parameters,r.assessment.digit_correct,r.assessment.parity_correct,r.assessment.correct,r.cyclic_image_correct,r.mismatched_image_correct])}/></>;
 if(kind==='dependency')return <CrossDiagram title="Memory sharing preserves the memory dependency, not a shared answer" height={240}>{[0,1,2,3].map(i=><g key={i}><CrossBox x={5+i*108} y={15} w={99} text={`encoder x${i}`}/><path d={`M${55+i*108} 49 L${55+i*108} 97`} stroke="#e4b752"/><CrossBox x={5+i*108} y={100} w={99} text={`memory m${i}`}/>{i<3&&<path d={`M${105+i*108} 31 L${113+i*108} 31`} stroke="#aaa"/>}</g>)}<text x={8} y={162}>Causal encoder: m2 may depend on x0,x1,x2, never x3.</text><text x={8} y={188}>Bidirectional encoder: m2 may already contain x3.</text><text x={8} y={214}>Each decoder layer still supplies its own query and output.</text></CrossDiagram>;
 return null;
}
