import { Code, H3, Prose } from '../content';
import MechanismProgram from './MechanismProgram.jsx';
import output from '../../data/external-memory-library-output.json';

export function StreamingSortImplementation() {
  return <section id="streaming-sort-implementation" data-implementation-depth="external-sort-stream">
    <H3>Keep the sorted result on disk</H3>
    <Prose>The pass-count program deliberately materializes every modeled pass and loads a tiny final result for inspection. For a larger actual file, keep the same sorted-run invariant but change its interface: a source file becomes a new destination file. This implementation sorts each chunk in place, merges at most fan_in runs together, closes every stream before deleting consumed runs, carries an unchanged singleton run forward, and copies the final result in bounded blocks.</Prose>
    <MechanismProgram source="/learn-assets/external-memory-algorithms-b-trees-i-o-complexity/external_sort_stream.py" title="Read the complete bounded-file sorter" output={output['external_sort_stream.py']} />
    <Prose>Run <Code>python external_sort_stream.py</Code> with Python 3.12+; its demonstration uses disposable temporary files. The reusable function accepts signed 64-bit binary records, a chunk record count, a merge fan-in and an I/O buffer record count. Live record storage is O(chunk_records + fan_in·buffer_records), plus Python object overhead and O(number of runs) pathname metadata. A merge opens at most fan_in input files plus one output. Heap merging costs O(log fan_in) per emitted record, while total sort work is O(N log N); each merge level transfers its participating records. File buffers and OS caching mean these are not measured physical disk operations.</Prose>
    <Prose>The destination must be new, and a failed final copy can leave a partial new output; successful completion is not a power-loss durability claim. The sorter rejects truncated records and protects an existing destination. It handles empty input and partial runs. <a href="https://docs.python.org/3/library/heapq.html#heapq.merge" target="_blank" rel="noopener noreferrer">heapq.merge</a> supplies the already-taught ordered frontier lazily, and <a href="https://docs.python.org/3/library/contextlib.html#contextlib.ExitStack" target="_blank" rel="noopener noreferrer">ExitStack</a> closes the bounded resource group even when processing raises. A byte budget must include interpreter, buffers, heap and metadata, not just count payload integers.</Prose>
  </section>;
}

export default function ExternalMemoryLibraryBridge() {
  return <section id="external-memory-library-bridge" data-implementation-depth="external-memory">
    <H3>Use the database index through its query contract</H3>
    <Prose>A practical application normally asks a database for an indexed interval instead of implementing B-tree page repairs itself. Reuse the <a href="/learn/topic/sql-relational-data-transactions-for-ml">SQL lesson's parameter binding and transaction discipline</a>. This program builds a disposable SQLite file, creates a unique index on reading, queries an inclusive interval, deletes one record and reopens the committed database. Its BTree comparison comes from the exact split/borrow/merge implementation earlier in this lesson.</Prose>
    <Prose>Save <a href="/learn-assets/external-memory-algorithms-b-trees-i-o-complexity/external_memory_mechanisms.py" download>external_memory_mechanisms.py</a> beside the program and run <Code>python sqlite_index_library.py</Code>. Python 3.12+'s standard sqlite3 module is sufficient. The unique constraint and INSERT OR IGNORE match our set's duplicate policy. Parameters bind values; ORDER BY specifies order rather than relying on an incidental scan. This bridge explicitly selects <Code>autocommit=False</Code>: the connection context commits or rolls back, and finally explicitly closes the connection. The earlier SQL program instead demonstrates explicit BEGIN/COMMIT statements; do not mix the two transaction-control styles.</Prose>
    <MechanismProgram source="/learn-assets/external-memory-algorithms-b-trees-i-o-complexity/sqlite_index_library.py" title="Compare an indexed SQL interval with the B-tree set" output={output['sqlite_index_library.py']} />
    <Prose>The interval [7,20] returns [7,10,12,17,20]. This environment's EXPLAIN QUERY PLAN names reading_order; the exact plan text is diagnostic, not a stable application API. An exception rolls back the inserted 99, and reopening observes seven committed rows. These tests exercise normal commit/rollback behavior, not power-loss recovery. The Python page model's visits cannot be read as SQLite page transfers: its cache, layout, optimizer, journaling and file system add their own mechanisms. Consult <a href="https://www.sqlite.org/queryplanner.html" target="_blank" rel="noopener noreferrer">SQLite's index/query explanation</a> and <a href="https://www.sqlite.org/eqp.html" target="_blank" rel="noopener noreferrer">query-plan diagnostics</a>.</Prose>
    <H3>Transfer: repeated measurements and a small merge budget</H3>
    <Prose>Change the database to retain repeated readings with distinct record IDs, insert two extra readings equal to 10, and return (reading,id) ordered by both fields. Separately sort the same readings with chunk_records=3 and fan_in=2 without removing duplicates. Verify the input multiset and keep the output file on disk.</Prose>
    <details><summary>Optional hint</summary><Prose>The set's duplicate suppression now violates the task. Use a nonunique composite index for the database and a Counter oracle for the file; order and multiplicity are separate checks.</Prose></details>
    <details><summary>Solution and reasoning</summary><Prose>Create a nonunique index on (reading,id), retain the primary-key ID, and use ORDER BY reading,id. Reading 10 must appear three times after the two inserts. The integer sorter already preserves repeated values; compare Counter(output) with Counter(input) and check adjacent output values are nondecreasing. Stream those checks for large outputs, retaining only the current previous value plus the chosen verification state. A Counter of all distinct values itself uses memory, so a full multiset oracle is appropriate only for bounded tests. Test more initial runs than the fan-in, an empty input, a short final chunk and the documented existing-destination rejection.</Prose></details>
  </section>;
}
