import { Code, H3, Prose } from '../content';
import MechanismProgram from './MechanismProgram.jsx';
import output from '../../data/network-flow-library-output.json';

export default function FlowLibraryBridge() {
  return <section id="flow-library-bridge" data-implementation-depth="network-flow">
    <H3>Compare certificates, not one favored flow</H3>
    <Prose>Use the <a href="/learn/topic/graphs-representations-bfs-dfs#graph-library-bridge">earlier declared-vertex graph construction</a>, but make capacity explicit on every edge. NetworkX's maximum-flow API does not accept MultiDiGraph. For this capacity-only task, the bridge sums parallel capacities into a DiGraph edge and leaves antiparallel directions distinct. It omits self-loops, which do not increase source–sink throughput. The local residual implementation continues to preserve each original edge's identity.</Prose>
    <Prose>Install NetworkX 3.6.1, save <a href="/learn-assets/network-flow-minimum-cuts-bipartite-matching/network_flow_mechanisms.py" download>network_flow_mechanisms.py</a> beside the comparison, and run <Code>python flow_library.py</Code>. The download reuses the complete Edmonds–Karp and matching mechanisms already explained. <Code>flow_func=edmonds_karp</Code> fixes the library algorithm rather than depending on a changeable default. Missing capacities would mean a different network, so the builder never omits them.</Prose>
    <MechanismProgram source="/learn-assets/network-flow-minimum-cuts-bipartite-matching/flow_library.py" title="Compare complete flow, cut and matching certificates" output={output['flow_library.py']} />
    <Prose>The first network sends 6 units; reducing edge 2→3 to capacity 1 lowers the maximum to 4. An isolated sink receives 0. The comparison independently checks every library capacity bound, internal conservation, net source/sink value and the capacity of its returned cut. A feasible flow whose value equals a cut's capacity is certified optimal. Different maximum flows and minimum cuts may satisfy this certificate, so exact per-edge equality is unnecessary. Aggregation loses individual parallel-edge allocation; if the application needs it, distribute the aggregate flow back within those capacities or retain an edge-identified solver.</Prose>
    <Prose>The matching route uses tagged left/right vertex identities and explicitly supplies the left partition. This matters for disconnected graphs, where partition inference is ambiguous. The library matching dictionary stores both directions, so its length is twice the matching size. The returned cover is checked against every compatibility edge and has that same size. Our reduction through flow teaches the mechanism; the <a href="https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.bipartite.matching.hopcroft_karp_matching.html" target="_blank" rel="noopener noreferrer">specialized Hopcroft–Karp API</a> is a practical route for larger bipartite problems. The <a href="https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.flow.maximum_flow.html" target="_blank" rel="noopener noreferrer">flow API reference</a> specifies capacities and residual conventions.</Prose>
    <Prose>Edmonds–Karp's O(VE²) worst-case bound and O(V + E) residual storage remain the local cost model. The earlier Dinic branch provides a different blocking-flow mechanism; specialized matching avoids treating every assignment as an arbitrary capacitated network. This exact comparison uses nonnegative integer capacities. Floating residual tolerances, costs, lower bounds and mandatory demands are separate contracts; preserve the taught reductions instead of silently passing those quantities as ordinary capacities.</Prose>
    <H3>Transfer: change the two exit capacities</H3>
    <Prose>Set capacities 1→3 and 2→3 to 2 each in the original program. Compute a maximum flow with both routes, but write your own certificate checker against the original edge list. Name a cut proving the result and retain the isolated vertex 4.</Prose>
    <details><summary>Optional hint</summary><Prose>All useful flow must cross into vertex 3. Sum capacities of edges from {0,1,2,4} into {3}, then construct that much feasible flow.</Prose></details>
    <details><summary>Solution and reasoning</summary><Prose>The maximum is 4. Send two units along 0→1→3 and two along 0→2→3; distribute the first two across the original parallel 0→1 edges within their individual capacities. The named cut has capacity 2 + 2 = 4. Check all original bounds and vertex balances, including vertex 4's zero balance; capacity aggregation alone is not a certificate for a particular original-edge allocation.</Prose></details>
  </section>;
}
