import { Code, H3, Prose } from '../content';
import MechanismProgram from './MechanismProgram.jsx';
import output from '../../data/computational-geometry-library-output.json';

export default function GeometryLibraryBridge() {
  return <section id="geometry-library-bridge" data-implementation-depth="computational-geometry">
    <H3>Use a floating hull with an explicit coordinate contract</H3>
    <Prose>SciPy's ConvexHull is a practical numerical hull interface backed by Qhull. Our monotone chain remains the exact integer-predicate route. Compare their corner-only answers on the same small, nondegenerate integer fixture, where the input coordinates are exactly representable as binary floats. The program deduplicates coordinates, selects float64 deliberately, and compares corner <em>sets</em> so a cyclic starting vertex is irrelevant.</Prose>
    <Prose>Use Python 3.12+, NumPy 2.3.5 and SciPy 1.18.1. Save <a href="/learn-assets/computational-geometry-robust-predicates-convex-hulls/computational_geometry_mechanisms.py" download style={{ overflowWrap: 'anywhere' }}>computational_geometry_mechanisms.py</a> beside the comparison, then run <Code>python hull_library.py</Code>. The import reuses the earlier orientation/hull implementation and the polygon doubled-area sum. The latter sums each consecutive x·y cross term around the closed boundary, then divides its absolute value by two.</Prose>
    <MechanismProgram source="/learn-assets/computational-geometry-robust-predicates-convex-hulls/hull_library.py" title="Compare hull corners and expose a degenerate input" output={output['hull_library.py']} />
    <Prose>The four corners enclose area 30 and perimeter 22. In SciPy's two-dimensional interface, <Code>volume</Code> means area and <Code>area</Code> means perimeter; read the dimension-dependent meaning before interpreting an output. The local include_boundary option also returns collinear edge records, so it intentionally asks for more than corner parity. The exact all-collinear hull returns the two endpoints, while the default full-dimensional library call raises QhullError. Silently adding jitter would change the input problem.</Prose>
    <Prose>The local algorithm spends O(n log n) comparisons sorting, then O(n) orientation calls and O(n) storage. Arbitrary-precision integer arithmetic has a bit cost; it is not a unit-cost guarantee for unlimited coordinate magnitudes. Converting 2⁵³ and 2⁵³ + 1 to float collapses their distinction before Qhull begins. Thus this successful fixture does not turn the floating library into an oracle for all exact predicates. Use the exact route for that contract and a documented numerical geometry route for the numerical one. SciPy's <a href="https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.ConvexHull.html" target="_blank" rel="noopener noreferrer">ConvexHull reference</a> documents vertex order, measures and degeneracy exceptions.</Prose>
    <H3>Transfer: translate without changing the shape</H3>
    <Prose>Translate every fixture point by (10⁶, −10⁶). Implement an exact area calculation after subtracting one hull vertex as an origin, then compare the library area on these translated coordinates. Next explain why repeating this test near 2⁵³ requires a different conclusion.</Prose>
    <details><summary>Optional hint</summary><Prose>Area depends on differences. For a chosen origin o, sum cross(vᵢ−o, vᵢ₊₁−o); the translation terms cancel exactly.</Prose></details>
    <details><summary>Solution and reasoning</summary><Prose>The exact corner offsets, area 30 and perimeter 22 are unchanged. Subtracting a common integer origin before conversion keeps the small local differences exactly available for the float comparison. Near 2⁵³, converting global coordinates first can merge distinct points; subtracting an origin afterward cannot restore discarded bits. Test both conversion orders and retain integer input until the coordinate-frame change if exact distinctions matter. Compare numerical area with a stated tolerance, not an unexplained exact float equality.</Prose></details>
  </section>;
}
