import {useId} from 'react';
import {NeuralTable,NeuralPlot,formatNeural as f} from './NeuralLessonElements.jsx';
import {adjacency,cycle,structuralRead,geometryContract,rotation,chirality,transformPoints,energyForce,matvec,add} from '../../data/geometric-graph-models.js';
import examples from '../../data/geometric-graph-examples.json';
import './geometric-graph.css';
export const vector=x=>`[${x.map(v=>f(v,6)).join(', ')}]`;
export function GeoDiagram({title,width=480,height=260,children}){const id='geo-'+useId().replaceAll(':','');return <figure className="geo-diagram"><figcaption>{title}</figcaption><div tabIndex={0} role="region" aria-label={`${title}; horizontally scrollable`}><svg viewBox={`0 0 ${width} ${height}`} style={{minWidth:width}} role="img" aria-label={title}><defs><marker id={id} markerWidth="7" markerHeight="7" refX="6" refY="3.5" orient="auto-start-reverse"><path d="M0 0 L7 3.5 L0 7" fill="#b5bdca"/></marker></defs>{typeof children==='function'?children(`url(#${id})`):children}</svg></div></figure>;}
export function GeoBox({x,y,w=120,text}){return <g><rect x={x} y={y} width={w} height={36} rx={3} fill="#282d36" stroke="#8c96a6"/><text x={x+w/2} y={y+23} textAnchor="middle">{text}</text></g>;}
export function GeoMatrix({title,values,labels,columns,selected,heat=false}){return <div className="geo-matrix" tabIndex={0} role="region" aria-label={`${title}; horizontally scrollable`}><table><caption>{title}</caption><thead><tr><th>row ↓ / column →</th>{values[0].map((_,i)=><th key={i}>{columns?.[i]??labels?.[i]??i}</th>)}</tr></thead><tbody>{values.map((r,i)=><tr key={i}><th>{labels?.[i]??i}</th>{r.map((v,j)=><td key={j} className={selected===i?'geo-selected':''} style={heat?{background:v>=0?`rgba(210,162,66,${Math.min(.55,Math.abs(v))})`:`rgba(96,149,207,${Math.min(.55,Math.abs(v))})`}:undefined}>{Number.isFinite(v)?f(v,6):'unreachable'}</td>)}</tr>)}</tbody></table></div>;}
export function GeoGraph({a,values,positions,selected=0,weights,labels,roles,title='Topology and node identities'}){const n=a.length,big=n>8,width=big?560:480,height=big?450:255,points=positions?positions.map(([x,y])=>[40+(x+1)*240,30+(y+1)*190]):n===3?[[65,110],[240,110],[415,110]]:Array.from({length:n},(_,i)=>[240+165*Math.cos(i*2*Math.PI/n-Math.PI/2),123+82*Math.sin(i*2*Math.PI/n-Math.PI/2)]);return <GeoDiagram title={title} width={width} height={height}>{arrow=><>{a.flatMap((r,i)=>r.map((edge,j)=>edge&&j>i?<line key={`${i}-${j}`} x1={points[i][0]} y1={points[i][1]} x2={points[j][0]} y2={points[j][1]} stroke="#646f7e"/>:null))}{weights&&points.map(([x,y],j)=>j!==selected&&weights[j]>0?<line key={j} x1={x} y1={y} x2={points[selected][0]} y2={points[selected][1]} stroke="#e4b752" strokeWidth={1+5*weights[j]} strokeDasharray={a[selected][j]?'':'4 4'} markerEnd={arrow}/>:null)}{points.map(([x,y],i)=><g key={i}><circle cx={x} cy={y} r={big?12:20} fill={i===selected?'#755821':'#252b34'} stroke={roles?.[i]==='fit'?'#e4b752':roles?.[i]==='development'?'#bda4da':'#8fb9e8'} strokeWidth={i===selected?3:1.5}/><text x={x} y={y+4} textAnchor="middle">{labels?.[i]??i}</text>{values&&!big&&<text x={x} y={y+40} textAnchor="middle">v={f(values[i])}</text>}</g>)}</>}</GeoDiagram>;}
export function GeoBars({title,values,labels,bound=1}){return <figure><figcaption>{title}; common signed scale ±{f(bound,8)}</figcaption>{values.map((v,i)=><div className="geo-bar" key={i}><span>{labels?.[i]??i}</span><div><i style={{left:`${v<0?50+v/bound*50:50}%`,width:`${Math.abs(v)/bound*50}%`}}/></div><output>{Math.abs(v)>0&&Math.abs(v)<.0001?v.toExponential(5):f(v,7)}</output></div>)}</figure>;}
export function PointArrows({title,points,vectors,after,scale=1,domainPoints}){const projection=p=>[p[0]+.35*p[2],p[1]+.22*p[2]],all=[...(domainPoints??[]),...points,...points.map((p,i)=>vectors?add(p,vectors[i].map(v=>v*scale)):p),...(after??[])].map(projection),xs=all.map(p=>p[0]),ys=all.map(p=>p[1]),lo=[Math.min(...xs)-.3,Math.min(...ys)-.3],hi=[Math.max(...xs)+.3,Math.max(...ys)+.3],unit=Math.min(370/(hi[0]-lo[0]),190/(hi[1]-lo[1])),map=p=>{const q=projection(p);return[50+(q[0]-lo[0])*unit,225-(q[1]-lo[1])*unit];};return <GeoDiagram title={title} height={280}>{arrow=><>{points.map((p,i)=>{const[x,y]=map(p),end=map(vectors?add(p,vectors[i].map(v=>v*scale)):after?.[i]??p);return <g key={i}><circle cx={x} cy={y} r={5} fill="#8fb9e8"/><text x={end[0]+9} y={end[1]-8-i*2}>{i}</text><line x1={x} y1={y} x2={end[0]} y2={end[1]} stroke="#e4b752" strokeWidth={2} markerEnd={arrow}/><circle cx={end[0]} cy={end[1]} r={3} fill="#e4b752"/></g>})}<text x={12} y={265}>Oblique projection (x + .35z, y + .22z); exact 3D values below.</text></>}</GeoDiagram>;}
export function SquareRoutes({result,input}){const rows=[['input',input],['filter then action',result.after],['action then filter',result.before]];return <GeoDiagram title="Follow the same named sensor values through both routes" height={290}>{arrow=><>{rows.map(([name,values],r)=><g key={name}><text x={10} y={25+r*92}>{name}</text>{values.map((v,i)=><g key={i}><rect x={180+i*72} y={6+r*92} width={58} height={38} fill="#303743" stroke="#93a6be"/><text x={209+i*72} y={30+r*92} textAnchor="middle">{f(v)}</text></g>)}</g>)}<path d="M140 43 L140 103 M150 43 L150 195" stroke="#c0a16b" fill="none" markerEnd={arrow}/><text x={183} y={276}>Output slot: 0                 1                 2                 3</text></>}</GeoDiagram>;}
export function GeometricFigure({kind}){
 if(kind==='routes')return <GeoDiagram title="Three distinct ways graph structure can reach a node state" height={305}>{arrow=><>{[['degree / return feature','input embedding'],['pair distance / path','attention score bias'],['observed local edge','local message sum']].map(([a,b],i)=><g key={a}><GeoBox x={8} y={22+92*i} w={163} text={a}/><GeoBox x={220} y={22+92*i} w={181} text={b}/><path d={`M171 ${40+92*i} L220 ${40+92*i} M401 ${40+92*i} L453 ${40+92*i}`} stroke="#e4b752" markerEnd={arrow}/></g>)}<path d="M454 39 L454 224" stroke="#b3bac6"/><text x={240} y={292} textAnchor="middle">Each route changes the received state.</text></>}</GeoDiagram>;
 if(kind==='gps')return <GeoDiagram title="GPS with normalization and dropout disabled: two residual copies of x" height={350}>{arrow=><><GeoBox x={5} y={129} w={65} text="x"/><GeoBox x={138} y={24} w={153} text="local GCN(x)"/><GeoBox x={138} y={226} w={153} text="global attention(x)"/><GeoBox x={353} y={129} w={115} text="h = 2x + L + G"/><path d="M70 147 L100 147 L100 42 L138 42 M100 147 L100 244 L138 244 M291 42 L410 42 L410 129 M291 244 L410 244 L410 165" fill="none" stroke="#e4b752" markerEnd={arrow}/><path d="M70 140 L350 140 M70 155 L350 155" fill="none" stroke="#8fb9e8" strokeDasharray="5 4" markerEnd={arrow}/><text x={193} y={126}>x bypass</text><text x={193} y={178}>x bypass</text><GeoBox x={174} y={298} w={130} text="y = h + MLP(h)"/><path d="M455 165 L455 316 L304 316" fill="none" stroke="#b8a3d4" markerEnd={arrow}/></>}</GeoDiagram>;
 if(kind==='walks')return <><div className="geo-pair"><GeoGraph title="Six-cycle: odd three-step return is impossible" a={cycle(6)}/><GeoGraph title="Two triangles: two returning routes per start" a={adjacency(6,[[0,1],[1,2],[2,0],[3,4],[4,5],[5,3]])}/></div><GeoDiagram title="Two distinct three-step returns to node 0; each route has probability 1/8" height={190}>{arrow=><>{[[0,1,2,0],[0,2,1,0]].map((row,r)=><g key={r}>{row.map((v,i)=><g key={i}><circle cx={52+i*116} cy={45+r*94} r={18} fill="#303743" stroke="#9aa8b9"/><text x={52+i*116} y={49+r*94} textAnchor="middle">{v}</text>{i<3&&<><path d={`M${70+i*116} ${45+r*94} L${149+i*116} ${45+r*94}`} markerEnd={arrow} stroke="#e4b752"/><text x={98+i*116} y={32+r*94}>1/2</text></>}</g>)}</g>)}</>}</GeoDiagram></>;
 if(kind==='access'){const a=structuralRead({values:[7,7,7]}),b=structuralRead({values:[7,7,7],local:true});return <><GeoBars title="Global contributions sum to 7" values={a.products} bound={7}/><GeoBars title="One-hop contributions also sum to 7" values={b.products} bound={7}/><GeoDiagram title="Access, retained information, learned use and prediction are separate questions" height={140} width={540}>{arrow=><>{['allowed route','mixed state','learned use','held-out answer'].map((text,i)=><g key={text}><GeoBox x={4+i*135} y={35} w={120} text={text}/>{i<3&&<path d={`M${124+i*135} 53 L${139+i*135} 53`} stroke="#9ea9b8" markerEnd={arrow}/>}</g>)}</>}</GeoDiagram></>;}
 if(kind==='proof')return <GeoDiagram title="The coordinate proof follows the message through four operations" height={325}>{arrow=><>{[['relative vector','Q(xᵢ − xⱼ); t cancels'],['squared distance','same scalar under Q'],['radial multiplier','same 1 / (1 + r²)'],['weighted direction','Q times original sum']].map(([a,b],i)=><g key={a}><GeoBox x={8} y={14+i*76} w={130} text={a}/><GeoBox x={230} y={14+i*76} w={239} text={b}/><path d={`M138 ${32+i*76} L230 ${32+i*76}`} stroke="#e4b752" markerEnd={arrow}/></g>)}</>}</GeoDiagram>;
 if(kind==='pipeline')return <GeoDiagram title="Actual graph study: two residual blocks, one shared distance table" height={330}>{arrow=><><GeoBox x={5} y={15} w={140} text="34 × 3 (or 7)"/><GeoBox x={191} y={15} w={112} text="embed → 16"/><GeoBox x={352} y={15} w={120} text="pre-LayerNorm"/><path d="M145 33 L191 33 M303 33 L352 33 M412 51 L412 102" stroke="#e4b752" markerEnd={arrow}/><GeoBox x={275} y={103} w={195} text="2 heads × 8; 34 × 34"/><GeoBox x={5} y={103} w={212} text="shared distance table, 2 heads"/><path d="M217 121 L275 121 M372 139 L372 182" stroke="#bba4da" markerEnd={arrow}/><GeoBox x={225} y={184} w={245} text="residual → norm → GELU FF → residual"/><text x={9} y={207}>repeat block twice</text><GeoBox x={225} y={275} w={124} text="34 × 2 logits"/><GeoBox x={5} y={275} w={170} text="10 fit labels → CE"/><path d="M348 220 L348 259 L286 259 L286 275 M225 293 L175 293" fill="none" stroke="#e4b752" markerEnd={arrow}/></>}</GeoDiagram>;
 if(kind==='results')return <><div className="geo-plot" tabIndex={0} role="region" aria-label="All twelve observed graph transformer outcomes"><NeuralPlot title="Every fixed fit; one observed graph, no selected winner" xLabel="run index, not time" yLabel="assessment correct / 18" xDomain={[0,11]} yDomain={[0,1]} series={[{label:'majority 9/18',color:'#8fb9e8',values:[[0,.5],[11,.5]]},{label:'earlier fixed label propagation 16/18',color:'#bba4da',values:[[0,16/18],[11,16/18]]}]} points={examples.summary.map((r,i)=>({x:i,y:r.correct.assessment/18,label:`${r.kind}/${r.seed}: ${r.correct.assessment}/18`,color:'#e4b752'}))}/></div><p>Points are the twelve actual fits, not samples of a time series. The two reference lines describe fixed algorithms on this split. All fitting results and parameter counts remain in the table.</p></>;
 if(kind==='types')return <><GeoDiagram title="Physical feature types carry different numbers of independent coordinates" height={280}>{arrow=><>{[['scalar ℓ=0',1],['vector ℓ=1',3],['symmetric traceless ℓ=2',5]].map(([name,n],r)=><g key={name}><text x={8} y={38+r*82}>{name}</text>{Array.from({length:n},(_,i)=><rect key={i} x={230+i*40} y={17+r*82} width={28} height={32} fill={r===0?'#6a542b':r===1?'#3d597a':'#645171'} stroke="#b9b2c7"/>)}</g>)}</>}</GeoDiagram><GeoMatrix title="Example symmetric traceless tensor: T transforms as Q T Qᵀ" values={[[1,2,3],[2,-.5,4],[3,4,-.5]]}/><p>Symmetry removes three independent entries and trace zero removes one more: 9 − 3 − 1 = 5. A general matrix has scalar trace (1), antisymmetric part (3) and symmetric traceless part (5).</p></>;
 if(kind==='frames'){const qi=[1,0,0],kj=[0,1,0],ri=rotation(90),rj=rotation(-90),ti=[2,0,0],tj=[0,2,0],q=add(matvec(ri,qi),ti),k=add(matvec(rj,kj),tj),weighted=q.map((v,i)=>.25*v+.75*k[i]),local=matvec([[0,1,0],[-1,0,0],[0,0,1]],weighted.map((v,i)=>v-ti[i]));return <><GeoDiagram title="Point attention carries local points into a shared frame, then back to the receiver" height={300}>{arrow=><><GeoBox x={6} y={19} w={150} text="receiver local query"/><GeoBox x={318} y={19} w={150} text="sender local key"/><GeoBox x={6} y={102} w={150} text="Rᵢ q + tᵢ"/><GeoBox x={318} y={102} w={150} text="Rⱼ k + tⱼ"/><path d="M81 55 L81 102 M393 55 L393 102 M156 120 L318 120" stroke="#e4b752" markerEnd={arrow}/><text x={175} y={99}>squared distance</text><GeoBox x={148} y={196} w={178} text="global weighted point"/><GeoBox x={148} y={260} w={178} text="Rᵢᵀ (point − tᵢ)"/><path d="M393 138 L393 214 L326 214 M81 138 L81 214 L148 214 M237 232 L237 260" stroke="#8fb9e8" fill="none" markerEnd={arrow}/></>}</GeoDiagram><NeuralTable caption="Constructed frames; no protein structure or learned prediction" headers={['Quantity','Coordinates']} rows={[[ 'Global query',vector(q)],['Global key',vector(k)],['Distance squared',q.reduce((s,v,i)=>s+(v-k[i])**2,0)],['Fixed illustrative .25/.75 global mixture',vector(weighted)],['Receiver-local result',vector(local)]]}/></>;}
 return null;
}
