import { Code, H3, Prose } from '../content';
import MechanismProgram from './MechanismProgram.jsx';
import output from '../../data/graph-traversal-library-output.json';

export default function GraphTraversalLibraryBridge() {
  return <section id="graph-library-bridge" data-implementation-depth="graph-traversal">
    <H3>Keep the graph contract when using NetworkX</H3>
    <Prose>A graph package is useful when construction, traversal and later analyses must share one representation. The runnable bridge uses NetworkX 3.6.1. Install it with <Code>python -m pip install networkx==3.6.1</Code>. Save <a href="/learn-assets/graphs-representations-bfs-dfs/graph_traversal_mechanisms.py" download>graph_traversal_mechanisms.py</a> beside the program, then run <Code>python graph_library.py</Code>. Those imported BFS, frame-based DFS and component functions are exactly the mechanisms already taught above.</Prose>
    <Prose>The local builder is the contract boundary: declare unique non-None vertices, reject undeclared endpoints, preserve direction, and collapse repeated edges. Then <Code>add_nodes_from</Code> keeps H even though no edge mentions it. <Code>Graph</Code> represents undirected relationships; <Code>DiGraph</Code> represents arrows. In either case a self-loop is allowed. A different multigraph representation is necessary if edge occurrences themselves matter.</Prose>
    <MechanismProgram source="/learn-assets/graphs-representations-bfs-dfs/graph_library.py" title="Compare reachable distances, DFS reachability and components" output={output['graph_library.py']} />
    <Prose>From E, the undirected version reaches A in three edges. With arrows as listed, E reaches only itself. The comparison checks distances and that each returned route follows real edges with the correct length. It compares component membership as sets and DFS reachability, because neighbor order can select different equally valid trees. A route to the source has zero edges; an absent distance means unreachable. This bridge materializes all returned paths only for the small witness example: all-path storage can be quadratic on a long chain. For distances alone, use <Code>single_source_shortest_path_length</Code>, preserving the O(V + E) adjacency-list traversal and O(V) search state.</Prose>
    <Prose>NetworkX's <a href="https://networkx.org/documentation/stable/reference/classes/digraph.html" target="_blank" rel="noopener noreferrer">graph representation contract</a> and <a href="https://networkx.org/documentation/stable/reference/algorithms/shortest_paths.html" target="_blank" rel="noopener noreferrer">shortest-path API guide</a> are the practical reference. Later weighted/flow lessons reuse this explicit construction boundary and add their own edge attributes. Grid neighbor generation and identity-preserving object cloning remain useful custom functions; a general package need not replace them.</Prose>
    <H3>Transfer: incoming reachability is a different question</H3>
    <Prose>Add a new isolated vertex I. On the directed fixture, implement the distances of vertices that can reach E. Keep every vertex in the result, using None for unreachable vertices. Explain why a forward search from E answers the wrong question.</Prose>
    <details><summary>Optional hint</summary><Prose>Reverse every directed edge, keep the same vertex set, then start at E. NetworkX can provide a reversed view with <Code>graph.reverse(copy=False)</Code>; keep the original unchanged while using the view.</Prose></details>
    <details><summary>Solution and reasoning</summary><Prose>In the reversed graph E has distance 0, D has 1, B and C have 2, and A has 3. F, G, H and I remain unreachable. Implement the scratch reversal by allocating an empty neighbor list for every vertex and appending each original tail to its head's list. Compare the resulting BFS distances with the library's reversed view. Reversal costs O(V + E) when materialized; the library view avoids copying topology but still reflects later changes to the original graph.</Prose></details>
  </section>;
}
