import RemoteCodeBlock from '../content/RemoteCodeBlock.jsx';
import { useState, useEffect, useRef } from 'react';
import { NeuralLab, NeuralSelect, NeuralTable, formatNeural as f } from './NeuralLessonElements.jsx';
import { NeuralNumber } from './NeuralNumberControl.jsx';
import { OdeFigure, OdePlot, odeVector, odeColors } from './NeuralOdeLabs.jsx';
import { odeClassifier } from '../../data/neural-ode-models.js';
import { odeStudy } from '../../data/neural-ode-study.js';
const base='/learn-assets/neural-ode-continuous-depth-models/';
const kinds=[['linear','Linear'],['residual','Four residual blocks'],['neural_ode','Shared neural field'],['augmented_ode','Augmented neural field']];
function useOdeAsset(file){const container=useRef(null),[visible,setVisible]=useState(false),[resource,setResource]=useState(null),[failed,setFailed]=useState(null),[attempt,setAttempt]=useState(0);useEffect(()=>{const observer=new IntersectionObserver(entries=>{if(entries.some(e=>e.isIntersecting)){setVisible(true);observer.disconnect();}},{rootMargin:'220px'});if(container.current)observer.observe(container.current);return()=>observer.disconnect();},[]);useEffect(()=>{if(!visible)return;const controller=new AbortController();setResource(null);setFailed(null);fetch(base+file,{signal:controller.signal}).then(r=>{if(!r.ok)throw new Error();return r.json();}).then(data=>{if(!controller.signal.aborted)setResource({file,data});}).catch(()=>{if(!controller.signal.aborted)setFailed(file);});return()=>controller.abort();},[visible,file,attempt]);return{container,data:resource?.file===file?resource.data:null,failed:failed===file,retry:()=>setAttempt(v=>v+1)};}
export function OdeStudyFigure(){const [log,setLog]=useState(false),series=odeStudy.runs.map((r,i)=>({label:`${r.kind}, seed${r.seed}`,color:odeColors[Math.floor(i/3)],dashed:i%3!==0,values:r.curves.map(c=>[c.step,log?Math.log10(c.validation.cross_entropy):c.validation.cross_entropy])})),values=series.flatMap(s=>s.values.map(v=>v[1]));return <><OdePlot title="All12 validation histories; each line retains its model and seed" xLabel="AdamW update" yLabel={log?'log10 validation cross-entropy':'validation cross-entropy (nats/record)'} xDomain={[1,300]} yDomain={[log?Math.min(...values)-.1:0,Math.max(...values)*1.05]} series={series}/><button onClick={()=>setLog(v=>!v)}>{log?'Use linear loss axis':'Use log10 loss axis'}</button><OdeFigure title="Paired assessment counts with parameter counts, not a leaderboard" height={380}>{kinds.map(([key,label],k)=><g key={key}><text x="12" y={45+k*83}>{label}</text><text x="12" y={66+k*83}>{odeStudy.runs.find(r=>r.kind===key).parameters} parameters</text><path d={`M205 ${45+k*83} H634`}/>{odeStudy.runs.filter(r=>r.kind===key).map((r,j)=><g key={r.seed}><circle cx={205+429*r.assessment.correct/29} cy={34+k*83+j*14} r="4" style={{fill:odeColors[j],stroke:odeColors[j]}}/><text x={205+429*r.assessment.correct/29-8} y={38+k*83+j*14} textAnchor="end">{r.seed}: {r.assessment.correct}/29</text></g>)}</g>)}<text x="205" y="366">0 correct</text><text x="634" y="366" textAnchor="end">29/29 correct</text></OdeFigure><p>The count axis is shared; each seed appears separately. Checkpoint selection used validation cross-entropy. These three paired seeds do not establish a universal architecture ranking or a confidence interval.</p></>;}
export function OdeStiffFigure(){return <NeuralTable caption="Executed SciPy solve of a smooth solution with a hidden fast mode" headers={['Stiffness κ','Solver','Accepted intervals','Field calls','Jacobian evaluations','Linear factorizations','Endpoint error']} rows={odeStudy.stiff.map(r=>[r.stiffness,r.method,r.accepted_intervals,r.nfe,r.njev,r.nlu,r.error.toExponential(5)])}/>;}
export function OdeWorkedIrisFigure(){const r=odeStudy.worked,s=odeStudy.sources.find(row=>row.id===64);return <><p>Worked row64: raw centimeters {odeVector(s.features)} become standardized {odeVector(r.standardized_initial)}. The seed37 neural field below is evaluated by four classical RK4 intervals, with16 field calls.</p><div className="ode-two">{[0,1,2,3].map(i=><OdePlot key={i} title={`Worked flower: hidden coordinate${i}`} xLabel="depth" yLabel={`z${i}`} xDomain={[0,1]} yDomain={[Math.min(...r.variant.trace.map(z=>z[i]))-.05,Math.max(...r.variant.trace.map(z=>z[i]))+.05]} series={[{label:'Actual saved-field state',color:odeColors[i],values:r.variant.trace.map((z,j)=>[j/4,z[i]])}]}/>)}</div><NeuralTable caption="The complete worked final state reaches the actual three-class readout" headers={['Final state','Logits','Probabilities']} rows={[[odeVector(r.variant.trace.at(-1)),odeVector(r.variant.logits),odeVector(r.variant.probabilities)]]}/></>;}
function IrisExplorer({snapshot,source,raw,setRaw,steps,setSteps,method,setMethod}){
 const [selected,setSelected]=useState(0),[pair,setPair]=useState([0,1]);
 const result=odeClassifier(snapshot,raw,odeStudy.metadata,steps,method),baseline=odeClassifier(snapshot,source.features,odeStudy.metadata,steps,method),dimension=result.endpoint.length,index=Math.min(selected,result.trace.length-1),delta=result.probabilities.map((v,i)=>v-baseline.probabilities[i]),unit=10**Math.floor(Math.log10(Math.max(1e-12,...delta.map(Math.abs))));
 const [a,b]=pair.map(v=>Math.min(v,dimension-1)),extent=Math.max(.1,...result.trace.flatMap(v=>[v[a],v[b]]),...result.trace.flatMap(v=>[-v[a],-v[b]]))*1.1;
 const x=v=>165+125*v/extent,y=v=>157-125*v/extent,traceTime=i=>i/steps;
 return <><p>Validation source row{source.id}, original species {source.species}. The saved {snapshot.kind} model, seed{snapshot.seed}, selected update{snapshot.selected_step}, stays fixed. Edited measurements have no newly established species label.</p><div className="ode-controls">{raw.map((v,i)=><NeuralNumber key={i} label={`${odeStudy.metadata.columns[i]} (cm)`} value={v} min={Math.min(odeStudy.bounds[i][0],source.features[i]-.6)} max={Math.max(odeStudy.bounds[i][1],source.features[i]+.6)} onChange={n=>setRaw(a=>a.map((v,j)=>i===j?n:v))}/>)}<NeuralSelect label="Saved-field numerical solver" value={method} onChange={setMethod} options={[["rk4","Classical RK4"],["euler","Euler"]]}/><NeuralSelect label="Intervals for this inference" value={steps} onChange={v=>setSteps(Number(v))} options={[4,16,64].map(n=>[n,`${n} intervals`])}/></div>
 <OdeFigure title="This current measurement through the whole saved classifier" height={265}><rect x="12" y="88" width="128" height="69"/><text x="76" y="109" textAnchor="middle">raw centimeters</text>{raw.map((v,i)=><text key={i} x={31+i*27} y="140" textAnchor="middle">{f(v,2)}</text>)}<path d="M140 121 H177"/><text x="153" y="114">→</text><rect x="180" y="65" width="134" height="114"/><text x="247" y="88" textAnchor="middle">(raw−fit μ)/fit σ</text>{result.standardized.map((v,i)=><text key={i} x="247" y={107+i*19} textAnchor="middle">z{i}={f(v,5)}</text>)}<path d="M314 121 H349"/><text x="325" y="114">→</text><rect x="353" y="78" width="142" height="88"/><text x="424" y="101" textAnchor="middle">same learned field</text><text x="424" y="125" textAnchor="middle">{dimension}D state, depth0→1</text><text x="424" y="148" textAnchor="middle">{result.nfe} field calls</text><path d="M495 121 H530"/><text x="506" y="114">→</text><rect x="533" y="80" width="133" height="84"/><text x="600" y="103" textAnchor="middle">WzT+b → softmax</text>{result.probabilities.map((v,i)=><text key={i} x="600" y={123+17*i} textAnchor="middle">P{i}={f(v,6)}</text>)}<text x="14" y="211">Fit-only μ={odeVector(odeStudy.metadata.mean)}</text><text x="14" y="235">Fit-only σ={odeVector(odeStudy.metadata.scale)}; extra augmented coordinates start at0.</text></OdeFigure>
 <NeuralTable caption="Current result and original measurement under the same solver settings" headers={['Class','Original probability','Current probability','Current logit','Probability delta']} rows={result.probabilities.map((v,i)=>[odeStudy.metadata.classes[i],f(baseline.probabilities[i],9),f(v,9),f(result.logits[i],7),delta[i].toExponential(6)])}/><OdePlot title="Local probability sensitivity, enlarged signed change" xLabel="class0 setosa,1 versicolor,2 virginica" yLabel={`probability change / ${unit.toExponential(0)}`} xDomain={[0,2]} yDomain={[Math.min(-1,...delta.map(v=>v/unit))*1.1,Math.max(1,...delta.map(v=>v/unit))*1.1]} series={[{label:'Current minus original, same model/solver',color:odeColors[0],values:delta.map((v,i)=>[i,v/unit])}]}/><p>Multiply the vertical value by {unit.toExponential(0)} probability. This local comparison shows sensitivity, not improved accuracy. The same model and solver settings define both inputs.</p>
 <div className="ode-two">{Array.from({length:dimension},(_,coordinate)=><OdePlot key={coordinate} title={`Complete hidden trace: coordinate${coordinate}`} xLabel="representation depth" yLabel={`hidden z${coordinate}`} xDomain={[0,1]} yDomain={[Math.min(...result.trace.map(r=>r[coordinate]),...baseline.trace.map(r=>r[coordinate]))-.05,Math.max(...result.trace.map(r=>r[coordinate]),...baseline.trace.map(r=>r[coordinate]))+.05]} series={[{label:'Current input',color:odeColors[coordinate],values:result.trace.map((r,i)=>[traceTime(i),r[coordinate]])},{label:'Original input',dashed:true,color:'#ddd',values:baseline.trace.map((r,i)=>[traceTime(i),r[coordinate]])}]}/>)}</div>
 <section data-lesson-teaching="" className="lesson-teaching-section"><h4 className="lesson-teaching-section__title">Inspect an actual state and a two-coordinate projection</h4><div className="ode-controls"><NeuralNumber label="Accepted state index" value={index} min={0} max={result.trace.length-1} integer step={1} onChange={setSelected}/>{[0,1].map((_,i)=><NeuralSelect key={i} label={`${i?'Vertical':'Horizontal'} projected coordinate`} value={i?b:a} onChange={v=>setPair(p=>p.map((u,j)=>i===j?Number(v):u))} options={Array.from({length:dimension},(_,j)=>[j,`Coordinate${j}`])}/>)}</div><p>Depth{f(traceTime(index),5)}: {odeVector(result.trace[index])}. These are hidden representations, not growing flower measurements.</p><OdeFigure title="Selected two-dimensional projection of the full hidden trace" width={340} height={325}><path d="M32 157 H299 M165 28 V285"/><polyline points={result.trace.map(r=>`${x(r[a])},${y(r[b])}`).join(' ')} style={{stroke:odeColors[1],strokeWidth:2}}/><circle cx={x(result.trace[index][a])} cy={y(result.trace[index][b])} r="6" style={{fill:odeColors[0]}}/><text x="165" y="310" textAnchor="middle">equal axes ±{f(extent,3)}; x=z{a},y=z{b}</text></OdeFigure></section>
 <div className="neural-buttons"><button onClick={()=>setRaw(a=>a.map((v,i)=>i===2?source.features[2]+.6:v))}>Set petal length to original+0.6cm</button><button onClick={()=>setRaw(a=>a.map((v,i)=>i===2?source.features[2]-.6:v))}>Set petal length to original−0.6cm</button><button onClick={()=>{setRaw(source.features);setSteps(4);setMethod('rk4');setSelected(0);setPair([0,1]);}}>Reset current flower</button></div></>;
}
export function OdeIrisLab(){const[kind,setKind]=useState('neural_ode'),[seed,setSeed]=useState(37),[sourceId,setSource]=useState(70),[raw,setRaw]=useState(odeStudy.sources.find(s=>s.id===70).features),[steps,setSteps]=useState(4),[method,setMethod]=useState('rk4'),resource=useOdeAsset(`model-${kind}-${seed}.json`),source=odeStudy.sources.find(s=>s.id===sourceId);return <div ref={resource.container}><NeuralLab id="ode-iris" title="Edit a real measurement; keep every model weight fixed"><div className="ode-controls"><NeuralSelect label="Saved field architecture" value={kind} onChange={setKind} options={kinds.slice(2)}/><NeuralSelect label="Saved fit seed" value={seed} onChange={v=>setSeed(Number(v))} options={[13,37,61].map(v=>[v,`${v}`])}/><NeuralSelect label="Validation source record" value={sourceId} onChange={v=>{setSource(Number(v));setRaw(odeStudy.sources.find(s=>s.id===Number(v)).features);}} options={odeStudy.sources.map(s=>[s.id,`Row${s.id}: ${s.species}`])}/></div>{resource.failed?<p role="alert">The selected saved model could not be loaded. Check your connection, then <button onClick={resource.retry}>retry model loading</button>.</p>:resource.data?<IrisExplorer key={`${kind}-${seed}-${sourceId}`} snapshot={resource.data} source={source} raw={raw} setRaw={setRaw} steps={steps} setSteps={setSteps} method={method} setMethod={setMethod}/>:<p role="status">Loading the selected saved field… Current edited measurements are preserved.</p>}</NeuralLab></div>;}
export function OdeProgram({file}){
  return <>
    <RemoteCodeBlock source={base + file} language="python" filename={file} title={"Read the complete " + (file)} />
  </>;
}
