import { useId, useState } from "react";
import { pivotModel, pivotMonths, pivotRegions } from '../../data/pandas-pivot-model.js';
import './scientific-concept-visuals.css';

export function PandasPivotLab() {
  const uid = useId();
  const [variation, setVariation] = useState('unique');
  const [operation, setOperation] = useState('pivot');
  const [selected, setSelected] = useState(0);
  const model = pivotModel(variation, operation);
  const cell = model.cells[selected];
  return <section className="sci-visual sci-pivot-lab" data-lab="pandas-pivot" aria-labelledby={`${uid}-title`}>
    <p className="lesson-eyebrow">LONG RECORDS → ROW/COLUMN COORDINATES</p><h3 id={`${uid}-title`}>Where does each record land?</h3>
    <p>Region chooses the output row; month chooses the column. Predict what happens when two source records request the same cell. Select any cell to trace its contributors.</p>
    <div className="sci-controls"><label>Source records<select value={variation} onChange={e => { setVariation(e.target.value); setSelected(e.target.value === 'missing' ? 3 : 0); }}><option value="unique">One record per region/month</option><option value="duplicate">Add a second North/Jan record</option><option value="missing">Remove the South/Feb record</option></select></label><label>Reshape rule<select value={operation} onChange={e => setOperation(e.target.value)}><option value="pivot">pivot: no aggregation</option><option value="sum">pivot_table: explicit sum</option><option value="mean">pivot_table: explicit mean</option></select></label></div>
    <div className="sci-pivot-layout"><div><h4>Long · {model.rows.length} records</h4><ol className="sci-pivot-records">{model.rows.map(row => <li key={row.id} className={cell.sources.some(source => source.id === row.id) ? 'is-linked' : ''}><strong>{row.id}</strong><span>{row.region} / {row.month}</span><b>{row.amount}</b>{cell.sources.some(source => source.id === row.id) && <small>→ selected cell</small>}</li>)}</ol></div><span className="sci-pivot-arrow" aria-hidden="true">→</span><div><h4>{model.blocked ? 'Requested grid · output blocked' : 'Wide · 2 rows × 2 columns'}</h4><div className="sci-pivot-grid" role="group" aria-label="Select a region and month"><span>region ↓<br />month →</span>{pivotMonths.map(month => <strong key={month}>{month}</strong>)}{pivotRegions.map((region, row) => <div className="sci-pivot-grid-row" key={region}><strong>{region}</strong>{pivotMonths.map((month, column) => { const index = row * 2 + column, item = model.cells[index]; return <button type="button" key={month} aria-label={`${region} ${month}: ${item.conflict ? 'collision' : model.blocked ? 'output blocked' : item.value ?? 'missing'}`} aria-pressed={selected === index} onClick={() => setSelected(index)}>{item.conflict ? <><b>2 → 1?</b><small>collision</small></> : <><b>{model.blocked ? '—' : item.value ?? 'NA'}</b><small>{item.sources.length} source{item.sources.length === 1 ? '' : 's'}</small></>}</button>; })}</div>)}</div></div></div>
    <div className="sci-pivot-feedback" role="status"><strong>{cell.region} / {cell.month} ← {cell.sources.length ? cell.sources.map(row => row.id).join(' + ') : 'no source record'}.</strong> {cell.conflict ? 'Two values want the same coordinate. pivot raises ValueError; it returns no partial table. Remove an unintended duplicate or choose a justified aggregation.' : model.blocked ? 'This cell has no collision, but a collision elsewhere prevents the entire pivot result.' : !cell.sources.length ? 'There was no amount to place here. NA preserves that absence; writing zero would make an extra assumption.' : operation === 'pivot' ? `${cell.value} moves into the cell; nothing is added or averaged.` : operation === 'sum' ? `${cell.sources.map(row => row.amount).join(' + ')} = ${cell.value}. Sum combines records; it does not determine whether a duplicate was legitimate.` : `(${cell.sources.map(row => row.amount).join(' + ')}) ÷ ${cell.sources.length} = ${cell.value}. A copied 10 leaves the mean at 10 even though the row count changed.`}</div>
    <button type="button" className="sci-reset" onClick={() => { setVariation('unique'); setOperation('pivot'); setSelected(0); }}>Reset pivot</button>
    <p className="sci-caption">Try sum and mean on the duplicated input. Then remove South/Feb and explain its empty cell. These fixed records are the example below; r1–r5 are tracing labels, not extra Pandas keys. This bounded model illustrates reshape policies, not arbitrary DataFrame execution. Months are displayed in calendar order explicitly.</p>
  </section>;
}
