import { Code, H3, Prose } from '../content';
import MechanismProgram from './MechanismProgram.jsx';
import output from '../../data/persistent-structures-library-output.json';

export default function PersistentMapLibraryBridge() {
  return <section id="persistent-library-bridge" data-implementation-depth="persistent-structures">
    <H3>Choose what the persistent collection must answer</H3>
    <Prose>The path-copy tree is a reusable array index: build once in O(n), assign through O(log n) newly copied path nodes, and query a range in O(log n). A maintained persistent mapping serves a different common workload: branch an immutable collection of key/value bindings. The immutables package supplies an unordered Map backed by a hash-array mapped trie. Its hash navigation is distinct from our interval navigation; it does not maintain range sums.</Prose>
    <Prose>Install <Code>python -m pip install immutables==0.21</Code>. Save <a href="/learn-assets/persistent-data-structures-structural-sharing-versioned-queries/persistent_structures_mechanisms.py" download>persistent_structures_mechanisms.py</a> beside the comparison and run <Code>python persistent_map_library.py</Code>. Here integer indices are map keys. Each operation names a parent version; <Code>map.set(index,value)</Code> returns the next map, just as assign returns a new tree root. Keeping the old handle preserves the old bindings.</Prose>
    <MechanismProgram source="/learn-assets/persistent-data-structures-structural-sharing-versioned-queries/persistent_map_library.py" title="Compare branching immutable versions and a batch edit" output={output['persistent_map_library.py']} />
    <Prose>Version 2 branches from version 0, so it retains index 2's value 4 even though version 1 changed it to 9. The program checks every position and an interval in every version. The map interval is deliberately computed by visiting its keys: summing a long interval is linear in the number of retrieved values, multiplied by lookup cost. The tree's cached summary avoids that scan. An immutable collection is not automatically an aggregate index.</Prose>
    <Prose>The library's <Code>mutate</Code> context groups several edits before finish returns a new map. It is useful when many bindings change together; do not publish the transient editing object as a persistent snapshot. Neither frozen tree fields nor immutable map bindings recursively freeze a mutable payload. The program's shared list changes through both references, which is why the core tree uses immutable integers. Hash-trie performance also depends on key hashing/equality and collision behavior; this example reports no measured universal speed or memory advantage. The project's <a href="https://github.com/MagicStack/immutables" target="_blank" rel="noopener noreferrer">primary API documentation</a> describes set/delete, transient edits and its hash-trie representation.</Prose>
    <H3>Transfer: a historical two-position correction</H3>
    <Prose>From version 0, create a new version setting indices 1 and 4 to −3 and 12. Implement the tree route with two assignments and the map route with one mutation context. Preserve versions 0–4. Compare every interval and explain the cost difference from a whole-array copy.</Prose>
    <details><summary>Optional hint</summary><Prose>The second tree assignment must use the first assignment's returned root. Both edits start from version 0's state, not the latest unrelated branch.</Prose></details>
    <details><summary>Solution and reasoning</summary><Prose>The new version is [2,−3,4,3,12], with total 18. A copied-array oracle should verify every [l,r) for every retained version, not just the latest total. The tree creates at most two logarithmic paths; shared ancestors may be allocated twice in this simple composition. The mutation context groups map writes while leaving the original unchanged. A whole-array copy costs O(n) copied elements even when only two positions change. Releasing a handle affects reclamation only when no remaining reference needs its shared nodes.</Prose></details>
  </section>;
}
