import { Code, H3, Prose } from '../content';
import MechanismProgram from './MechanismProgram.jsx';
import output from '../../data/range-query-library-output.json';

export default function RangeQueryLibraryBridge() {
  return <section id="range-library-bridge" data-implementation-depth="range-query">
    <H3>Carry the algebra into AtCoder's range APIs</H3>
    <Prose>The Python classes above are reusable implementations: their public methods isolate callers from interval decomposition and lazy propagation. In C++ algorithm work, the official AtCoder Library supplies the corresponding maintained containers. This optional language bridge keeps the same arrays, zero-based half-open intervals and operations. Read the mapping even if Python remains your working language; the Python replay exercises the same contract.</Prose>
    <Prose>Download <a href="/learn-assets/segment-trees-fenwick-trees-range-queries/ac-library-v1.6-range-headers.zip" download>the required official v1.6 headers and CC0 license</a>, extract the ac-library-v1.6 folder beside range_library.cpp, then compile with <Code>g++ -std=c++17 -O2 -Iac-library-v1.6 range_library.cpp -o range_library</Code>. Run the resulting executable (range_library.exe on Windows). This requires a C++17 compiler; Python does not execute the C++ file. Header <a href="/learn-assets/segment-trees-fenwick-trees-range-queries/ac-library-provenance.json">provenance and hashes</a> identify the pinned upstream files.</Prose>
    <Prose>For the Python replay, save <a href="/learn-assets/segment-trees-fenwick-trees-range-queries/range_query_mechanisms.py" download>range_query_mechanisms.py</a> beside <a href="/learn-assets/segment-trees-fenwick-trees-range-queries/range_library_reference.py" download>range_library_reference.py</a> and run the latter. It imports the earlier classes without maintaining another copy. Both replays produce the same recorded output.</Prose>
    <MechanismProgram language="C++" source="/learn-assets/segment-trees-fenwick-trees-range-queries/range_library.cpp" title="Read the complete C++17 range-library comparison" output={output['range_library.cpp']} />
    <Prose><Code>SegmentTree.query(l,r)</Code> maps to <Code>segtree.prod(l,r)</Code>; point assignment maps to set. Fenwick's library add takes a <em>delta</em>, so assigning index 4 from 0 to 3 adds 3 and updates the caller's saved value. Its sum method accepts [l,r). Both totals change from 15 to 18. Construction differs: our Fenwick build is linear, while this straightforward library initialization issues n logarithmic add calls. Choose deliberately when initialization dominates.</Prose>
    <Prose>The lazy adapter stores (total, length), so an action x → ax + b maps a summary to (a·total + b·length, length). Composition takes the <em>newer</em> action after the older one. Set −2 then add 5 gives 3; reversing them gives −2. Starting from [2,1,3,4,0], the three updates yield [2,4,−2,3,3], total 10 and [2,4) sum 1. Padding has length zero, so the identity remains a true empty segment.</Prose>
    <Prose>With constant-size summaries and constant-time arithmetic, tree build/storage are O(n), and point/query/lazy operations are O(log n). The string-concatenation example demonstrates ordering only: copying a growing string is not a constant-time combine. C++ signed overflow is outside the supported contract; keep all totals and intermediate products within long long. These integer fixtures do, while Python's integers have a different bit-cost model. The official <a href="https://atcoder.github.io/ac-library/production/document_en/segtree.html" target="_blank" rel="noopener noreferrer">segment tree</a>, <a href="https://atcoder.github.io/ac-library/production/document_en/fenwicktree.html" target="_blank" rel="noopener noreferrer">Fenwick</a> and <a href="https://atcoder.github.io/ac-library/production/document_en/lazysegtree.html" target="_blank" rel="noopener noreferrer">lazy-tree contracts</a> document these caller responsibilities.</Prose>
    <H3>Transfer: reverse two updates and test the whole array</H3>
    <Prose>On [3,−1,4,0,2], assign 6 to [1,4), then add −2 to [2,5). Implement this with both lazy trees and compare every subrange with a direct array. Repeat with the update order reversed; include empty intervals and a non-power-of-two size.</Prose>
    <details><summary>Optional hint</summary><Prose>Store action composition as function composition, not componentwise addition. A later assignment discards the earlier affine value.</Prose></details>
    <details><summary>Solution and reasoning</summary><Prose>The first order yields [3,6,4,4,0], total 17; reversing yields [3,6,6,6,0], total 21. For every 0 ≤ l ≤ r ≤ 5, compare tree.prod(l,r).total or local query(l,r) with sum of the corresponding direct slice. All empty ranges return 0. Tests over all intervals detect stale descendants that a correct full-root total alone can miss.</Prose></details>
  </section>;
}
