import './recommender-labs.css';
export function RecommendationTimelineFigure() {
  return <figure className="rec-figure"><div className="rec-timeline"><div><strong>Fit · events 1–20</strong><span>Compute means, neighbors and factors using only this prefix.</span></div><div><strong>Choose · 21–25</strong><span>Compare settings on later evidence.</span></div><div><strong>Evaluate · 26–31</strong><span>Freeze the choice. Report new outcomes once.</span></div></div><figcaption>Actual invented event partitions used by the final program. After choosing settings, it refits on events 1–25 and evaluates 26–31. The desktop widths represent event counts; phones stack the same sequence for reading. An item's release time must also precede the request, even if it exists in today's catalogue.</figcaption></figure>;
}
export function AmbiguousCompletionFigure() {
  return <figure className="rec-figure"><div className="rec-completion-pair">{[[[1, .5], [2, 1]], [[1, 2], [.5, 1]]].map((matrix, index) => <div key={index}><p>Rank-one completion {index + 1}</p><div className="rec-small-matrix">{matrix.flatMap((row, rowIndex) => row.map((value, column) => <span key={`${rowIndex}-${column}`} className={rowIndex === column ? 'rec-given' : undefined}>{value}</span>))}</div></div>)}</div><figcaption>Gold entries are the only observations: both diagonal ratings equal 1. Blue off-diagonal predictions differ. Both determinants are 1 − 1 = 0 and both matrices are nonzero, so each has rank one. A small rank alone does not identify missing ratings.</figcaption></figure>;
}
export function RecommendationPipelineFigure() {
  return <figure className="rec-figure"><div className="rec-pipeline"><div><strong>1 · Eligible</strong><span>Available, permitted, request-time filters</span></div><div><strong>2 · Candidates</strong><span>Retrieve a manageable subset</span></div><div><strong>3 · Scores</strong><span>Personalize and compare</span></div><div><strong>4 · Slate</strong><span>Apply ordering and list constraints</span></div></div><figcaption>A stage can remove an item before the scoring model sees it. Better reranking cannot recover a missing candidate. A repeat-consumption service may keep previously used items eligible; the toy catalogue explicitly uses unseen-item recommendation.</figcaption></figure>;
}
