import { useId } from 'react';
import { formatNeural as f } from './NeuralLessonElements.jsx';
import movement from '../../data/rwkv-trajectory-example.json';

function ArrowDefinitions({ id }) {
  return <defs><marker id={id} viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#e0b660" /></marker></defs>;
}
function Box({ x, y, width, height = 40, label, detail }) {
  return <g><rect x={x} y={y} width={width} height={height} rx="3" fill="#222" stroke="#858585" /><text x={x + width / 2} y={y + (detail ? 17 : 25)} textAnchor="middle" fill="#eee">{label}</text>{detail && <text x={x + width / 2} y={y + 33} textAnchor="middle" fill="#e5c783">{detail}</text>}</g>;
}
export function MemoryTranscriptFigure() {
  const id = useId();
  return <figure className="rwkv-diagram"><figcaption>Query → compatibility weights → value contributions</figcaption><div className="rwkv-diagram-scroll" role="region" aria-label="Mechanism diagram; scroll horizontally if needed" tabIndex={0}><svg viewBox="0 0 330 400" role="img" aria-label="One query scores three legal keys. Weights one quarter, one half, one quarter multiply values 2, 8, and minus 1, summing to 4.25. A future donor is disconnected."><ArrowDefinitions id={id} /><Box x={82} y={8} width={164} label="Receiver query" />{[45, 165, 285].map((x, i) => <g key={i}><path d={`M165 48 L165 62 L${x} 62 L${x} 83`} fill="none" stroke="#e0b660" markerEnd={`url(#${id})`} /><Box x={x - 39} y={86} width={78} height={47} label={`key ${i + 1}`} detail={['score 0', 'score log2', 'score 0'][i]} /><line x1={x} x2={x} y1="133" y2="165" stroke="#e0b660" markerEnd={`url(#${id})`} /><rect x={x - 37} y="167" width="74" height="36" fill="#49391e" stroke="#e0b660" /><text x={x} y="190" textAnchor="middle" fill="#fff">{['¼', '½', '¼'][i]}</text><text x={x} y="232" textAnchor="middle" fill="#ddd">× {['2', '8', '−1'][i]}</text><line x1={x} x2={x} y1="240" y2="270" stroke="#83b4e8" markerEnd={`url(#${id})`} /><text x={x} y="289" textAnchor="middle" fill="#e5c783">{['0.5', '4', '−0.25'][i]}</text><path d={`M${x} 298 L${x} 318 L165 318 L165 335`} fill="none" stroke="#e0b660" markerEnd={i === 1 ? `url(#${id})` : undefined} /></g>)}<Box x={94} y={338} width={142} label="sum = 4.25" /><text x="165" y="396" textAnchor="middle" fill="#bdbdbd">Future record: no legal edge</text></svg></div><p>The weights normalize over the three legal keys. Values follow the blue contribution path; an unavailable future record has no path to the sum.</p></figure>;
}
export function MemoryChunkFigure() {
  const id = useId();
  return <figure className="rwkv-diagram"><figcaption>A carried summary and a causal triangle meet before division</figcaption><div className="rwkv-diagram-scroll" role="region" aria-label="Mechanism diagram; scroll horizontally if needed" tabIndex={0}><svg viewBox="0 0 340 400" role="img" aria-label="Incoming state covers earlier chunks; a 3 by 3 local score triangle includes only current/past positions. Their numerators and denominators add before division."><ArrowDefinitions id={id} /><Box x={10} y={10} width={140} height={50} label="earlier chunks" detail="S_in, z_in" /><Box x={190} y={10} width={140} height={50} label="this chunk" detail="Q, K, V" />{Array.from({ length: 9 }, (_, n) => { const row = Math.floor(n / 3), col = n % 3; return <g key={n}><rect x={204 + col * 34} y={82 + row * 34} width="31" height="31" fill={col <= row ? '#5b4523' : '#202020'} stroke="#777" /><text x={219 + col * 34} y={103 + row * 34} textAnchor="middle" fill="#eee">{col <= row ? '•' : '×'}</text></g>; })}<text x="255" y="205" textAnchor="middle" fill="#ddd">donor → receiver</text><path d="M80 60 V225 H135 V245" fill="none" stroke="#e0b660" markerEnd={`url(#${id})`} /><path d="M255 212 V225 H205 V245" fill="none" stroke="#e0b660" markerEnd={`url(#${id})`} /><Box x={53} y={250} width={234} height={55} label="add contributions" detail="Q S_in + local-weighted V" /><text x="80" y="113" textAnchor="middle" fill="#e0b660">Q S_in</text><text x="80" y="141" textAnchor="middle" fill="#e0b660">Q z_in</text><line x1="170" x2="170" y1="305" y2="334" stroke="#e0b660" markerEnd={`url(#${id})`} /><Box x={53} y={338} width={234} height={52} label="divide by combined mass" detail="Q z_in + local row sum" /></svg></div><p>Crossed cells cannot send future information backward. At the first row of a later chunk, earlier chunks still contribute through S_in and z_in.</p></figure>;
}
export function MemoryCircuitFigure() {
  const id = useId();
  return <figure className="rwkv-figure"><figcaption>Read and store have different wires</figcaption><div className="rwkv-panels">{[false, true].map(store => <div key={String(store)} className="rwkv-diagram-scroll" role="region" aria-label="Mechanism diagram; scroll horizontally if needed" tabIndex={0}><svg className="rwkv-small-circuit" viewBox="0 0 300 310" role="img" aria-label={store ? 'Storage decays old state, adds ordinary key-weighted value, and never stores the current bonus.' : 'Read combines old history with bonus-weighted current value before dividing.'}><ArrowDefinitions id={`${id}-${store}`} /><text x="150" y="22" textAnchor="middle" fill="#efcf89">{store ? 'STORE FOR NEXT TOKEN' : 'ANSWER THIS TOKEN'}</text><Box x={8} y={44} width={128} height={48} label="old A=2, B=1" detail={store ? '× retention .5' : 'unchanged history'} /><Box x={165} y={44} width={128} height={48} label="current v=8" detail={store ? 'exp(k)=2' : 'exp(u+k)=4'} /><path d="M72 92 V128 H116 V152" fill="none" stroke="#e0b660" markerEnd={`url(#${id}-${store})`} /><path d="M230 92 V128 H184 V152" fill="none" stroke="#e0b660" markerEnd={`url(#${id}-${store})`} /><Box x={38} y={158} width={224} height={52} label={store ? 'A=.5×2 + 2×8 = 17' : 'numerator 2 + 4×8 = 34'} detail={store ? 'B=.5×1 + 2 = 2.5' : 'denominator 1 + 4 = 5'} /><line x1="150" x2="150" y1="210" y2="238" stroke="#e0b660" markerEnd={`url(#${id}-${store})`} /><Box x={57} y={245} width={186} label={store ? 'save (17, 2.5)' : 'read 34/5 = 6.8'} /></svg></div>)}</div><p>Bonus u changes only the current read. Retention λ changes only how old state is stored for later positions. The two branches start from the same previous state.</p></figure>;
}
export function MemoryBlockFigure() {
  const id = useId();
  return <figure className="rwkv-diagram"><figcaption>Residual bypasses carry the representation; slots carry the sequence</figcaption><div className="rwkv-diagram-scroll" role="region" aria-label="Mechanism diagram; scroll horizontally if needed" tabIndex={0}><svg className="rwkv-block-diagram" viewBox="0 0 360 445" role="img" aria-label="Input flows through time normalization and mixing, with residual bypass, then through channel normalization and mixing with a second bypass. Previous inputs and memory slots attach to their respective branches."><ArrowDefinitions id={id} /><Box x={99} y={8} width={144} label="input x" /><Box x={99} y={72} width={144} label="time norm" /><Box x={99} y={136} width={144} label="time mixer" /><circle cx="171" cy="214" r="17" fill="#222" stroke="#ddd" /><text x="171" y="220" textAnchor="middle" fill="#fff">+</text><Box x={99} y={258} width={144} label="channel norm" /><Box x={99} y={322} width={144} label="channel mixer" /><circle cx="171" cy="408" r="17" fill="#222" stroke="#ddd" /><text x="171" y="414" textAnchor="middle" fill="#fff">+</text>{[[48, 72], [112, 136], [176, 195], [232, 258], [298, 322], [362, 389]].map(([a, b]) => <line key={a} x1="171" x2="171" y1={a} y2={b} stroke="#e0b660" markerEnd={`url(#${id})`} />)}<path d="M99 28 H45 V214 H150" fill="none" stroke="#83b4e8" markerEnd={`url(#${id})`} /><path d="M171 239 H45 V408 H150" fill="none" stroke="#83b4e8" markerEnd={`url(#${id})`} /><Box x={257} y={112} width={96} height={65} label="time state" detail="x_prev,a,b,p" /><path d="M257 148 H244" stroke="#e0b660" markerEnd={`url(#${id})`} /><Box x={257} y={307} width={96} height={65} label="channel" detail="x_prev" /><path d="M257 340 H244" stroke="#e0b660" markerEnd={`url(#${id})`} /></svg></div><p>Blue bypasses add the input around each sublayer. The two previous-input slots are distinct. Learned projection matrices belong to the model parameters outside these sequence-state slots.</p></figure>;
}
export function MemoryAddressCompass({ keys = [[1, 0], [.6, .8]], memory = [5, 4.64] }) {
  return <figure className="rwkv-compass"><figcaption>Address geometry and one signed memory row</figcaption><div className="rwkv-diagram-scroll" role="region" aria-label="Mechanism diagram; scroll horizontally if needed" tabIndex={0}><svg viewBox="0 0 240 240" role="img" aria-label="Two unit keys separated by their dot-product angle"><circle cx="120" cy="120" r="88" fill="none" stroke="#777" /><line x1="20" x2="220" y1="120" y2="120" stroke="#555" /><line x1="120" x2="120" y1="20" y2="220" stroke="#555" />{keys.map((key, i) => <g key={i}><line x1="120" y1="120" x2={120 + key[0] * 88} y2={120 - key[1] * 88} stroke={i ? '#83b4e8' : '#e0b660'} strokeWidth="3" /><circle cx={120 + key[0] * 88} cy={120 - key[1] * 88} r="4" fill={i ? '#83b4e8' : '#e0b660'} /></g>)}</svg></div><p>A=[{keys[0].join(', ')}]; B=[{keys[1].join(', ')}]. M=[{memory.map(v => f(v)).join(', ')}]. Overlap lets an A correction alter the B read.</p></figure>;
}
export function MemoryPipelineFigure() {
  const id = useId();
  return <figure className="rwkv-figure"><figcaption>One recorded hand path becomes a learnable sequence</figcaption><div className="rwkv-panels"><figure className="rwkv-path"><figcaption>Actual source row 7 · normalized coordinates</figcaption><div className="rwkv-diagram-scroll" role="region" aria-label="Mechanism diagram; scroll horizontally if needed" tabIndex={0}><svg viewBox="0 0 260 260" role="img" aria-label="Actual 45 point Libras validation trajectory with start ring and end square"><rect x="20" y="20" width="220" height="220" fill="none" stroke="#666" /><polyline points={movement.points.map(p => `${20 + 220 * p[0]},${240 - 220 * p[1]}`).join(' ')} fill="none" stroke="#e0b660" />{movement.points.map((p, i) => <circle key={i} cx={20 + 220 * p[0]} cy={240 - 220 * p[1]} r="2" fill="#eee"><title>Point {i + 1}</title></circle>)}<circle cx={20 + 220 * movement.points[0][0]} cy={240 - 220 * movement.points[0][1]} r="7" fill="none" stroke="#fff" /><rect x={16 + 220 * movement.points.at(-1)[0]} y={236 - 220 * movement.points.at(-1)[1]} width="8" height="8" fill="none" stroke="#fff" /></svg></div></figure><div className="rwkv-diagram-scroll" role="region" aria-label="Mechanism diagram; scroll horizontally if needed" tabIndex={0}><svg className="rwkv-small-circuit" viewBox="0 0 300 370" role="img" aria-label="45 by 2 coordinates project to 45 by 16, pass through two memory blocks, average to 16 features, and project to 15 logits. Training loss updates weights."><ArrowDefinitions id={id} />{[['45 × 2 coordinates', 'fixed 2x−1'], ['45 × 16 features', 'learned 2→16'], ['two memory blocks', '45 × 16 → 45 × 16'], ['temporal mean', 'sum / 45 → 16'], ['class readout', '16→15 logits']].map(([label, detail], i) => <g key={label}><Box x={31} y={8 + i * 68} width={238} height={48} label={label} detail={detail} />{i < 4 && <line x1="150" x2="150" y1={56 + i * 68} y2={76 + i * 68} stroke="#e0b660" markerEnd={`url(#${id})`} />}</g>)}</svg></div></div><p>Training labels produce a cross-entropy gradient through these learned maps. Validation and assessment use forward computations only. The ring and square mark actual start and end; they are not invented motion labels.</p></figure>;
}
export function MemoryContributionRibbon({ values, title }) {
  const scale = Math.max(1e-12, ...values.map(Math.abs));
  return <figure className="rwkv-ribbon"><figcaption>{title} · common signed scale ±{f(scale)}</figcaption>{values.map((value, i) => <div key={i}><span>{i + 1}</span><div><i style={{ left: value < 0 ? `${50 + 50 * value / scale}%` : '50%', width: `${50 * Math.abs(value) / scale}%`, background: value < 0 ? '#83b4e8' : '#e0b660' }} /></div><output>{f(value)}</output></div>)}</figure>;
}
