import { Code, H3, Prose } from '../content';
import MechanismProgram from './MechanismProgram.jsx';
import output from '../../data/randomized-algorithm-library-output.json';

export default function SamplingLibraryBridge() {
  return <section id="sampling-library-bridge" data-implementation-depth="randomized-algorithm">
    <H3>Use the sampling API without changing the experiment</H3>
    <Prose>The mechanisms above separate permutation, sampling without replacement, weighted draws with replacement and one-pass reservoir sampling. Python already provides <Code>Random.shuffle</Code>, <Code>sample</Code> and <Code>choices</Code>. Choose by the experiment's contract: shuffle mutates its supplied sequence, sample returns distinct <em>occurrences</em>, and choices may select the same occurrence repeatedly. Equal values do not become the same record.</Prose>
    <Prose>Save <a href="/learn-assets/randomized-algorithms-sampling-error-guarantees/randomized_algorithm_mechanisms.py" download style={{ overflowWrap: 'anywhere' }}>randomized_algorithm_mechanisms.py</a> beside the comparison and run <Code>python sampling_library.py</Code> with Python 3.12+. The download reuses our Fisher–Yates, integer-ticket picker and reservoir implementations. The example tags repeated values with their input indices and passes separate Random objects so no earlier draw silently consumes the next experiment's state.</Prose>
    <MechanismProgram source="/learn-assets/randomized-algorithms-sampling-error-guarantees/sampling_library.py" title="Compare random-library contracts and replay state" output={output['sampling_library.py']} />
    <Prose>A size-two reservoir and sample both choose two distinct occurrences, but equal seeds need not choose the same subset: the algorithms consume random bits differently. Reservoir also returns every available record when the stream is shorter than its capacity; sample raises when k exceeds population size. The exact small-choice enumeration and proof above establish the reservoir's uniform-subset claim. A handful of matching outputs or frequencies would not.</Prose>
    <Prose>Our integer-ticket picker retains exact interval sizes for arbitrarily large integer weights. The ordinary choices interface uses floating-point arithmetic, so it is useful for finite nonnegative weights with a positive representable total but is not an exact substitute for enormous integer-ticket counts. Zero-weight slots are checked here. For an unknown-length stream, keep reservoir's O(N) work and O(k) retained records; converting the stream to a list just to call sample changes the storage contract. For a known integer population, sample over range avoids constructing all N record objects. The <a href="https://docs.python.org/3/library/random.html" target="_blank" rel="noopener noreferrer">random API reference</a> specifies these semantics and state restoration; a saved state is a replay tool, not a proof of independence or a cross-version portability promise.</Prose>
    <H3>Transfer: reduce the reservoir after the stream ends</H3>
    <Prose>A one-pass reservoir holds four occurrence IDs sampled uniformly from a stream of at least four items. You now need only two. Implement an unbiased reduction without reading the stream again. Explain why taking the first two reservoir slots is not justified by the subset invariant alone.</Prose>
    <details><summary>Optional hint</summary><Prose>Condition on the four-item subset, then choose a uniform two-subset inside it. Slot order is a separate property from subset uniformity.</Prose></details>
    <details><summary>Solution and reasoning</summary><Prose>Use rng.sample(saved_reservoir, k=2), with fresh draws after the first sampling stage. For any target pair among N occurrences, the probability the four-subset contains it is 12/(N(N−1)); its conditional chance of being selected is 1/6, giving 2/(N(N−1)), exactly 1 divided by the number of pairs. Enumerate every four-subset and every internal pair for a six-item oracle; each pair must have the same count. Preserve occurrence IDs, check duplicates by identity, and define a separate policy if the original stream contained fewer than four items.</Prose></details>
  </section>;
}
