import { useId } from 'react';
import { formatNeural as f } from './NeuralLessonElements.jsx';
import trajectory from '../../data/self-attention-trajectory-example.json';

function Arrows({ id }) {
  return <defs><marker id={id} viewBox="0 0 8 8" refX="7" refY="4" markerWidth="6" markerHeight="6" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#ddb260" /></marker></defs>;
}
export function AttentionPathsFigure() {
  const id = useId();
  return <figure className="attention-path-diagram"><figcaption>Keep the comparison path separate from the value path</figcaption><div className="attention-diagram-scroll" role="region" aria-label="Mechanism diagram; scroll horizontally if needed" tabIndex={0}><svg viewBox="0 0 340 385" role="img" aria-label="A query compares with three keys; each match normalizes to a weight. Separately, three values multiply by those weights and converge at the output for A."><Arrows id={id} />{[55, 170, 285].map((x, i) => <g key={i}><rect x={x - 40} y="12" width="80" height="40" fill="#252525" stroke="#aaa" /><text x={x} y="37" textAnchor="middle" fill="#eee">input {String.fromCharCode(65 + i)}</text><path d={`M${x} 52 V72 H${x - 19} V90`} fill="none" stroke="#ddb260" markerEnd={`url(#${id})`} /><path d={`M${x} 52 V72 H${x + 27} V226`} fill="none" stroke="#83b4e8" /><circle cx={x - 19} cy="108" r="17" fill="#49381e" stroke="#e0b660" /><text x={x - 19} y="113" textAnchor="middle" fill="#eee">k</text><text x={x + 27} y="242" textAnchor="middle" fill="#83b4e8">v</text><line x1={x - 19} x2={x - 19} y1="125" y2="151" stroke="#ddb260" markerEnd={`url(#${id})`} /><rect x={x - 42} y="155" width="52" height="35" fill="#282828" stroke="#c6b28a" /><text x={x - 16} y="178" textAnchor="middle" fill="#ddd">q·k</text><path d={`M${x - 16} 190 V215 H${x + 5} V242`} fill="none" stroke="#ddb260" markerEnd={`url(#${id})`} /><circle cx={x + 5} cy="262" r="16" fill="#222" stroke="#ddd" /><text x={x + 5} y="267" textAnchor="middle" fill="#eee">×</text><path d={`M${x + 27} 245 L${x + 18} 254`} fill="none" stroke="#83b4e8" markerEnd={`url(#${id})`} /><path d={`M${x + 5} 278 V308 H170 V332`} fill="none" stroke="#ddb260" /></g>)}<text x="170" y="143" textAnchor="middle" fill="#eacb85">same receiver query qA</text><text x="170" y="207" textAnchor="middle" fill="#eacb85">normalize the three matches</text><rect x="90" y="333" width="160" height="40" fill="#302819" stroke="#ddb260" /><text x="170" y="358" textAnchor="middle" fill="#eee">sum → A's output</text></svg></div><p>Amber determines coefficients; blue carries value content. B and C make their own reads with the same learned maps and different queries.</p></figure>;
}
export function AttentionKeyPlane({ query, keys }) {
  const id = useId();
  const x = n => 150 + n * 40, y = n => 150 - n * 40;
  return <figure className="attention-value-plane"><figcaption>Matching space · q and k have separate vectors</figcaption><div className="attention-diagram-scroll" role="region" aria-label="Mechanism diagram; scroll horizontally if needed" tabIndex={0}><svg viewBox="0 0 300 300" role="img" aria-label={`Query ${query.join(',')} and three key vectors; their dot products are listed in the score table`}><Arrows id={id} /><rect x="30" y="30" width="240" height="240" fill="none" stroke="#666" /><line x1="30" x2="270" y1="150" y2="150" stroke="#666" /><line x1="150" x2="150" y1="30" y2="270" stroke="#666" />{keys.map((key, i) => <g key={i}><line x1="150" y1="150" x2={x(key[0])} y2={y(key[1])} stroke="#83b4e8" strokeWidth="2" strokeDasharray={i === 1 ? '4 3' : undefined} /><circle cx={x(key[0])} cy={y(key[1])} r={4 + i} fill="none" stroke="#83b4e8"><title>Key {i + 1}: {key.join(', ')}</title></circle></g>)}<line x1="150" y1="150" x2={x(query[0])} y2={y(query[1])} stroke="#ddb260" strokeWidth="3" markerEnd={`url(#${id})`} /></svg></div><p>Amber arrow: q={query.map(v => f(v)).join(', ')}. Blue: donor keys. The comparison is a dot product, so both direction and magnitude matter. These are not value-space positions.</p></figure>;
}
export function AttentionLegalEdges({ receiver, allowed, weights }) {
  const id = useId();
  return <figure className="attention-legal-diagram"><figcaption>Actual donor → receiver paths for the current mask</figcaption><div className="attention-diagram-scroll" role="region" aria-label="Mechanism diagram; scroll horizontally if needed" tabIndex={0}><svg viewBox="0 0 340 210" role="img" aria-label={`Receiver ${receiver + 1} may read donors ${allowed.map((a, i) => a ? i + 1 : null).filter(Boolean).join(', ') || 'none'}`}><Arrows id={id} />{[40, 126, 212, 298].map((x, i) => <g key={i}><rect x={x - 29} y="15" width="58" height="42" fill="#252525" stroke={allowed[i] ? '#ddb260' : '#666'} strokeDasharray={allowed[i] ? undefined : '3 3'} /><text x={x} y="41" textAnchor="middle" fill="#eee">{String.fromCharCode(65 + i)}</text>{allowed[i] ? <path d={`M${x} 57 L${x} 80 L170 142`} fill="none" stroke={i > receiver ? '#c59cd3' : '#ddb260'} strokeWidth={1 + 3 * (weights?.[i] || 0)} markerEnd={`url(#${id})`} /> : <text x={x} y="104" textAnchor="middle" fill="#aaa">blocked</text>}</g>)}<rect x="115" y="147" width="110" height="42" fill="#302819" stroke="#ddb260" /><text x="170" y="174" textAnchor="middle" fill="#eee">receiver {String.fromCharCode(65 + receiver)}</text></svg></div><p>Solid edges carry normalized weight; absent edges carry none. Violet marks an enabled future edge, which the next-token task forbids.</p></figure>;
}
export function AttentionDataPipeline() {
  return <figure className="self-attention-figure"><figcaption>One measured path, two ways to preserve its information</figcaption><div className="self-attention-columns"><figure className="attention-value-plane"><figcaption>Source row 77 · actual point order</figcaption><div className="attention-diagram-scroll" role="region" aria-label="Mechanism diagram; scroll horizontally if needed" tabIndex={0}><svg viewBox="0 0 300 300" role="img" aria-label="Original Libras class 4 hand path with start ring and end square"><rect x="24" y="24" width="252" height="252" fill="none" stroke="#666" /><polyline points={trajectory.points.map(p => `${24 + 252 * p[0]},${276 - 252 * p[1]}`).join(' ')} fill="none" stroke="#ddb260" />{trajectory.points.map((p, i) => <circle key={i} cx={24 + 252 * p[0]} cy={276 - 252 * p[1]} r="2" fill="#ddd"><title>Point {i + 1}</title></circle>)}<circle cx={24 + 252 * trajectory.points[0][0]} cy={276 - 252 * trajectory.points[0][1]} r="8" fill="none" stroke="#fff" /><rect x={20 + 252 * trajectory.points.at(-1)[0]} y={272 - 252 * trajectory.points.at(-1)[1]} width="8" height="8" fill="none" stroke="#fff" /></svg></div></figure><div className="attention-pipeline-nodes"><div>45 × 2 measured points</div><span>↓ pointwise 2→24 + tanh</span><div>45 × 24 features</div><span>↓ one/two heads + residual</span><div>45 × 24 contextual rows</div><span>↓ mean erases row order</span><div>24 pooled features → 15 logits</div></div></div><p>The ordered-linear comparison follows a separate path: flatten 45×2 into 90 ordered coordinates → 15 logits. The exact observed table retains every seed, including the better ordered baseline.</p></figure>;
}
