import { useEffect, useMemo, useState } from 'react';
import { NeuralLab, NeuralNumber, NeuralSelect, NeuralTable, NeuralPlot, formatNeural as f } from './NeuralLessonElements.jsx';
import { sequenceTokens, shiftedTracks, scalarBridge, probabilityTree, lengthScore, encodeSequence, generatedTrace, sequenceBeam } from '../../data/seq2seq-models.js';
import measurements from '../../data/seq2seq-measurements.json';
import './seq2seq-labs.css';
export const seq2seqAsset = '/learn-code/sequence-to-sequence-encoder-decoder/';
const labelToken = value => typeof value === 'number' ? sequenceTokens[value] : value;
function TokenStrip({ title, tokens, active = -1 }) {
  return <figure className="seq-token-strip"><figcaption>{title}</figcaption><ol>{tokens.map((token, index) => <li key={index} className={index === active ? 'is-active' : ''}><small>{index + 1}</small><span>{labelToken(token)}</span></li>)}</ol></figure>;
}
function TextControl({ label, value, onChange, min = 1, max = 12 }) {
  const [draft, setDraft] = useState(null);
  return <label className="seq-text-control">{label}<input value={draft ?? value} aria-label={label} aria-invalid={draft !== null} onChange={event => {
    const text = event.target.value;
    if (new RegExp(`^[a-z]{${min},${max}}$`).test(text)) { setDraft(null); onChange(text); } else setDraft(text);
  }} onBlur={() => setDraft(null)} />{draft !== null && <small>Use {min}–{max} lowercase a–z letters. The views retain “{value}”.</small>}</label>;
}

export function Seq2SeqTimelines() {
  return <figure className="seq-timelines"><TokenStrip title="Source timeline: request + letters + EOS" tokens={['<past>', ...'lactate', '<eos>']} /><div className="seq-context-bridge">Encoder finishes → context vector → decoder initial state</div><TokenStrip title="Decoder inputs: previous target token" tokens={['<bos>', ...'lactated']} /><TokenStrip title="Decoder targets: letters + EOS" tokens={[...'lactated', '<eos>']} /><p>Source/output positions are different timelines. No line claims that their equally numbered tokens are aligned.</p></figure>;
}

export function Seq2SeqAlignmentLab() {
  const [target, setTarget] = useState('cared'), [padding, setPadding] = useState(0), [leak, setLeak] = useState(false), [position, setPosition] = useState(3), [probability, setProbability] = useState(.8);
  const track = shiftedTracks(target, padding, leak), second = shiftedTracks('tried', padding), selected = Math.min(position, track.targets.length - 1), count = track.valid + second.valid;
  const nll = -Math.log(probability), total = count * nll;
  return <NeuralLab id="seq2seq-alignment" title="The decoder receives the previous answer, not the one it is scoring">
    <p>Source stays <code>care + past</code>. Change the reference string and inspect actual shifted token tracks. Edited references are constructed counterfactual targets, not verified inflections.</p>
    <div className="neural-controls"><TextControl label="Reference target" value={target} onChange={setTarget} max={10} /><NeuralNumber label="Extra ignored PAD cells" value={padding} min={0} max={3} step={1} integer onChange={setPadding} /><NeuralNumber label="Inspect prediction position (zero-based)" value={selected} min={0} max={track.targets.length - 1} step={1} integer onChange={setPosition} /></div>
    <TokenStrip title="Encoder source (unchanged by a target edit)" tokens={['<past>', ...'care', '<eos>']} /><TokenStrip title={leak ? 'Incorrect same-position inputs: answer leakage' : 'Actual shifted decoder inputs'} tokens={track.inputs} active={selected} /><TokenStrip title="Targets and storage padding" tokens={track.targets} active={selected} />
    <p className="seq-result">At position {selected + 1}, receive <strong>{track.inputs[selected]}</strong> and score <strong>{track.targets[selected]}</strong>. {track.targets[selected] === '<pad>' ? 'This storage position is excluded from loss.' : 'This position is included in loss.'} {leak ? 'The current answer is being supplied as input; this is the wrong prediction task.' : 'Only the preceding target can enter this step.'}</p>
    <div className="neural-buttons"><button onClick={() => setTarget('carts')}>Change cared → carts</button><button onClick={() => setLeak(value => !value)}>{leak ? 'Restore correct shift' : 'Inspect incorrect unshifted inputs'}</button><button onClick={() => { setTarget('cared'); setPadding(0); setLeak(false); setPosition(3); setProbability(.8); }}>Reset alignment</button></div>
    <p>Changing target position 4 from e to t leaves the first four correctly shifted input positions unchanged. Position 5 receives the changed character; the first four distributions remain fixed for the same source/model.</p>
    <details><summary>See the mask and its denominator</summary><TokenStrip title="Second example targets: try → tried" tokens={second.targets} /><NeuralNumber label="Constructed correct-token probability at each valid position" value={probability} min={.05} max={.99} step="any" onChange={setProbability} /><p>For this explicitly constructed equal-probability example: {count} valid targets, including both EOS tokens. Loss sum = {f(total)} nats; valid-token mean = {f(nll)}. Extra PAD cells leave it unchanged. Incorrectly averaging across all storage slots gives {f(total / (track.targets.length + second.targets.length))}.</p><p>The fitted seed-one model's separate native check on cared/tried measured 1.074011445 nats over 12 valid targets before and after adding padding. The editable calculation above is a simple mask demonstration, not that fitted model.</p></details>
  </NeuralLab>;
}

export function Seq2SeqBridgeLab() {
  const [inputs, setInputs] = useState([-.3, .6]), [weight, setWeight] = useState(.7), [rate, setRate] = useState(.1), [detached, setDetached] = useState(false);
  const current = scalarBridge(inputs, weight, rate, detached);
  return <NeuralLab id="seq2seq-bridge" title="Follow the loss backward through the context bridge">
    <p>Constructed scalar tanh model, two output classes A/EOS. Encoder weights differ from decoder weights. The reference answer is A then EOS; both current outputs are visible.</p><div className="neural-controls">{inputs.map((value, index) => <NeuralNumber key={index} label={`Source scalar ${index + 1}`} value={value} min={-1} max={1} step="any" onChange={next => setInputs(previous => previous.map((item, i) => i === index ? next : item))} />)}<NeuralNumber label="Encoder input weight" value={weight} min={-1.5} max={1.5} step="any" onChange={setWeight} /><NeuralNumber label="Encoder update rate" value={rate} min={0} max={.2} step="any" onChange={setRate} /></div>
    <div className="seq-state-flow">{current.encoder.map((state, index) => <div key={index}><small>Encoder step {index + 1}</small><strong>{f(state)}</strong><span>tanh({f(weight)}×{f(inputs[index])} + .4×{f(index === 0 ? 0 : current.encoder[index - 1])} + .1)</span></div>)}</div><div className="seq-context-bridge">Context {f(current.context)} → decoder initial state</div>
    <div className="seq-state-flow">{current.decoder.map((state, index) => <div key={index}><small>Decoder {index + 1}; receives {index ? 'A (embedding .4)' : 'BOS (embedding .1)'}</small><strong>state {f(state)}</strong><div className="seq-probability-bar"><span style={{ width: `${current.probabilityA[index] * 100}%` }} /></div><span>P(A) {f(current.probabilityA[index])}; P(EOS) {f(1 - current.probabilityA[index])}</span><span>Target {index ? 'EOS' : 'A'}; NLL {f(current.losses[index])}</span></div>)}</div>
    <p className="seq-result">Mean NLL <strong>{f(current.loss)}</strong>. Encoder weight derivative {f(current.gradient, 8)}; proposed weight {f(current.nextWeight, 8)}; new NLL {f(current.nextLoss, 8)}.</p><p>{detached ? 'Detaching cuts this decoder-to-encoder gradient path. Forward states and probabilities remain identical.' : `Backwards: loss → context derivative ${f(current.contextGradient, 8)} → reused encoder-weight sensitivity ${f(current.sensitivity, 8)}.`} {current.nextLoss > current.loss + 1e-12 ? 'The selected step increases loss.' : rate === 0 ? 'Zero update rate is an exact null.' : 'The update follows the signed derivative computed from both target tokens.'}</p><div className="neural-buttons"><button aria-pressed={detached} onClick={() => setDetached(value => !value)}>{detached ? 'Reconnect context gradient' : 'Detach context gradient'}</button><button onClick={() => { setInputs([.2, .8]); setWeight(.7); setRate(.1); setDetached(false); }}>Worked manuscript fixture</button><button onClick={() => { setInputs([-.3, .6]); setWeight(.7); setRate(.1); setDetached(false); }}>Reset bridge</button></div>
  </NeuralLab>;
}

export function Seq2SeqTreeLab() {
  const [firstA, setFirstA] = useState(.55), [afterA, setAfterA] = useState(.6), [afterB, setAfterB] = useState(.85), [width, setWidth] = useState(2), [step, setStep] = useState(2), [alpha, setAlpha] = useState(0);
  const tree = probabilityTree(firstA, afterA, afterB, width), current = tree.history[step], greedy = probabilityTree(firstA, afterA, afterB, 1);
  const display = path => path.replace('!', ', EOS');
  return <NeuralLab id="seq2seq-tree" title="A locally likely first token can lose the whole sequence">
    <p>Complete constructed probability tree. Each slider changes a conditional row and updates its complement. The final winner is always visible; stepping changes which intermediate retained/pruned candidates you inspect.</p><div className="neural-controls"><NeuralNumber label="P(A) at root" value={firstA} min={.01} max={.99} step="any" onChange={setFirstA} /><NeuralNumber label="P(EOS | A)" value={afterA} min={.01} max={.99} step="any" onChange={setAfterA} /><NeuralNumber label="P(EOS | B)" value={afterB} min={.01} max={.99} step="any" onChange={setAfterB} /><NeuralNumber label="Tiny-tree beam width" value={width} min={1} max={2} step={1} integer onChange={setWidth} /></div>
    <div className="seq-tree">{['A', 'B'].map((name, index) => <div key={name}><h4>Root → {name}: {f(index ? 1 - firstA : firstA)}</h4><div>{tree.leaves.slice(index * 2, index * 2 + 2).map(leaf => <p key={leaf.path}>{display(leaf.path)}<br /><strong>P = {f(leaf.probability)}</strong><br />log P = {f(Math.log(leaf.probability))}</p>)}</div></div>)}</div>
    <p className="seq-result">Greedy: <strong>{display(greedy.winner.path)}</strong>, P {f(greedy.winner.probability)}. Beam {width}: <strong>{display(tree.winner.path)}</strong>, P {f(tree.winner.probability)}.</p><NeuralNumber label="Inspect search step" value={step + 1} min={1} max={3} step={1} integer onChange={value => setStep(value - 1)} /><NeuralTable caption={`Actual search frontier after step ${step + 1}`} headers={['Prefix / state identity', 'Probability', 'Status']} rows={[...current.candidates.map(item => [display(item.path), f(item.probability), item.path.endsWith('!') ? 'Retained; complete' : 'Retained; live']), ...current.pruned.map(item => [display(item.path), f(item.probability), 'Pruned'])]} /><p>The prefix determines the conditional distribution in this small tree. A neural candidate also owns the recurrent state after consuming its previous input. Completed candidates never append another EOS.</p>
    <details><summary>Change the length-ranking policy</summary><p>Separate constructed pair: lengths include EOS, exclude BOS. The GNMT denominator applies the exponent once.</p><NeuralNumber label="Length score alpha" value={alpha} min={0} max={2} step="any" onChange={setAlpha} /><NeuralTable caption="Ranking score = raw log P / ((5+L)/6)^alpha" headers={['Length', 'Raw log P', 'Ranking score']} rows={[[2, -1.2], [5, -1.4]].map(([length, logp]) => [length, logp, f(lengthScore(logp, length, alpha))])} /><p>Winner: {lengthScore(-1.2, 2, alpha) >= lengthScore(-1.4, 5, alpha) ? 'shorter' : 'longer'} answer. This ranking score is not a normalized probability.</p></details>
    <div className="neural-buttons"><button onClick={() => setAfterA(.9)}>Make A end with probability .9</button><button onClick={() => { setFirstA(.55); setAfterA(.6); setAfterB(.85); setWidth(2); setStep(2); setAlpha(0); }}>Reset probability tree</button></div>
  </NeuralLab>;
}

export function Seq2SeqEvidenceFigure() {
  const colors = ['#e4b752', '#ddd', '#a996ca'];
  return <section className="seq-evidence"><h3>Recorded development curves: every seed, the same 447 examples</h3><div className="neural-two">{[['teacher_forced_nll', 'Teacher-forced NLL', 'nats per valid target token'], ['exact', 'Generated exact match', 'correct / 447']].map(([key, title, units]) => <NeuralPlot key={key} title={title} xLabel="training updates" yLabel={units} xDomain={[0, 1200]} yDomain={[0, Math.max(...measurements.runs.flatMap(run => run.checkpoints.map(point => point[key])))]} series={measurements.runs.map((run, index) => ({ label: `Seed ${run.seed}`, color: colors[index], values: run.checkpoints.map(point => [point.update, point[key]]), dashed: index === 1 }))} />)}</div><p>Points are measured checkpoints; connecting lines guide the eye. There are no invented intermediate training-accuracy measurements.</p><details><summary>Exact checkpoint values and final slice counts</summary><NeuralTable caption="All actual development checkpoints" headers={['Seed', 'Update', 'NLL', 'Exact / 447']} rows={measurements.runs.flatMap(run => run.checkpoints.map(point => [run.seed, point.update, f(point.teacher_forced_nll), point.exact]))} /><NeuralTable caption="Final development length groups; no causal memory threshold" headers={['Seed', '3–5 letters: exact / 168', '6–8 letters: exact / 279']} rows={measurements.runs.map(run => [run.seed, measurements.slices[run.seed].length3to5.exact, measurements.slices[run.seed].length6to8.exact])} /></details></section>;
}

function useSequenceResource(file, open, json = false) {
  const [state, setState] = useState({ data: null, error: null }), [attempt, setAttempt] = useState(0);
  useEffect(() => {
    if (!open) return;
    const controller = new AbortController(); setState({ data: null, error: null });
    fetch(seq2seqAsset + file, { signal: controller.signal }).then(response => { if (!response.ok) throw new Error('The saved resource could not be loaded.'); return json ? response.json() : response.text(); }).then(data => { if (!controller.signal.aborted) setState({ data, error: null }); }).catch(error => { if (!controller.signal.aborted) setState({ data: null, error: error.message }); });
    return () => controller.abort();
  }, [file, open, json, attempt]);
  return { ...state, retry: () => setAttempt(value => value + 1) };
}
export function Seq2SeqProgram({ file, title }) {
  const [open, setOpen] = useState(false), resource = useSequenceResource(file, open);
  return <details className="seq-program" onToggle={event => setOpen(event.currentTarget.open)}><summary>{title}</summary><p><a href={seq2seqAsset + file} download>Download {file}</a></p>{open && (resource.error ? <p role="alert">{resource.error} <button onClick={resource.retry}>Retry source</button></p> : resource.data ? <pre tabIndex={0} role="region" aria-label={title}><code>{resource.data}</code></pre> : <p role="status">Loading source…</p>)}</details>;
}

function FittedSequence({ weights }) {
  const [lemma, setLemma] = useState('emmove'), [feature, setFeature] = useState('past'), [prefix, setPrefix] = useState(''), [contextMode, setContextMode] = useState('source'), [cap, setCap] = useState(16), [step, setStep] = useState(0), [coordinate, setCoordinate] = useState(0), [beamWidth, setBeamWidth] = useState(1);
  const context = useMemo(() => contextMode === 'zero' ? Array(64).fill(0) : contextMode === 'lactate' ? encodeSequence(weights, 'lactate', 'past').context : null, [weights, contextMode]);
  const trace = useMemo(() => generatedTrace(weights, lemma, feature, { prefix, context, cap }), [weights, lemma, feature, prefix, context, cap]);
  const baseline = useMemo(() => generatedTrace(weights, 'emmove', 'past'), [weights]);
  const beam = useMemo(() => sequenceBeam(weights, lemma, feature, beamWidth, cap), [weights, lemma, feature, beamWidth, cap]);
  const selected = Math.min(step, trace.steps.length - 1), current = trace.steps[selected];
  const ranked = current.probabilities.map((probability, token) => ({ probability, token })).filter(item => item.probability > 0).sort((a, b) => b.probability - a.probability);
  const known = lemma === 'emmove' && feature === 'past' ? 'Development source emmove + past; reference emmoved.' : lemma === 'lactate' && feature === 'past' ? 'Training source lactate + past; reference lactated.' : 'Edited query; no reference spelling or correctness score is claimed.';
  const reset = () => { setLemma('emmove'); setFeature('past'); setPrefix(''); setContextMode('source'); setCap(16); setStep(0); setCoordinate(0); setBeamWidth(1); };
  return <><div className="neural-controls"><TextControl label="Source lemma" value={lemma} onChange={setLemma} /><NeuralSelect label="Grammatical request" value={feature} onChange={setFeature} options={['past', 'participle', 'third_person'].map(value => [value, value])} /><TextControl label="Forced prefix (empty uses greedy choices)" value={prefix} onChange={setPrefix} min={0} max={6} /><NeuralSelect label="Decoder initial context" value={contextMode} onChange={setContextMode} options={[[ 'source', 'Current source context'], ['zero', 'Zero intervention'], ['lactate', 'Context from lactate + past']]} /><NeuralNumber label="Generated-token cap (includes EOS)" value={cap} min={1} max={16} step={1} integer onChange={setCap} /></div>
    <p>{known} Model: final seed 1, update 1200. Input has {trace.ids.length} source tokens; the decoder emitted {trace.tokens.length} tokens.</p>
    <TokenStrip title="Actual encoder inputs" tokens={trace.ids} /><div className="seq-context-bridge">Used decoder context: {contextMode === 'source' ? 'freshly encoded current source' : contextMode === 'zero' ? '64 zeros (intervention)' : 'fixed other source lactate + past'}</div><TokenStrip title="Current generated tokens (EOS is retained visibly)" tokens={trace.tokens} active={selected} />
    <p className="seq-result">Generated <strong>{trace.word || '(empty string)'}</strong>; {trace.ended ? 'natural EOS termination' : 'CAPPED: the model did not choose EOS'}. Raw log probability {f(trace.logProbability)}. Baseline emmove + past: <strong>{baseline.word}</strong>, first P(e) {f(baseline.steps[0].probabilities[10])}.</p>
    <div className="neural-controls"><NeuralNumber label="Inspect decoder step (zero-based)" value={selected} min={0} max={trace.steps.length - 1} step={1} integer onChange={setStep} /><NeuralNumber label="Hidden coordinate" value={coordinate} min={0} max={63} step={1} integer onChange={setCoordinate} /></div>
    <p>Step {selected + 1} receives <strong>{labelToken(current.previous)}</strong>. It selects {labelToken(current.selected)} {current.forced ? 'by prefix intervention' : 'by argmax'}. This distribution was computed before that token was supplied as the next input.</p><div className="seq-state-flow"><div><small>Encoder coordinate {coordinate}, through source positions</small><span>{trace.states.map(state => f(state[coordinate], 3)).join(' → ')}</span></div><div><small>Decoder coordinate {coordinate}</small><span>{trace.steps.map(state => f(state.state[coordinate], 3)).join(' → ')}</span></div></div>
    <div className="seq-next-probabilities">{ranked.slice(0, 6).map(item => <div key={item.token}><span>{labelToken(item.token)}</span><div><span style={{ width: `${item.probability * 100}%` }} /></div><strong>{f(item.probability, 6)}</strong></div>)}</div><details><summary>All 32 next-token probabilities</summary><NeuralTable caption="Output support is identical during training and generation" headers={['Token', 'Probability']} rows={current.probabilities.map((probability, token) => [labelToken(token), f(probability, 8)])} /></details>
    <div className="neural-buttons"><button onClick={() => { setLemma('emmode'); setPrefix(''); }}>Change source to emmode</button><button onClick={() => { setPrefix('a'); setStep(1); }}>Force first character a</button><button onClick={() => { setPrefix(trace.word.slice(0, 2)); }}>Replay first two current characters</button><button onClick={reset}>Reset fitted investigation</button></div>
    <details><summary>Compare actual candidate-owned beam search</summary><p>This separate search uses the current source's own context, no forced prefix, alpha 0, and the same token cap. Its controls do not change the intervention view above.</p><NeuralNumber label="Fitted-model beam width" value={beamWidth} min={1} max={3} step={1} integer onChange={setBeamWidth} /><NeuralTable caption="Final retained beam candidates and state ownership" headers={['Generated tokens', 'Raw log P', 'Termination', `State coordinate ${coordinate}`]} rows={beam.candidates.map(candidate => [candidate.tokens.map(labelToken).join(' '), f(candidate.logProbability), candidate.tokens.at(-1) === 2 ? 'EOS' : 'Capped', f(candidate.state[coordinate])])} /><p>Each state is after consuming the previous input; the candidate's newly emitted final token has not yet been fed back. Siblings may share this immutable parent-step state until their different emitted tokens are consumed next.</p></details>
    <p>Raw hidden coordinates are values, not assigned linguistic concepts. Zero context and forced characters are interventions on fixed weights. Prefix forcing preserves earlier distributions; a changed source must rerun its encoder.</p>
  </>;
}

export function Seq2SeqFittedLab() {
  const [open, setOpen] = useState(false), resource = useSequenceResource('seed-one-inference.json', open, true);
  return <NeuralLab id="seq2seq-fitted" title="Change a real source, a prefix or the context—and follow the consequence"><p>Load only the saved seed-one weights for bounded inference. This does not run training or download a pretrained model.</p><details onToggle={event => setOpen(event.currentTarget.open)}><summary>Open the saved inflection model</summary>{open && (resource.error ? <p role="alert">{resource.error} <button onClick={resource.retry}>Retry saved model</button></p> : resource.data ? <FittedSequence weights={resource.data.weights} /> : <p role="status">Loading saved model…</p>)}</details></NeuralLab>;
}
