import { useId } from 'react';
import { NeuralTable, NeuralPlot, formatNeural as f } from './NeuralLessonElements.jsx';
import { causalEdges, graphReach, featureMemory, projectedRead } from '../../data/sparse-attention-models.js';
import examples from '../../data/sparse-attention-examples.json';
import './sparse-attention.css';

export const vector = row => `[${row.map(value => f(value, 6)).join(', ')}]`;
export function SparseChart(props) {
  return <div className="sparse-chart-scroll" role="region" tabIndex={0} aria-label={`${props.title}; scroll horizontally if needed`}><NeuralPlot {...props} /></div>;
}
export function SparseMatrix({ values, title, rowLabel = 'feature', columnLabel = 'value' }) {
  const maximum = Math.max(1e-12, ...values.flat().map(Math.abs));
  return <div className="sparse-matrix"><p>{title} · rows: {rowLabel}; columns: {columnLabel}</p><div className="sparse-scroll" role="region" tabIndex={0} aria-label={title}><table><tbody>{values.map((row, i) => <tr key={i}>{row.map((value, j) => <td key={j} style={{ background: value < 0 ? `rgba(131,180,232,${.08 + .4 * Math.abs(value) / maximum})` : `rgba(224,182,96,${.08 + .4 * Math.abs(value) / maximum})` }}>{f(value, 5)}</td>)}</tr>)}</tbody></table></div></div>;
}
export function WeightStrip({ title, rows, labels }) {
  return <figure className="sparse-weight-strip"><figcaption>{title} · shared probability scale 0–1</figcaption>{rows.map((row, i) => <div key={i}><span>{labels[i]}</span><div className="sparse-bars">{row.map((value, j) => <div key={j} title={`Donor ${j}: ${f(value, 8)}`}><i style={{ height: `${100 * value}%`, background: i ? '#83b4e8' : '#e0b660' }} />{(row.length < 10 || j % 10 === 0) && <span>{j}</span>}</div>)}</div></div>)}<section data-lesson-teaching="" className="lesson-teaching-section"><h4 className="lesson-teaching-section__title">Exact donor weights</h4><NeuralTable caption={title} headers={['Donor', ...labels]} rows={rows[0].map((_, donor) => [donor, ...rows.map(row => f(row[donor], 8))])} /></section></figure>;
}
function Diagram({ title, height, children, label, width = 360 }) {
  return <figure className="sparse-diagram"><figcaption>{title}</figcaption><div className="sparse-scroll" tabIndex={0} role="region" aria-label={`${title}; scroll horizontally if needed`}><svg viewBox={`0 0 ${width} ${height}`} style={{ minWidth: width }} role="img" aria-label={label}>{children}</svg></div></figure>;
}
function Box({ x, y, width = 140, label, detail }) {
  return <g><rect x={x} y={y} width={width} height={detail ? 48 : 34} fill="#222" stroke="#999" rx="3" /><text x={x + width / 2} y={y + 21} textAnchor="middle">{label}</text>{detail && <text className="sparse-amber" x={x + width / 2} y={y + 39} textAnchor="middle">{detail}</text>}</g>;
}
function Arrow({ id, from, to, dashed = false, color = '#e0b660' }) {
  return <line x1={from[0]} y1={from[1]} x2={to[0]} y2={to[1]} stroke={color} strokeDasharray={dashed ? '4 3' : undefined} markerEnd={`url(#${id})`} />;
}
function Marker({ id }) {
  return <defs><marker id={id} viewBox="0 0 8 8" refX="7" refY="4" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#e0b660" /></marker></defs>;
}
export function LayerGraph({ mask, source, target, layers = 2, title = 'Possible information paths' }) {
  const id = useId(), reach = graphReach(mask, source, layers), path = reach.paths[target];
  const width = Math.max(360, 90 * (layers + 1)), height = mask.length * 27 + 55;
  const x = layer => 35 + layer * (width - 70) / layers, y = position => 39 + position * 27;
  return <><Diagram title={title} height={height} width={width} label={`Input position ${source} to output ${target} through ${layers} layers. ${path ? `Path ${path.join(' then ')}.` : 'No path.'}`}><Marker id={id} />{Array.from({ length: layers }, (_, layer) => <g key={layer}>{mask.flatMap((row, receiver) => row.map((allowed, donor) => allowed || donor === receiver ? <line key={`${receiver}-${donor}`} x1={x(layer)} y1={y(donor)} x2={x(layer + 1)} y2={y(receiver)} stroke="#aaa" opacity=".16" /> : null))}</g>)}{path && path.slice(1).map((position, i) => <Arrow key={i} id={id} from={[x(i) + 7, y(path[i])]} to={[x(i + 1) - 9, y(position)]} />)}{reach.stages.map((row, layer) => <g key={layer}><text x={x(layer)} y="15" textAnchor="middle">{layer ? `layer ${layer}` : 'input'}</text>{row.map((active, position) => <g key={position}><circle cx={x(layer)} cy={y(position)} r="9" fill={active ? '#755425' : '#222'} stroke={path?.[layer] === position ? '#e0b660' : '#888'} /><text x={x(layer)} y={y(position) + 4} textAnchor="middle">{position}</text></g>)}</g>)}</Diagram><p>{path ? `Possible path: ${path.join(' → ')}.` : `No ${layers}-layer path from ${source} to ${target}.`} Self links include residual routes. This establishes possible dependence, not a learned nonzero effect.</p></>;
}
export function ProjectionPaths({ values, coefficients, position }) {
  const id = useId(), result = projectedRead(values, coefficients, position);
  const height = 155 + values.length * 48;
  return <Diagram title="Full summary and prefix summary have different source paths" height={height} label={`Full result ${result.full}; prefix through ${position} result ${result.prefix}. Dashed paths originate in the future.`}><Marker id={id} />{values.map((value, i) => <g key={i}><Box x={5} y={15 + i * 48} width={107} label={`v${i}=${f(value)}`} /><text x="136" y={37 + i * 48} textAnchor="middle">×{f(coefficients[i])}</text>{coefficients[i] !== 0 && <><Arrow id={id} from={[156, 32 + i * 48]} to={[234, height - 112]} dashed={i > position} />{i <= position && <Arrow id={id} from={[156, 32 + i * 48]} to={[91, height - 62]} color="#83b4e8" />}</>}</g>)}<Box x={181} y={height - 108} width={175} label={`full = ${f(result.full)}`} detail="all source positions" /><Box x={4} y={height - 57} width={176} label={`prefix = ${f(result.prefix)}`} detail={`only positions ≤ ${position}`} /></Diagram>;
}
export function TrajectoryFigure({ points, predictions = [], truth = null, selected = -1, zoom = false }) {
  const markers = predictions.map((row, i) => ({ point: row.point, label: row.label, color: ['#e0b660', '#83b4e8', '#ddd'][i] }));
  const bounds = zoom ? [...markers.map(m => m.point), ...(truth ? [truth] : []), points.at(-1)] : [[0, 0], [1, 1]];
  const minX = Math.min(...bounds.map(p => p[0])), maxX = Math.max(...bounds.map(p => p[0]));
  const minY = Math.min(...bounds.map(p => p[1])), maxY = Math.max(...bounds.map(p => p[1]));
  const pad = zoom ? Math.max(.012, maxX - minX, maxY - minY) * .25 : 0;
  const x0 = minX - pad, x1 = maxX + pad, y0 = minY - pad, y1 = maxY + pad;
  const x = value => 45 + (value - x0) / (x1 - x0) * 270, y = value => 298 - (value - y0) / (y1 - y0) * 270;
  return <Diagram title={zoom ? 'Forecast zoom · explicit local coordinate limits' : 'Observed source 77 · original coordinate units'} height={345} label="Actual measured chronological hand path; circle, square and triangle distinguish forecasts; cross is the original true next point."><rect x="45" y="28" width="270" height="270" fill="none" stroke="#777" />{[0, .5, 1].map(t => <g key={t}><text x={45 + t * 270} y="322" textAnchor="middle">{f(x0 + t * (x1 - x0), 3)}</text><text x="40" y={302 - t * 270} textAnchor="end">{f(y0 + t * (y1 - y0), 3)}</text></g>)}{!zoom && <><polyline points={points.map(p => `${x(p[0])},${y(p[1])}`).join(' ')} fill="none" stroke="#a0a0a0" />{points.map((p, i) => <circle key={i} cx={x(p[0])} cy={y(p[1])} r={i === selected ? 6 : 2} fill={i === selected ? '#83b4e8' : '#eee'}><title>Observed point {i}: {vector(p)}</title></circle>)}</>}{markers.map((m, i) => <g key={m.label} fill="none" stroke={m.color} strokeWidth="2">{i === 0 ? <circle cx={x(m.point[0])} cy={y(m.point[1])} r="5" /> : i === 1 ? <rect x={x(m.point[0]) - 5} y={y(m.point[1]) - 5} width="10" height="10" /> : <path d={`M${x(m.point[0])} ${y(m.point[1]) - 6}l6 11h-12Z`} />}<title>{m.label}: {vector(m.point)}</title></g>)}{truth && <path d={`M${x(truth[0]) - 6} ${y(truth[1]) - 6}l12 12m-12 0l12 -12`} stroke="#fff" strokeWidth="2" />}<text x="180" y="342" textAnchor="middle">x coordinate · vertical: y coordinate</text></Diagram>;
}

export function SparseFigure({ kind }) {
  const id = useId();
  if (kind === 'representations') return <><div className="sparse-panels">{['Dense records', 'Selected records', 'Length summaries', 'Feature memory'].map((name, mode) => <Diagram key={name} title={name} height={240} label={`${name}: the same six source records follow different paths to the receiver.`}><Marker id={`${id}-${mode}`} />{Array.from({ length: 6 }, (_, i) => <g key={i}><rect x={13 + i * 57} y="12" width="43" height="28" fill={mode === 1 && ![1, 3, 5].includes(i) ? '#222' : '#4b3920'} stroke="#aaa" /><text x={35 + i * 57} y="31" textAnchor="middle">{i}</text>{mode !== 1 || [1, 3, 5].includes(i) ? <Arrow id={`${id}-${mode}`} from={[35 + i * 57, 41]} to={[mode === 2 ? (i < 3 ? 100 : 260) : 180, mode < 2 ? 158 : 92]} /> : null}</g>)}{mode < 2 ? <Box x={70} y={162} width={220} label="query → normalized read" /> : <><Box x={mode === 2 ? 40 : 70} y={95} width={mode === 2 ? 120 : 220} label={mode === 2 ? 'summary 0' : 'S: 2 × 2; z: 2'} />{mode === 2 && <Box x={200} y={95} width={120} label="summary 1" />}<Arrow id={`${id}-${mode}`} from={[180, 131]} to={[180, 170]} /><Box x={60} y={175} width={240} label="query reads the stored summary" /></>}{mode === 0 && <text x="180" y="226" textAnchor="middle">Tiling changes execution; all six edges remain.</text>}</Diagram>)}</div><SparseMatrix title="One illustrative 2 × 6 length projection (not fitted weights)" rowLabel="summary slot" columnLabel="original position" values={[[1/3,1/3,1/3,0,0,0],[0,0,0,1/3,1/3,1/3]]} /><p>Each summary arrow above follows a nonzero coefficient in this illustrated projection. General learned E and F may mix any positions and need not share coefficients. Feature memory stores a feature-by-value matrix rather than individually addressable records.</p></>;
  if (kind === 'mass') return <><WeightStrip title="Deleting donor 2 renormalizes the retained mass" rows={[[.5, .25, .25], [2 / 3, 1 / 3, 0]]} labels={['all', 'retained']} /><NeuralTable caption="Same scalar values, different normalized contributions" headers={['Donor', 'Value', 'Full contribution', 'Retained contribution']} rows={[[0, 2, 1, '4/3'], [1, -1, '-.25', '-1/3'], [2, 4, 1, 'removed']]} /><p>Output 1.75 → 1. Removed probability mass .25; the separate error bound is 2.00. Setting every value to 2 gives output 2 for both distributions.</p></>;
  if (kind === 'hubs') return <div className="sparse-panels">{[-1, 6, 0].map(hub => <div key={hub}><LayerGraph mask={causalEdges(12, 3, hub)} source={2} target={11} title={hub < 0 ? 'Local only: W=3' : `Causal hub at ${hub}`} /></div>)}</div>;
  if (kind === 'memory') {
    const result = featureMemory([2, 1], [[1, 0], [0, 1], [1, 1]], [[2], [-1], [3]]);
    return <><div className="sparse-panels">{result.history.map((step, i) => <div key={i}><p>Write {i}: key {vector([[1, 0], [0, 1], [1, 1]][i])} × value {[2, -1, 3][i]}</p><SparseMatrix title="Outer product added" values={step.contribution} /><SparseMatrix title="Accumulated S" values={step.matrix} /><p>z = {vector(step.normalizer)}</p></div>)}</div><p>Query [2,1] reads 2×5 + 1×2 = 12, divided by 2×2 + 1×2 = 6: output 2. Histories [1,3] and [2,2] with unit keys both store S=4, z=2; the first original value is no longer recoverable from that state alone.</p></>;
  }
  if (kind === 'random') return <><Diagram title="Kernel estimation precedes normalization" height={330} label="Scaled query and key follow fixed Gaussian projections into positive features, whose products estimate the kernel. A separate row division creates attention weights."><Marker id={id} />{[['x, y: scaled Q and K', 'same fixed Gaussian rows ω'], ['positive feature products', 'exp(ω·x−|x|²/2) exp(ω·y−|y|²/2)'], ['sampled kernel estimate', 'mean across m features'], ['normalized mixture', 'divide by the sum across legal keys']].map(([label, detail], i) => <g key={label}><Box x={5} y={8 + i * 80} width={350} label={label} detail={detail} />{i < 3 && <Arrow id={id} from={[180, 58 + i * 80]} to={[180, 85 + i * 80]} />}</g>)}</Diagram><p>For x=y=1 and m=64, the analytic IID kernel-estimator variance is {f(examples.random_features.iid_variance_x1_y1_m64)}. Gaussian marginal radii give expectation e≈2.71828; fixed-radius ±1 gives exp(−1)cosh(2)≈1.384. Orthogonal directions need independent chi-distributed radii to retain Gaussian row marginals. One shared scalar rescales all key features together; separate per-key scales would change the normalized answer.</p></>;
  if (kind === 'projection') return <ProjectionPaths values={[1, 2, 9]} coefficients={[.5, 0, .5]} position={0} />;
  if (kind === 'nystrom') {
    const data = examples.nystrom_worked;
    return <><Diagram title="Read Nyström factors from the value side" height={285} label="B times V gives a 2 by 1 array. Multiply by the 2 by 2 pseudoinverse, then the 4 by 2 front factor; no 4 by 4 approximate matrix is needed."><Marker id={id} />{[['B: 2 × 4', 'V: 4 × 1 → BV: 2 × 1'], ['A⁺: 2 × 2', 'A⁺(BV): 2 × 1'], ['F: 4 × 2', 'F(A⁺(BV)): 4 × 1']].map(([label, detail], i) => <g key={label}><Box x={30} y={10 + 90 * i} width={300} label={label} detail={detail} />{i < 2 && <Arrow id={id} from={[180, 60 + 90 * i]} to={[180, 98 + 90 * i]} />}</g>)}</Diagram><div className="sparse-panels"><SparseMatrix title="F: full queries read key landmarks" values={data.front} rowLabel="query" columnLabel="landmark" /><SparseMatrix title="A: query landmarks read key landmarks" values={data.middle} rowLabel="landmark" columnLabel="landmark" /><SparseMatrix title="B: query landmarks read all keys" values={data.back} rowLabel="landmark" columnLabel="donor" /></div><NeuralTable caption="Calculated noncausal approximation" headers={['Receiver', 'Nyström output', 'Full softmax output']} rows={data.full_output.map((row, i) => [i, f(data.approximate_output[i][0]), f(row[0])])} /><p>A⁺ and F A⁺ B need not be probability matrices. Seven positions split into three segments of lengths 3,2,2; the ordinary library bridge uses every position, including the trailing segment.</p></>;
  }
  if (kind === 'architectures') return <><Diagram title="NSA · three separately normalized reads" height={345} label="Compressed, selected and window branches each normalize separately, then sigmoid gates weight their output vectors before addition."><Marker id={id} /><Box x={100} y={8} width={160} label="current query" />{['compressed', 'selected', 'window'].map((name, i) => <g key={name}><Arrow id={id} from={[180, 44]} to={[62 + i * 118, 90]} /><Box x={5 + i * 118} y={95} width={114} label={name} detail="own softmax" /><Arrow id={id} from={[62 + i * 118, 145]} to={[62 + i * 118, 180]} /><Box x={5 + i * 118} y={186} width={114} label="× gate" detail="sigmoid scalar" /><Arrow id={id} from={[62 + i * 118, 236]} to={[180, 275]} /></g>)}<Box x={80} y={279} width={200} label="add three output vectors" /><text x="180" y="340" textAnchor="middle">Fixed-stride compression still scans a growing memory.</text></Diagram><Diagram title="V3.2-Exp DSA · selection has its own cost" height={300} label="A lightning indexer scans causal keys, produces top-k indices, then the main MLA query reads selected KV entries. The indexer is not eliminated."><Marker id={id} />{[['lightning indexer', 'full-prefix scores: quadratic over a sequence'], ['Top-k indices', 'selection output, not main values'], ['main MLA selected read', 'O(Lk) main pairs for fixed k']].map(([label, detail], i) => <g key={label}><Box x={3} y={10 + i * 98} width={354} label={label} detail={detail} />{i < 2 && <Arrow id={id} from={[180, 60 + 98 * i]} to={[180, 105 + 98 * i]} />}</g>)}</Diagram><Diagram title="V4.1 CSA2 · memory reuse and index reuse are separate" height={385} width={420} label="Full creates memory and indices; Reindex uses old memory and fresh index query; Reuse uses old memory and old indices. Every mode has a fresh main query and local-window KV."><Marker id={id} />{[['Full', 'new main KV / index K', 'new index Q → Top-k'], ['Reindex', 'shared main KV / index K', 'new index Q → Top-k'], ['Reuse', 'shared main KV', 'shared Top-k; no index Q']].map(([label, memory, index], i) => <g key={label}><text x="8" y={30 + i * 109}>{label}</text><Box x={90} y={8 + i * 109} width={320} label={memory} detail={index} /><Arrow id={id} from={[248, 57 + i * 109]} to={[248, 72 + i * 109]} /><text x="248" y={91 + i * 109} textAnchor="middle">fresh main Q + layer-local window KV → output</text></g>)}<text x="210" y="358" textAnchor="middle">First Full: scan entire causal range → candidate pool.</text><text x="210" y="378" textAnchor="middle">Later Reindex: search that pool. Reuse: no new selection.</text></Diagram><p>Architecture descriptions from the cited primary reports; no production timing is reproduced. Decoder global memory comes from causal encoder output projections, while local-window KV remains layer-specific.</p></>;
  if (kind === 'trajectory') return <><TrajectoryFigure points={examples.sourcePoints.slice(0, 32)} predictions={examples.workedForecasts ?? []} truth={examples.sourcePoints[32]} /><p>The observed path stops at position 31. The cross marks the separately observed next point. Circles, squares and triangles identify dense, window and kernel forecasts.</p></>;
  return null;
}
