import { useState } from 'react';
import { NeuralNumber, NeuralPlot, NeuralSelect, NeuralTable, formatNeural as f } from './NeuralLessonElements.jsx';
import { linearSystem, systemDefault, ssdDefault, ssdOperator } from '../../data/state-space-models.js';
import { StateTrace, StateMatrix, TrajectoryPlot, movementLabels, stateColors } from './StateSpaceLabs.jsx';
import measurements from '../../data/state-space-measurements.json';

function Flow({ title, steps }) {
  return <figure className="ssm-flow"><figcaption>{title}</figcaption><ol>{steps.map(([label, description]) => <li key={label}><strong>{label}</strong><span>{description}</span></li>)}</ol></figure>;
}
export function StatePathsFigure() {
  return <figure className="ssm-state-paths"><figcaption>One time step: two writes into the new state, two contributions to the output</figcaption><div className="ssm-two"><div><h4>Existing memory</h4><p>h previous [N] → Ā [N × N]</p><strong>.5 × 1 = .5</strong></div><div><h4>Current write</h4><p>u [H] → B̄ [N × H]</p><strong>1 × 3 = 3</strong></div></div><div className="ssm-join">Sum → new h [N] = <strong>3.5</strong></div><div className="ssm-two"><div><h4>Read memory</h4><p>h [N] → C [J × N]</p><strong>2 × 3.5 = 7</strong></div><div><h4>Independent direct path</h4><p>u [H] → D [J × H]</p><strong>.25 × 3 = .75</strong></div></div><div className="ssm-join">Sum → y [J] = <strong>7.75</strong>. Direct input is counted once.</div></figure>;
}
export function SamplingFigure() {
  const samples = Array.from({ length: 7 }, (_, i) => i);
  return <figure className="ssm-figure"><figcaption>A = −1, B = 1, Δ = 1: the discretization changes retention and writing</figcaption><div className="ssm-two">{[false, true].map(held => <NeuralPlot key={String(held)} title={held ? 'Held u = 1, initial state 0' : 'Zero input, initial state 1'} xLabel="arbitrary time units" yLabel="state" xDomain={[0, 6]} yDomain={[0, 1]} series={[{ label: 'Continuous / exact ZOH', color: stateColors[0], values: Array.from({ length: 61 }, (_, k) => [k / 10, held ? 1 - Math.exp(-k / 10) : Math.exp(-k / 10)]) }, { label: 'Bilinear samples', color: stateColors[1], dashed: true, values: samples.map(k => [k, held ? 1 - (1 / 3) ** k : (1 / 3) ** k]) }]} points={samples.map(k => ({ x: k, y: held ? 1 - Math.exp(-k) : Math.exp(-k), label: `Exact sample ${k}`, color: stateColors[0] }))} />)}</div><NeuralTable caption="First three decay samples; same initial condition" headers={['Time', 'Exact ZOH', 'Bilinear']} rows={samples.slice(0, 3).map(t => [t, f(Math.exp(-t)), f((1 / 3) ** t)])} /><Flow title="The singular integrator: A = 0 and Δ = .5" steps={[["Start at 3", 'No decay; only accumulated input'], ["u = 2", 'Signed area .5 × 2 = 1 → state 4'], ["u = −1", 'Signed area .5 × −1 = −.5 → state 3.5']]} /></figure>;
}
export function ImpulseFigure() {
  const settings = { ...systemDefault(), inputs: [2, 0, 1, 0] }, result = linearSystem(settings);
  return <figure className="ssm-figure"><figcaption>Each input leaves a fading contribution to later outputs</figcaption><StateMatrix title="Birth row → output column; sum each column" matrix={result.contributions} /><div className="ssm-two"><StateTrace title="Computed kernel taps" series={[{ label: 'Lag-dependent tap', values: result.kernel }]} /><StateTrace title="State coordinates versus output" series={[{ label: 'State 1', values: result.states.map(row => row[0]) }, { label: 'State 2', values: result.states.map(row => row[1]) }, { label: 'Output y', values: result.recurrent }]} /></div><p>Column 2: 2 × .11328125 + 1 × .3125 + .25 × 1 = .7890625. The final term is feedthrough, outside this historical-contribution matrix.</p><Flow title="FFT padding prevents circular wraparound" steps={[["4 input samples", '2, 0, 1, 0'], ["4 kernel taps", '.3125, .203125, .11328125, .0595703125'], ["At least 7 transform slots", 'Pad both; multiply spectra; inverse transform'], ["Keep first 4 causal outputs", 'The tail cannot wrap into output 0']]} /></figure>;
}
export function MemoryRatesFigure() {
  const rates = [.2, .8, .99];
  return <figure className="ssm-figure"><figcaption>One impulse, three decay rates</figcaption><div className="ssm-two">{[100, 8].map(length => <NeuralPlot key={length} title={length === 8 ? 'First eight updates in detail' : 'Longer horizon'} xLabel="empty updates k" yLabel="retained fraction aᵏ" xDomain={[0, length]} yDomain={[0, 1]} series={rates.map((rate, i) => ({ label: `a = ${rate}`, color: stateColors[i], dashed: i === 1, values: Array.from({ length: length + 1 }, (_, k) => [k, rate ** k]) }))} />)}</div><NeuralTable caption="Half-life of one mode" headers={['Decay a', 'Half-life (steps)']} rows={rates.map(rate => [rate, f(Math.log(.5) / Math.log(rate))])} /></figure>;
}
export function OscillatorFigure() {
  const points = Array.from({ length: 49 }, (_, k) => { const t = k * .25; return [Math.exp(-.2 * t) * Math.cos(2 * t), Math.exp(-.2 * t) * Math.sin(2 * t)]; });
  return <figure className="ssm-figure"><figcaption>Rotation plus decay, represented entirely with real coordinates</figcaption><div className="ssm-two"><div className="ssm-oscillator"><svg viewBox="0 0 320 320" role="img" aria-label="Equal-scale phase plane. Starting at (1,0), the state rotates counterclockwise and shrinks."><line x1="35" x2="285" y1="160" y2="160" stroke="#666" /><line x1="160" x2="160" y1="35" y2="285" stroke="#666" /><circle cx="160" cy="160" r="115" fill="none" stroke="#333" strokeDasharray="3 4" /><polyline points={points.map(([x, y]) => `${160 + 115 * x},${160 - 115 * y}`).join(' ')} fill="none" stroke="#e2b55a" strokeWidth="2" />{points.filter((_, i) => i % 4 === 0).map(([x, y], i) => <circle key={i} cx={160 + 115 * x} cy={160 - 115 * y} r="3" fill="#eee"><title>t = {i}; ({f(x)}, {f(y)})</title></circle>)}<text x="280" y="180">x</text><text x="170" y="35">y</text><text x="275" y="145">1</text><text x="40" y="145">−1</text></svg><p>Equal x/y scale. Dots are one time unit apart; each numerical update is Δ = .25.</p></div><StateTrace title="The same pair along its update timeline" series={[{ label: 'Horizontal coordinate', values: points.map(row => row[0]) }, { label: 'Vertical coordinate', values: points.map(row => row[1]) }]} /></div><Flow title="Conjugate readout: c = 1 + 2i, z = 3 − i" steps={[["Multiply c z", '(1 + 2i)(3 − i) = 5 + 5i'], ["Add the conjugate partner", '(5 + 5i) + (5 − 5i)'], ["Real output = 10", '2 Re(cz) = 2(px − qy); the factor 2 remains']]} /></figure>;
}
export function PolynomialFigure() {
  const x = Array.from({ length: 21 }, (_, i) => i / 10);
  return <figure className="ssm-figure"><figcaption>Memory coefficients under the normalized measure ds/2 on [0,2]</figcaption><div className="ssm-two"><NeuralPlot title="Orthonormal basis functions" xLabel="history coordinate s" yLabel="basis value" xDomain={[0, 2]} yDomain={[-2, 2]} series={[{ label: 'Basis 0: 1', color: stateColors[0], values: x.map(s => [s, 1]) }, { label: 'Basis 1: √3(s−1)', color: stateColors[1], values: x.map(s => [s, Math.sqrt(3) * (s - 1)]) }]} /><NeuralPlot title="Reconstruct f(s) = s" xLabel="history coordinate s" yLabel="function value" xDomain={[0, 2]} yDomain={[0, 2]} series={[{ label: 'One coefficient: 1', color: stateColors[1], dashed: true, values: x.map(s => [s, 1]) }, { label: 'Two coefficients: 1+(s−1)=s', color: stateColors[0], values: x.map(s => [s, s]) }]} /></div><p>Coefficients 1 and √3/3 multiply the two bases. The first retains level; the second restores the trend. The two-coefficient reconstruction exactly overlaps this linear history.</p></figure>;
}
export function DplrFigure() {
  const A = Array.from({ length: 4 }, (_, i) => Array.from({ length: 4 }, (_, j) => i === j ? -i - 1 : i > j ? -Math.sqrt((2 * i + 1) * (2 * j + 1)) : 0));
  const normal = A.map((row, i) => row.map((value, j) => value + Math.sqrt(i + .5) * Math.sqrt(j + .5)));
  return <figure className="ssm-figure"><figcaption>Separate the normal part before changing basis</figcaption><StateMatrix title="HiPPO-inspired triangular A, N = 4" matrix={A} /><StateMatrix title="Normal part A + ppᵀ, pₙ = √(n+.5)" matrix={normal} /><Flow title="The correction survives the coordinate change" steps={[["A + ppᵀ", 'Symmetric part = −I/2; normal matrix'], ["Unitary eigenbasis U", 'U* (A + ppᵀ) U = Λ'], ["Original dynamics", 'U* A U = Λ − (U*p)(U*p)*']]} /><p>The eigenbasis belongs to the corrected normal part. The original dynamics still contain a rank-one correction.</p></figure>;
}
export function FixedDelayFigure() {
  return <Flow title="An LTI shift register copies a fixed two-step delay" steps={[["Write current input", 'State cell 1 ← uₜ'], ["Shift old cell 1", 'State cell 2 ← uₜ₋₁'], ["Shift old cell 2 and read", 'State cell 3 ← uₜ₋₂'], ["Input → output", '[2,5,−1,7,0] → [0,0,2,5,−1]']]} />;
}
export function MambaBlockFigure() {
  return <figure className="ssm-figure">
    <figcaption>Mamba-1: the temporal operator sits inside a wider block</figcaption>
    <div className="ssm-join">Input [T,d] → two projections; keep the original input for the residual path</div>
    <div className="ssm-two">
      <Flow title="Feature branch [T,D]" steps={[["Causal depthwise convolution", 'Short local interaction, then SiLU'], ["Generate coefficients", 'B,C: [T,N]; Δ: [T,D]'], ["Selective recurrence", 'State [D,N] → temporal output [T,D]']]} />
      <Flow title="Separate gate branch [T,D]" steps={[["SiLU activation", 'z × sigmoid(z); this gate scales the temporal output, not the retained state']]} />
    </div>
    <div className="ssm-join">↓ Both branches meet here ↓<br /><strong>Temporal output ⊙ activated gate</strong><br />Elementwise [T,D] × [T,D]</div>
    <div className="ssm-join">Output projection: [T,D] → [T,d]<br /><strong>Add the saved input → block output [T,d]</strong></div>
    <p>The small Libras experiment uses the selective recurrence with a shared residual scaffold. It does not include this local convolution or the separate gate branch.</p>
    <Flow title="Affine maps can be grouped without erasing their dependency" steps={[["First map", 'h → .5h + 1'], ["Second map", 'h → .2h + 3'], ["Third map", 'h → .8h − 2'], ["Either parenthesization", 'h → .08h + .56']]} />
  </figure>;
}
export function SSDFigure() {
  const settings = ssdDefault(); settings.values[2] = [1, 2]; settings.chunkSize = 2;
  const result = ssdOperator(settings), chunk = result.chunks[1];
  return <figure className="ssm-figure"><figcaption>A signed influence map, followed by an exact chunk boundary</figcaption><StateMatrix title="Worked four-step influence coefficients" matrix={result.influence} causal /><p>Future entries are absent; negative entries are valid. No row softmax is applied.</p><NeuralTable caption="Second chunk at q = 2" headers={['Step', 'Local vector', 'Incoming memory', 'Output']} rows={chunk.local.map((row, i) => [i + 2, row.map(value => f(value)).join(', '), chunk.incoming[i].map(value => f(value)).join(', '), chunk.total[i].map(value => f(value)).join(', ')])} /><Flow title="Four stages of the chunk computation" steps={[["1. Local outputs", 'Within-chunk coefficient matrix × values'], ["2. Own final write", 'Each chunk summarizes its new inputs'], ["3. Carry the state", 'Decay incoming state and add own write'], ["4. Add incoming read", 'Local output + read of carried state']]} /></figure>;
}
export function RealTrajectoriesFigure() {
  return <figure className="ssm-figure"><figcaption>Actual fitting rows from UCI Libras Movement</figcaption><div className="ssm-three">{measurements.paths.map(row => <TrajectoryPlot key={row.id} title={`Row ${row.id}: ${movementLabels[row.label - 1]}`} points={row.points} />)}</div><p>45 ordered coordinate pairs per row. Source: Dias, Peres and Bíscaro, UCI Libras Movement (CC BY 4.0). First retained fitting row per shown class, without selecting attractive outcomes.</p></figure>;
}
export function TrainingPipelineFigure() {
  return <Flow title="One measured path → one loss → learned updates" steps={[["45 × 2 coordinates", 'Fixed transform 2x−1; input affine projection'], ["45 × 16 features", 'Two blocks: LayerNorm → temporal mixer → GELU → affine + residual'], ["16 pooled features", 'Mean over the 45 time positions'], ["15 logits", 'Learned classifier → softmax'], ["−log p(label)", 'Backpropagate into classifier, projections, writes, reads and decays']]} />;
}
export function LearningEvidenceFigure() {
  const [selected, setSelected] = useState(0), [recall, setRecall] = useState(false);
  const model = measurements.models[selected];
  const confusion = model.confusion.map(row => row.map(value => recall ? value / row.reduce((a, b) => a + b, 0) : value));
  return <figure className="ssm-figure"><figcaption>Recorded learning curves: four predeclared small CPU fits</figcaption><div className="ssm-two">{measurements.models.map(run => <NeuralPlot key={`${run.kind}${run.seed}`} title={`${run.kind}, seed ${run.seed}; selected epoch ${run.selected_epoch}`} xLabel="epoch" yLabel="cross-entropy (nats)" xDomain={[1, 100]} yDomain={[0, Math.max(...run.history.flatMap(row => row.slice(1)))]} series={[{ label: 'Fitting loss before update', color: stateColors[0], values: run.history.map(row => [row[0], row[1]]) }, { label: 'Validation loss after update', color: stateColors[1], dashed: true, values: run.history.map(row => [row[0], row[2]]) }]} points={[{ x: run.selected_epoch, y: run.history[run.selected_epoch - 1][2], label: 'Selected validation checkpoint', color: stateColors[0] }]} />)}</div><p>The optimizer reports fitting loss before each update and validation loss after it. Lines join the actual epoch records. No per-epoch assessment curve was measured.</p><section data-lesson-teaching="" className="lesson-teaching-section"><h4 className="lesson-teaching-section__title">Inspect assessment confusion and exact recorded losses</h4><div className="neural-controls"><NeuralSelect label="Measured run" value={selected} options={measurements.models.map((run, i) => [i, `${run.kind}, seed ${run.seed}`])} onChange={value => setSelected(Number(value))} /><label className="ssm-checkbox"><input type="checkbox" checked={recall} onChange={event => setRecall(event.target.checked)} />Show row-normalized recall</label></div><StateMatrix title={recall ? 'Assessment recall: true class rows / predicted class columns (zero-based)' : 'Assessment counts: true class rows / predicted class columns (zero-based)'} matrix={confusion} /><p>Each assessment class has four examples. One count changes its recall by .25. Class indices above are dataset class IDs minus one.</p><NeuralTable caption="Exact recorded epoch values" headers={['Epoch', 'Fitting loss', 'Validation loss']} rows={model.history.map(row => row.map(value => f(value, 7)))} /></section></figure>;
}
export function CacheCountsFigure() {
  return <figure className="ssm-figure"><figcaption>Specified retained arrays, not timing measurements</figcaption><div className="ssm-two"><div className="ssm-count"><strong>48 KiB</strong><span>12 layers × 64 channels × 16 states × 4 bytes</span><small>Real recurrent state, one sequence</small></div><div className="ssm-count"><strong>12 MiB</strong><span>2 × 12 layers × 4096 tokens × 64 channels × 2 bytes</span><small>Full multi-head K/V cache, one sequence</small></div></div><p>These are formula cards, not area-scaled rectangles. Their ratio is 256; parameters, temporary buffers and convolution caches are excluded.</p></figure>;
}
export function MambaThreeFigure() {
  const [mix, setMix] = useState(.5);
  return <figure className="ssm-figure"><figcaption>Three separate changes: endpoint writes, rotations and write rank</figcaption><div className="ssm-endpoints"><NeuralNumber label="Endpoint mixing λ" value={mix} min={0} max={1} onChange={setMix} /><NeuralTable caption="Exact scalar discrete update: α=.5, Δ=1, B=1" headers={['Old state', 'Previous input write', 'Current input write', 'Total']} rows={[[.5, f((1 - mix) * .5 * 2), f(mix * 6), f(.5 + (1 - mix) + mix * 6)]]} /></div><Flow title="A π rotation for each bit 1, starting at [1,0]" steps={[["Bit 1", 'State [−1,0]; odd parity 1'], ["Bit 0", 'State [−1,0]; odd parity 1'], ["Bit 1", 'State [1,0]; odd parity 0'], ["Bit 1", 'State [−1,0]; odd parity 1']]} /><div className="ssm-two"><StateMatrix title="Rank-one write e₁e₁ᵀ" matrix={[[1, 0], [0, 0]]} /><StateMatrix title="Rank-two write B Xᵀ with B = X = I" matrix={[[1, 0], [0, 1]]} /></div><p>The retained state stays 2 × 2 while one update writes in two independent directions. This arithmetic comparison makes no latency claim.</p></figure>;
}
