import './transfer-intuition.css';

export function ProbeInformationFigure() {
  const points = [[-1, -1, 'same'], [-1, 1, 'different'], [1, -1, 'different'], [1, 1, 'same']];
  return <figure className="transfer-intuition" aria-label="A failed linear probe need not mean the representation lost the answer"><h3>A head can fail for two different reasons</h3><p>Task: decide whether two signs agree. Filled circles mean “same”; hollow squares mean “different.” Reuse the XOR-style geometry from the neuron lesson.</p><div className="transfer-intuition-pair"><div><h4>Keep both coordinates</h4><svg viewBox="0 0 250 240" role="img" aria-label="Opposite corners have the same label, so no straight line separates the two classes"><line x1="30" x2="220" y1="120" y2="120" stroke="#8c8476" /><line x1="125" x2="125" y1="25" y2="215" stroke="#8c8476" />{points.map(([x, y, label]) => <g key={`${x},${y}`}>{label === 'same' ? <circle cx={125 + x * 65} cy={120 - y * 65} r="8" fill="#e4b752" /> : <rect x={117 + x * 65} y={112 - y * 65} width="16" height="16" fill="none" stroke="#dfd8c8" strokeWidth="2" />}<text x={125 + x * 65} y={143 - y * 65} textAnchor="middle">({x}, {y})</text></g>)}</svg><p>A linear decision boundary cannot solve all four rows. A nonlinear head can use the sign of x₁x₂. The information is still present.</p></div><div><h4>Keep only the first coordinate</h4><div className="transfer-collapsed-features">{[-1, 1].map(value => <div key={value}><strong>Feature = {value}</strong><span>● same</span><span>□ different</span><span>Both inputs now coincide.</span></div>)}</div><p>Each feature value must serve conflicting labels. No deterministic head receiving only this feature can distinguish both cases.</p></div></div><figcaption>Constructed four-row example. The two-coordinate problem is a restriction of the head; the one-coordinate problem is lost information. Optimization and regularization can also weaken a measured probe, so its score alone does not identify the cause.</figcaption></figure>;
}

export function AdapterCorrectionFigure() {
  const hidden = Math.tanh(-1);
  return <figure className="transfer-intuition" aria-label="A bottleneck adapter computes a nonlinear correction and adds back the input"><h3>Follow one feature correction through the detour</h3><p>h = (1, 2); down weights D = [1, −1]; up weights U = [.5, −.25]ᵀ; both biases zero. This is an after-initialization example with nonzero up weights.</p><div className="transfer-adapter-trace"><div><strong>Keep the direct route</strong><span>h = (1, 2) ─────────→ add at the end</span></div><div><strong>Measure a difference</strong><span>Dh = 1 − 2 = −1</span></div><div><strong>Apply the nonlinearity</strong><span>tanh(−1) = {hidden.toFixed(6)}</span></div><div><strong>Distribute the correction</strong><span>U tanh(Dh) = ({(.5 * hidden).toFixed(6)}, {(-.25 * hidden).toFixed(6)})</span></div><div><strong>Rejoin the original features</strong><span>h′ = ({(1 + .5 * hidden).toFixed(6)}, {(2 - .25 * hidden).toFixed(6)})</span></div></div><figcaption>The intermediate bottleneck is one number, yet it affects two output coordinates. Doubling h does not generally double the correction because tanh is nonlinear. Unlike a fixed linear LoRA path, this detour cannot generally be absorbed into one constant matrix.</figcaption></figure>;
}

export function LowRankDirectionFigure() {
  const examples = [{ x: [2, 1], measure: 1 }, { x: [0, 2], measure: -2 }, { x: [3, 3], measure: 0 }];
  return <figure className="transfer-intuition" aria-label="Rank one restricts every correction to a common output direction"><h3>One measurement controls one output direction</h3><p>Hold A = [1, −1], B = [1, 2]ᵀ and scale s = 1 fixed. Different inputs change the amount and sign of the correction, but every correction stays on the line through B.</p><div className="transfer-intuition-pair"><svg viewBox="0 0 260 285" role="img" aria-label="Corrections (1,2), (−2,−4) and (0,0) lie on one line"><line x1="20" x2="240" y1="120" y2="120" stroke="#8c8476" /><line x1="140" x2="140" y1="20" y2="260" stroke="#8c8476" /><line x1="75" y1="250" x2="185" y2="30" stroke="#e4b752" strokeDasharray="4 4" /><line x1="140" y1="120" x2="165" y2="70" stroke="#e4b752" strokeWidth="3" /><line x1="140" y1="120" x2="90" y2="220" stroke="#dfd8c8" strokeWidth="3" />{examples.map(({measure}, index) => <g key={index}><circle cx={140 + 25 * measure} cy={120 - 50 * measure} r="5" fill={index === 1 ? '#dfd8c8' : '#e4b752'} /><text x={140 + 25 * measure + 10} y={120 - 50 * measure + 4}>{`(${measure}, ${2 * measure})`}</text></g>)}<text x="16" y="279">Output coordinates · equal unit scales</text></svg><div>{examples.map(example => <p key={example.measure}>x = ({example.x.join(', ')})<br />Ax = {example.measure}<br /><strong>Correction = ({example.measure}, {2 * example.measure})</strong></p>)}</div></div><figcaption>This shows the added correction, not the full output Wx + BAx. The base W can still produce outputs outside this line. Learning B can change the line; a fixed rank-one adapter still offers only one correction direction at a time.</figcaption></figure>;
}
