import { useId, useState } from 'react';
import { NeuralSelect, NeuralTable, NeuralPlot, formatNeural as f } from './NeuralLessonElements.jsx';
import { composeInfluence, gramGeometry, imagePatches, patchProjection, softmax, visionMACs, windowRead } from '../../data/vision-transformer-models.js';
import examples from '../../data/vision-transformer-examples.json';
import './vision-transformer.css';

export const vector = values => `[${values.map(value => f(value, 5)).join(', ')}]`;
export function VisionPlot(props) {
  return <div className="vision-chart-scroll" role="region" tabIndex={0} aria-label={`${props.title}; scroll horizontally if needed`}><NeuralPlot {...props} /></div>;
}
export function VisionGrid({ values, columns, title, selected = -1, onSelect, groups = 0, range = [0, 1], showValues = false, colors = null, marked = [], labels = null }) {
  const display = value => f(value, 3);
  return <figure className="vision-grid-figure"><figcaption>{title}</figcaption><div className="vision-grid" style={{ gridTemplateColumns: `repeat(${columns}, minmax(0,1fr))` }}>
    {values.map((value, i) => {
      const amount = Math.max(0, Math.min(1, (value - range[0]) / (range[1] - range[0])));
      const style = { background: colors?.[i] ?? `rgb(${Array(3).fill(Math.round(18 + 225 * amount)).join(',')})`, color: colors ? '#fff' : amount > .55 ? '#111' : '#eee', borderRightWidth: groups && (i % columns + 1) % groups === 0 ? 3 : 1, borderBottomWidth: groups && (Math.floor(i / columns) + 1) % groups === 0 ? 3 : 1 };
      const content = labels?.[i] ?? (showValues ? display(value) : '');
      const description = `Row ${Math.floor(i / columns)}, column ${i % columns}: ${display(value)}${selected === i ? ', selected' : ''}${marked.includes(i) ? ', highlighted source' : ''}`;
      return onSelect ? <button key={i} type="button" aria-label={description} aria-pressed={selected === i} className={marked.includes(i) ? 'marked' : ''} style={style} onClick={() => onSelect(i)}>{content}</button> : <div key={i} role="img" aria-label={description} className={`${i === selected ? 'selected' : ''} ${marked.includes(i) ? 'marked' : ''}`} style={style} title={description}>{content}</div>;
    })}
  </div><p>{range[0]}–{range[1]} {colors ? 'input values; feature colors use their separate legend' : 'on this fixed color scale'}.</p></figure>;
}
export function VisionMatrix({ values, title, cosine = false }) {
  const maximum = cosine ? 1 : Math.max(1e-12, ...values.flat().map(Math.abs));
  return <figure className="vision-matrix"><figcaption>{title}</figcaption><div className="vision-scroll" role="region" tabIndex={0} aria-label={title}><table><tbody>{values.map((row, i) => <tr key={i}>{row.map((value, j) => <td key={j} style={{ background: value < 0 ? `rgba(131,180,232,${.1 + .35 * Math.abs(value) / maximum})` : `rgba(224,182,96,${.1 + .35 * Math.abs(value) / maximum})` }}>{f(value, 4)}</td>)}</tr>)}</tbody></table></div><p>{cosine ? 'Cosine: −1 blue, 0 neutral, +1 amber; printed values retain sign.' : 'Signed values; rows and columns follow the labelled entities.'}</p></figure>;
}
export function VisionBars({ rows, title, labels, signed = false }) {
  const maximum = signed ? Math.max(1e-12, ...rows.flat().map(Math.abs)) : 1;
  return <figure className="vision-bars"><figcaption>{title} · shared scale {signed ? `±${f(maximum)}` : '0–1'}</figcaption>{rows.map((row, i) => <div key={i}><p>{labels[i]}</p>{row.map((value, j) => <div className="vision-bar-row" key={j}><span>{j}</span><div className={signed ? 'signed' : ''}><i style={{ left: signed ? value < 0 ? `${50 + 50 * value / maximum}%` : '50%' : '0%', width: `${(signed ? 50 : 100) * Math.abs(value) / maximum}%`, background: i ? '#83b4e8' : '#e0b660' }} /></div><output>{f(value, 6)}</output></div>)}</div>)}</figure>;
}
function Diagram({ title, height, width = 360, label, children }) {
  return <figure className="vision-diagram"><figcaption>{title}</figcaption><div className="vision-scroll" tabIndex={0} role="region" aria-label={`${title}; scroll horizontally if needed`}><svg viewBox={`0 0 ${width} ${height}`} style={{ minWidth: width }} role="img" aria-label={label}>{children}</svg></div></figure>;
}
function Marker({ id }) {
  return <defs><marker id={id} viewBox="0 0 8 8" refX="7" refY="4" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L8 4L0 8Z" fill="#e0b660" /></marker></defs>;
}
function Box({ x, y, width = 150, label, detail }) {
  return <g><rect x={x} y={y} width={width} height={detail ? 48 : 34} fill="#242424" stroke="#999" rx="3" /><text x={x + width / 2} y={y + 21} textAnchor="middle">{label}</text>{detail && <text x={x + width / 2} y={y + 39} textAnchor="middle" className="vision-amber">{detail}</text>}</g>;
}
function Arrow({ id, from, to, dashed = false }) {
  return <line x1={from[0]} y1={from[1]} x2={to[0]} y2={to[1]} stroke="#e0b660" strokeDasharray={dashed ? '4 3' : undefined} markerEnd={`url(#${id})`} />;
}
export function FeatureCompass({ vectors, title = 'Feature directions', selected = -1 }) {
  return <Diagram title={title} width={300} height={300} label="Unit feature arrows share an origin; each number identifies the corresponding Gram row and column."><circle cx="150" cy="150" r="107" fill="none" stroke="#666" /><line x1="25" x2="275" y1="150" y2="150" stroke="#555" /><line x1="150" x2="150" y1="25" y2="275" stroke="#555" />{vectors.map((v, i) => <g key={i}><line x1="150" y1="150" x2={150 + 107 * v[0]} y2={150 - 107 * v[1]} stroke={i === selected ? '#e0b660' : '#83b4e8'} strokeWidth={i === selected ? 3 : 1.5} /><circle cx={150 + 107 * v[0]} cy={150 - 107 * v[1]} r="4" fill="#ddd" /><text x={150 + 124 * v[0]} y={155 - 124 * v[1]} textAnchor="middle">{i}</text></g>)}</Diagram>;
}
export function PatchContributionFigure({ pixels, weights, biases }) {
  const id = useId(), result = patchProjection(pixels, weights, biases);
  return <><Diagram title="Each pixel has a signed route into each feature" height={280} label={`Patch ${pixels.join(', ')} projects to ${result.output.join(', ')} using the displayed shared coefficients.`}><Marker id={id} />{pixels.map((pixel, i) => <g key={i}><Box x={5 + i * 89} y={8} width={81} label={`x${i}=${f(pixel)}`} />{weights.map((row, output) => <Arrow key={output} id={id} from={[45 + i * 89, 44]} to={[90 + 180 * output, 117]} />)}</g>)}{result.contributions.map((row, i) => <g key={i}><Box x={5 + 180 * i} y={124} width={170} label={`feature ${i}`} detail={`sum + ${f(biases[i])}`} /><text x={90 + 180 * i} y="199" textAnchor="middle">{row.map(v => f(v)).join(' + ')}</text><Arrow id={id} from={[90 + 180 * i, 208]} to={[90 + 180 * i, 237]} /><text x={90 + 180 * i} y="261" textAnchor="middle">= {f(result.output[i])}</text></g>)}</Diagram><NeuralTable caption="Explicit multiplication preserves coefficient signs" headers={['Pixel index', 'Pixel', 'Feature 0 coefficient', 'Product 0', 'Feature 1 coefficient', 'Product 1']} rows={pixels.map((v, i) => [i, f(v), f(weights[0][i]), f(result.contributions[0][i]), f(weights[1][i]), f(result.contributions[1][i])])} /></>;
}
export function FeatureAtlas({ example, pca = examples.pca, imageTitle = null }) {
  const [patch, setPatch] = useState(5), [mode, setMode] = useState('rgb');
  const projected = example.patch_pca;
  const colors = projected.map(row => mode === 'rgb' ? `rgb(${row.map((v, i) => Math.round(255 * Math.max(0, Math.min(1, (v - pca.training_min[i]) / (pca.training_max[i] - pca.training_min[i]))))).join(',')})` : undefined);
  const axis = mode === 'rgb' ? 0 : Number(mode);
  return <><NeuralSelect label="PCA display coordinates" value={mode} onChange={setMode} options={[['rgb', 'Three fixed principal axes as RGB'], [0, 'PC 0 only'], [1, 'PC 1 only'], [2, 'PC 2 only']]} /><div className="vision-panels"><VisionGrid values={example.image.flat()} columns={8} groups={2} title={imageTitle ?? `Observed test source ${example.source_id} · digit ${example.label}`} /><VisionGrid values={projected.map(row => row[axis])} columns={4} title="Training-basis patch feature coordinates" selected={patch} onSelect={setPatch} colors={mode === 'rgb' ? colors : null} range={mode === 'rgb' ? [pca.training_min[0], pca.training_max[0]] : [pca.training_min[axis], pca.training_max[axis]]} labels={Array.from({ length: 16 }, (_, i) => i)} /><VisionGrid values={example.last_head0_cls_attention.slice(1)} columns={4} title="Layer 2, head 0: CLS reads each patch" range={[0, 1]} selected={patch} onSelect={setPatch} /></div><p>Patch {patch} PCA coordinates {vector(projected[patch])}. These axes explain {f(pca.explained_variance_ratio.reduce((a, b) => a + b, 0) * 100, 3)}% of training variance. Display colors clip to the training minima/maxima; values remain available here. CLS self mass {f(example.last_head0_cls_attention[0], 7)} plus all 16 patch masses sums to one. Neither map is a segmentation mask.</p><VisionBars title="All actual class probabilities" rows={[example.probabilities]} labels={[`Source ${example.source_id}; observed label ${example.label}`]} /></>;
}

export function VisionFigure({ kind }) {
  const id = useId();
  if (kind === 'patches') {
    const image = Array.from({ length: 4 }, (_, row) => Array.from({ length: 4 }, (_, col) => row * 4 + col));
    const patches = imagePatches(image);
    return <><VisionGrid values={image.flat()} columns={4} groups={2} title="Constructed 4 × 4 image · four spatial patches" range={[0, 15]} showValues /><NeuralTable caption="Every flattened scalar retains its original coordinate" headers={['Patch (row,column)', 'Pixel coordinates in order', 'Unfolded row', 'Shared projection result']} rows={patches.map(patch => [`(${patch.row},${patch.column})`, patch.coordinates.map(pair => `(${pair.join(',')})`).join(' '), vector(patch.pixels), vector(patchProjection(patch.pixels, [[1, 0, 0, 1], [0, 1, -1, 0]], [.5, 1]).output)])} /><PatchContributionFigure pixels={patches[0].pixels} weights={[[1,0,0,1],[0,1,-1,0]]} biases={[.5,1]} /><p>224 × 224 RGB → 14 × 14 patches → 196 rows of 768 measured scalars → 196 learned vectors of width d. All patches use the same weight matrix.</p></>;
  }
  if (kind === 'cls') return <><div className="vision-panels"><VisionGrid values={examples.examples[0].image.flat()} columns={8} groups={2} title="Sixteen spatial patches remain one observed image" /><Diagram title="CLS reads token features; the head reads CLS" height={485} label="Sixteen patch embeddings and one separate CLS become seventeen width 32 tokens. Two pre-normalization residual blocks retain token identities, then the normalized CLS goes to a ten-class head."><Marker id={id} />{[['16 patches + nonspatial CLS', 'positions add to 17 × 32 tokens'], ['pre-LN attention + residual', 'weights over 17 donors per receiver'], ['pre-LN FFN + residual', 'same 32→64→32 map at each token'], ['repeat block, then final LN', '17 × 32 contextual features'], ['extract CLS: width 32', 'learned 32→10 class scores'], ['softmax over 10 classes', 'a different domain from donor weights']].map(([label, detail], i) => <g key={label}><Box x={5} y={7 + i * 80} width={350} label={label} detail={detail} />{i < 5 && <Arrow id={id} from={[180, 57 + i * 80]} to={[180, 83 + i * 80]} />}</g>)}</Diagram></div><VisionGrid values={examples.examples[0].last_head0_cls_attention.slice(1)} columns={4} title="Actual source 1: last layer/head 0 CLS-to-patch masses" range={[0, 1]} /><VisionBars title="Actual layer 2, head 0, value coordinate 0: each donor contribution" rows={[examples.clsRead.products]} labels={['Donor 0 is CLS; donors 1–16 are spatial patch slots']} signed /><p>The signed products sum to head coordinate {f(examples.clsRead.output, 8)} before the output projection and residual addition. A large attention coefficient can multiply a negative value.</p><section data-lesson-teaching="" className="lesson-teaching-section"><h4 className="lesson-teaching-section__title">Inspect all 17 coefficient × value products</h4><NeuralTable caption="Native observed CLS weighted read" headers={['Donor', 'Weight', 'Value coordinate 0', 'Product']} rows={examples.clsRead.weights.map((v, i) => [i === 0 ? 'CLS' : `Patch ${i - 1}`, f(v, 7), f(examples.clsRead.values[i], 7), f(examples.clsRead.products[i], 7)])} /></section><p>CLS's own donor mass is {f(examples.examples[0].last_head0_cls_attention[0], 7)}. Keep it in the row total; the spatial grid is not silently renormalized.</p></>;
  if (kind === 'permutation') return <Diagram title="Move the picture alone, or move its location badge too" height={310} label="Content-only swapping patch 5 and patch 6 keeps badges at 5 and 6, changing the located input. A joint swap moves both content and badges, reordering the same token set while CLS stays fixed."><Marker id={id} />{[['Original', 'content A + pos5', 'content B + pos6'], ['Content swap', 'content B + pos5', 'content A + pos6'], ['Joint swap', 'content B + pos6', 'content A + pos5']].map(([label, a, b], i) => <g key={label}><text x="180" y={22 + i * 101} textAnchor="middle">{label}</text><Box x={5} y={32 + i * 101} width={168} label={a} /><Box x={186} y={32 + i * 101} width={168} label={b} />{i < 2 && <><Arrow id={id} from={[89, 68 + i * 101]} to={[271, 128 + i * 101]} dashed /><Arrow id={id} from={[271, 68 + i * 101]} to={[89, 128 + i * 101]} dashed /></>}</g>)}</Diagram>;
  if (kind === 'resolution') return <><div className="vision-panels"><div><p>Two prefix positions stay outside interpolation: [0,1] and [2,3].</p><VisionGrid values={[4, 6, 8, 10, 12, 14]} columns={3} range={[4, 14]} showValues title="Old rectangular spatial positions: 2 × 3, channel 0" /></div><div><p>Bicubic interpolation acts across the spatial grid only.</p><VisionGrid values={examples.mechanisms.position_resize[0].slice(2).map(row => row[0])} columns={4} range={[3, 15]} showValues title="New positions: 3 × 4, channel 0" /></div></div><p>The source table has eight entries of width 2; the target has fourteen. The first two entries are unchanged. The same operation maps a 14 × 14 patch grid to 24 × 24 while retaining CLS separately. Changing patch size also changes the projection input width.</p></>;
  if (kind === 'cost') return <VisionCostFigure />;
  if (kind === 'windows') {
    const values = Array(16).fill(0), first = windowRead(values, 4, 4, 2, 0), second = windowRead(first.output, 4, 4, 2, 1), composed = composeInfluence(second.weights, first.weights), receiver = 5;
    return <><div className="vision-panels"><VisionGrid values={first.weights[receiver]} columns={4} groups={2} title="First layer: F reads A,B,E,F" range={[0,.25]} showValues /><VisionGrid values={second.weights[receiver]} columns={4} title="Second layer: F reads F,G,J,K states" range={[0,.25]} showValues /><VisionGrid values={composed[receiver]} columns={4} title="Composed original contributors: all 16" range={[0,.0625]} showValues /></div><p>The second read consumes four first-layer states, each already containing four original cells. All16 coefficients are 1/16. At corner A, only four original contributors remain reachable at this depth.</p><VisionGrid values={[16,0,0,0]} columns={2} title="Rolled boundary window: distant corners collide in memory" range={[0,16]} labels={['(5,5):16','(5,0):0','(0,5):0','(0,0):0']} /><p>Unmasked mean at(0,0):4. Boundary-masked mean:0. The four original coordinates belong to different clipped regions; rolling storage does not create legal spatial neighbors.</p></>;
  }
  if (kind === 'hierarchy') return <><Diagram title="Patch merging concatenates before learning a reduction" height={310} label="Top-left, bottom-left, top-right and bottom-right tokens concatenate in that order into 4d features; layer normalization precedes a learned 4d-to2d map."><Marker id={id} /><Box x={10} y={8} width={145} label="top left (TL)" /><Box x={200} y={8} width={145} label="top right (TR)" /><Box x={10} y={65} width={145} label="bottom left (BL)" /><Box x={200} y={65} width={145} label="bottom right (BR)" />{[80, 270].map(x => <Arrow key={x} id={id} from={[x, 105]} to={[180, 147]} />)}<Box x={15} y={152} width={330} label="[TL | BL | TR | BR]: width 4d" /><Arrow id={id} from={[180, 188]} to={[180, 225]} /><Box x={15} y={230} width={330} label="LayerNorm 4d → learned linear 4d→2d" /></Diagram><p>56×56×96 → 28×28×192 → 14×14×384 → 7×7×768. Spatial token count quarters; feature width doubles. This does not manufacture extra pixels.</p></>;
  if (kind === 'library') return <NeuralTable caption="Actual Swin V1 library parameter mapping" headers={['Scratch object', 'torchvision object', 'Transformation']} rows={[["qkv", "qkv", "same linear layout"], ["output", "proj", "same weights and bias"], ["relative_bias: head × offset", "relative_position_bias_table: offset × head", "transpose"], ["PatchMerge.norm / reduce", "PatchMerging.norm / reduction", "same V1 ordering"]]} />;
  if (kind === 'deit') return <><Diagram title="Teacher targets go to a loss, not into the student tokens" height={435} label="An image goes to frozen teacher and trainable student. The label supervises CLS; teacher argmax supervises DIST. The teacher branch has no gradient. Deployment keeps the student and both heads."><Marker id={id} /><Box x={110} y={8} width={140} label="same image" /><Arrow id={id} from={[180,44]} to={[80,85]} /><Arrow id={id} from={[180,44]} to={[280,85]} /><Box x={5} y={90} width={150} label="frozen teacher" detail="no gradient update" /><Box x={185} y={90} width={170} label="trainable student" detail="CLS | DIST | patches" /><Arrow id={id} from={[80,140]} to={[80,192]} /><Box x={5} y={198} width={150} label="teacher argmax" /><Arrow id={id} from={[235,140]} to={[220,252]} /><Arrow id={id} from={[300,140]} to={[310,252]} /><Box x={170} y={258} width={87} label="CLS head" /><Box x={265} y={258} width={90} label="DIST head" /><Box x={5} y={295} width={145} label="dataset label" /><Arrow id={id} from={[150,312]} to={[202,348]} /><path d="M80 234 L80 244 L2 244 L2 405 L307 405 L307 393" fill="none" stroke="#e4b752" strokeWidth="1.6" strokeDasharray="5 4" markerEnd={`url(#${id})`} /><Arrow id={id} from={[215,294]} to={[215,348]} /><Arrow id={id} from={[310,294]} to={[310,348]} /><Box x={157} y={353} width={94} label="½ label CE" /><Box x={259} y={353} width={96} label="½ teacher CE" /><text x="180" y="427" textAnchor="middle">Inference: teacher removed; combine the two student heads.</text></Diagram><VisionFusionFigure /></>;
  if (kind === 'dino') return <><Diagram title="Different crops compare across views" height={415} label="Teacher view A targets student view B; teacher view B targets student view A. Identical-view comparisons are excluded. Teacher parameter EMA and running prototype center update separately."><Marker id={id} />{[0,1].map(i => <g key={i}><rect x={35+i*190} y="8" width="95" height="85" fill="#303030" stroke="#aaa" /><rect x={46+i*190} y={20+i*15} width="64" height="43" fill="#756448" stroke="#e0b660" /><text x={82+i*190} y="83" textAnchor="middle">crop {i?'B':'A'}</text><Box x={5+i*190} y={122} width={165} label={`teacher ${i?'B':'A'}`} detail="center / τt / detach" /><Box x={5+i*190} y={258} width={165} label={`student ${i?'B':'A'}`} detail="softmax with τs" /></g>)}<Arrow id={id} from={[87,172]} to={[277,252]} /><Arrow id={id} from={[277,172]} to={[87,252]} /><text x="180" y="221" textAnchor="middle">cross-view targets</text><Box x={5} y={345} width={350} label="teacher parameter: .9×2 + .1×4 = 2.2" detail="center: separate EMA of batch teacher logits" /></Diagram><VisionBars title="Worked teacher target and student distribution" rows={[examples.mechanisms.dino_worked.target, examples.mechanisms.dino_worked.student]} labels={['teacher target','student']} /><p>Worked gradient {vector(examples.mechanisms.dino_worked.gradient)}; loss {f(examples.mechanisms.dino_worked.loss, 7)} nats. Equal logits produce uniform distributions and zero gradient: agreement alone cannot certify useful features.</p></>;
  if (kind === 'dinov2') return <><div className="vision-panels"><VisionGrid values={[1,.3,.6,.8]} columns={2} selected={2} title="Teacher sees the corresponding patch" range={[0,1]} showValues /><VisionGrid values={[1,.3,0,.8]} columns={2} selected={2} title="Student sees a mask at that location" range={[0,1]} labels={['visible','visible','MASK','visible']} /></div><Diagram title="Two objectives use different heads" height={265} label="CLS features pass through an image prototype head and cross-view objective. Spatial patch features pass through a separate patch head and masked correspondence objective."><Marker id={id} /><Box x={5} y={8} width={350} label="shared backbone features" /><Arrow id={id} from={[180,44]} to={[88,95]} /><Arrow id={id} from={[180,44]} to={[272,95]} /><Box x={5} y={100} width={166} label="CLS → image head" detail="cross-view targets" /><Box x={185} y={100} width={170} label="patch → patch head" detail="masked-location targets" /><text x="180" y="200" textAnchor="middle">Assignment balancing acts across a batch of prototypes.</text><text x="180" y="225" textAnchor="middle">KoLeo spreads normalized image feature vectors.</text><text x="180" y="250" textAnchor="middle">Neither operation supplies human class labels.</text></Diagram></>;
  if (kind === 'gram') {
    const original = gramGeometry([0,90],[0,90]), rotated = gramGeometry([90,180],[0,90]), collapsed = gramGeometry([0,0],[0,90]);
    return <><div className="vision-panels">{[['original',original],['common 90° rotation',rotated],['collapsed',collapsed]].map(([name,data]) => <div key={name}><FeatureCompass vectors={data.vectors} title={name} /><VisionMatrix title={`Gram; difference ${f(data.loss)}`} values={data.gram} cosine /></div>)}</div><p>Constructed geometry, not measured DINOv3 embeddings. A common rotation preserves pairwise dot products; collapse changes the summed squared difference to 2.</p><div className="vision-token-layout"><span>CLS</span>{[0,1,2,3].map(i=><span key={i}>register {i}</span>)}<strong>spatial patches → 2D feature grid</strong></div><p>Registers are nonspatial learned working tokens. Four is an example choice; only the patch segment is reshaped into the image grid.</p></>;
  }
  if (kind === 'results') return <VisionResultsFigure />;
  if (kind === 'atlas') return <VisionAtlasFigure />;
  return null;
}
function VisionFusionFigure() {
  const first = [-3,-2,0], second = [2,3,0], averaged = first.map((v,i)=>(v+second[i])/2), probabilities = softmax(first).map((v,i)=>(v+softmax(second)[i])/2);
  return <><NeuralTable caption="Same two heads, different operation order" headers={['Route','Intermediate','Selected class']} rows={[["mean logits → softmax",vector(averaged),1],["softmax each → mean probabilities",vector(probabilities),2]]} /><VisionBars title="Two fusion rules give different class probabilities" rows={[softmax(averaged),probabilities]} labels={['released code: mean logits first','paper description: mean probabilities']} /></>;
}
function VisionCostFigure() {
  const [extended,setExtended]=useState(false), sides=extended?[224,384,512,1024]:[224,384,512], results=sides.map(side=>visionMACs(side,side));
  return <><label><input type="checkbox" checked={extended} onChange={e=>setExtended(e.target.checked)} />Extend the calculated range to 1024 pixels</label><VisionPlot title="Calculated matmul work per block" xLabel="image side, pixels" yLabel="billions of MACs" xDomain={[224,extended?1024:512]} yDomain={[0,extended?27:5]} series={['projection','ffn','pairs'].map((key,i)=>({label:key,color:['#e0b660','#83b4e8','#ddd'][i],values:results.map((result,j)=>[sides[j],result[key]/1e9])}))} /><NeuralTable caption="Derived counts, not measured throughput" headers={['Side','Tokens','Projection / block','FFN / block','Pairs / block','Whole model']} rows={results.map((row,i)=>[sides[i],row.sequence,...['projection','ffn','pairs','total'].map(key=>`${f(row[key]/1e9,5)} billion`)])} /><p>At 224, pair work is {f(visionMACs(224,224).pairFraction*100,2)}% of the block's matmul MACs. One MAC is one multiply–accumulate; normalization, softmax, activation and memory traffic are excluded. Lines connect calculated settings only.</p></>;
}
function VisionResultsFigure() {
  const [model,setModel]=useState('vit'), record=examples.study[model];
  return <><div className="vision-panels"><VisionPlot title="Recorded correct test classifications" xLabel="0 CNN,1 ViT,2 distilled" yLabel="correct out of 1797" xDomain={[-.2,2.2]} yDomain={[0,1797]} series={[]} points={[1723,1630,1658].map((y,x)=>({x,y,label:`${y}/1797`}))} /><VisionPlot title="Recorded test cross-entropy" xLabel="0 CNN,1 ViT,2 distilled" yLabel="nats per image" xDomain={[-.2,2.2]} yDomain={[0,.45]} series={[]} points={[.135869801,.3815183043,.3075848818].map((y,x)=>({x,y,label:f(y,8)}))} /></div><NeuralSelect label="Inspect recorded validation trace" value={model} onChange={setModel} options={['cnn','vit','distilled'].map(name=>[name,name])} /><VisionPlot title={`${model}: observed validation checkpoints`} xLabel="AdamW update" yLabel="validation cross-entropy, nats" xDomain={[0,600]} yDomain={[0,Math.max(...record.trace.map(row=>row.cross_entropy))*1.1]} series={[{label:'13 recorded validation values',color:'#e0b660',values:record.trace.map(row=>[row.step,row.cross_entropy])}]} points={[{x:record.chosen_step,y:record.trace.find(row=>row.step===record.chosen_step).cross_entropy,label:`Selected update ${record.chosen_step}`,selected:true}]} /><p>Checkpoint {record.chosen_step} minimizes validation cross-entropy among the measured steps. No test curve or repeated-seed uncertainty was measured.</p></>;
}
function VisionAtlasFigure() {
  const [source,setSource]=useState(2), example=examples.examples[source];
  return <><NeuralSelect label="Actual test specimen for the feature atlas" value={source} onChange={v=>setSource(Number(v))} options={examples.examples.map((row,i)=>[i,`Test source ${row.source_id} · digit ${row.label}`])} /><FeatureAtlas example={example} /><VisionMatchingFigure /><div className="vision-panels"><VisionGrid values={examples.examples[0].image.flat()} columns={8} groups={2} title="Query: source 1, patch 5" marked={[18,19,26,27]} /><VisionGrid values={examples.matching.all_cosines} columns={4} range={[-1,1]} title="Source2 patch cosine similarities to source 1 patch 5" showValues marked={examples.matching.top_patch_ids} /></div><p>Source1 patch 5 → source 2 patches {examples.matching.top_patch_ids.join(', ')}: {vector(examples.matching.cosines)}. The best available match is not proof of a meaningful correspondence between these different digits.</p></>;
}
function VisionMatchingFigure() {
  const id = useId();
  return <Diagram title="The three nearest features point to actual image regions" height={201} label="Observed digit zero source one patch five connects to the three closest patch features in observed digit one source two: patch ten, patch two and patch fourteen, all with cosine below 0.37."><Marker id={id} />{[0,1].map(image => <g key={image}><text x={68+image*220} y="20" textAnchor="middle">source {image+1}</text>{examples.examples[image].image.flat().map((v,i)=><rect key={i} x={20+image*220+i%8*12} y={40+Math.floor(i/8)*12} width="12" height="12" fill={`rgb(${Array(3).fill(Math.round(v*255)).join(',')})`} stroke="#777" strokeWidth=".3" />)}</g>)}<rect x="44" y="64" width="24" height="24" fill="none" stroke="#e0b660" strokeWidth="2" />{examples.matching.top_patch_ids.map((patch,i)=><g key={patch}><rect x={240+patch%4*24} y={40+Math.floor(patch/4)*24} width="24" height="24" fill="none" stroke="#83b4e8" strokeWidth="2" /><Arrow id={id} from={[69,76]} to={[238+patch%4*24,52+Math.floor(patch/4)*24]} dashed /><text x="180" y={157+i*16} textAnchor="middle">patch {patch}: cosine {f(examples.matching.cosines[i],5)}</text></g>)}</Diagram>;
}
