import { Code, H3, Prose } from '../content';
import MechanismProgram from './MechanismProgram.jsx';
import output from '../../data/weighted-graph-library-output.json';

export default function WeightedGraphLibraryBridge() {
  return <section id="weighted-graph-library-bridge" data-implementation-depth="weighted-graph">
    <H3>Ask the maintained solver the same question</H3>
    <Prose>Reuse the <a href="/learn/topic/graphs-representations-bfs-dfs#graph-library-bridge">earlier graph construction bridge</a>: declare all vertices, choose direction, then attach attributes. Here an edge occurrence has an integer <Code>weight</Code> and its original edge ID becomes a multigraph key. This preserves parallel edges. Dijkstra chooses the cheapest usable occurrence; a spanning forest is a separate undirected problem.</Prose>
    <Prose>With NetworkX 3.6.1 installed, save <a href="/learn-assets/shortest-paths-spanning-trees-topological-ordering/weighted_graph_mechanisms.py" download>weighted_graph_mechanisms.py</a> beside the comparison and run <Code>python weighted_graph_library.py</Code>. It imports the exact earlier Dijkstra, Bellman–Ford, Kruskal and Kahn implementations. Explicit <Code>weight='weight'</Code> avoids accidentally comparing edge count with total cost. All fixtures supply every edge's weight.</Prose>
    <MechanismProgram source="/learn-assets/shortest-paths-spanning-trees-topological-ordering/weighted_graph_library.py" title="Compare routes, forests and dependency orders" output={output['weighted_graph_library.py']} />
    <Prose>The nonnegative route has distances [0, 2, 1, 4, 7, infinity]; vertex 5 is preserved but unreachable. The signed case uses Bellman–Ford. A reachable negative cycle makes this NetworkX API raise <Code>NetworkXUnbounded</Code>, while our richer local contract marks each affected destination with negative infinity. Those are intentional differences in output, not a numerical disagreement. A minimum forest may choose different tied edges: compare its weight, acyclicity and connected components, then validate the selected-edge witness rather than requiring identical IDs.</Prose>
    <Prose>Python's <Code>graphlib.TopologicalSorter</Code> is the ordinary standard-library route for dependencies. Its input maps each node to <em>predecessors</em>, the reverse of an outgoing adjacency list. Both returned orders must contain each vertex once and place every prerequisite first; the program also exercises <Code>CycleError</Code>. For a ready-work executor, its prepare/get_ready/done interface additionally distinguishes ready from completed work. Topological ordering still does not solve a finite-worker scheduling optimization.</Prose>
    <Prose>The earlier costs remain meaningful: lazy-heap Dijkstra can retain O(E) entries and takes O((V + E) log(V + E)); layered Bellman–Ford is O(VE), Kruskal sorts edges in O(E log E), and topological processing is O(V + E), under constant-cost integer operations. Repeated source queries, signed DAG relaxation, edge budgets and critical-chain reconstruction should reuse their already-derived local routines when those are the actual task. These API checks establish matched results, not a benchmark or an assertion that all solvers use identical internal state. Consult <a href="https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.tree.mst.minimum_spanning_tree.html" target="_blank" rel="noopener noreferrer">NetworkX's forest contract</a> and <a href="https://docs.python.org/3/library/graphlib.html" target="_blank" rel="noopener noreferrer">graphlib's dependency protocol</a>.</Prose>
    <H3>Transfer: preserve a new, cheaper parallel route</H3>
    <Prose>Add another edge 0→1 with weight 0. Implement a comparison that validates a real route to every reachable target. Then change that new weight to −1 and choose the appropriate solver. Keep the isolated vertex.</Prose>
    <details><summary>Optional hint</summary><Prose>Retain the edge occurrence instead of overwriting another weight. With a node-only library path, recover its cost by taking the minimum parallel weight for each consecutive node pair.</Prose></details>
    <details><summary>Solution and reasoning</summary><Prose>The zero-weight case gives [0, 0, 1, 2, 5, infinity]. The −1 case gives [0, −1, 1, 1, 4, infinity] and requires Bellman–Ford under the general signed-graph contract. Confirm each witness starts at 0, follows directed edges and sums to its reported distance. Our scratch witness also carries edge IDs, so it can identify the chosen occurrence directly. No returned finite route should be invented for vertex 5.</Prose></details>
  </section>;
}
