import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

export const articleSlugPattern = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
const reservedNames = /^(con|prn|aux|nul|com[1-9]|lpt[1-9])$/i;
export function validateSlug(slug) {
  if (!articleSlugPattern.test(slug) || reservedNames.test(slug)) throw new Error(`Invalid article slug: ${slug}`);
}

function validDate(value) {
  return typeof value === "string" && /^\d{4}-\d{2}-\d{2}$/.test(value) &&
    Number.isFinite(Date.parse(value)) && new Date(value).toISOString().slice(0, 10) === value;
}

export async function readArticles(repositoryRoot) {
  const contentRoot = path.join(repositoryRoot, "content/articles");
  const entries = await readdir(contentRoot, { withFileTypes: true });
  const articles = [];
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    if (entry.isSymbolicLink()) throw new Error(`Article source must not be a symbolic link: ${entry.name}`);
    if (!entry.isDirectory()) continue;
    const slug = entry.name;
    validateSlug(slug);
    const directory = path.join(contentRoot, slug);
    try {
      const metadata = JSON.parse(await readFile(path.join(directory, "metadata.json"), "utf8"));
      const body = await readFile(path.join(directory, "body.md"), "utf8");
      if (!metadata || Array.isArray(metadata) || typeof metadata !== "object") throw new Error("metadata must be an object");
      const allowedFields = new Set(["title", "summary", "status", "publishedAt", "updatedAt", "tags", "author"]);
      for (const key of Object.keys(metadata)) if (!allowedFields.has(key)) throw new Error(`Unknown metadata field: ${key}`);
      for (const key of ["title", "summary"]) if (typeof metadata[key] !== "string" || !metadata[key].trim()) throw new Error(`${key} must be nonempty text`);
      if (!["draft", "published"].includes(metadata.status)) throw new Error("status must be draft or published");
      if (!Array.isArray(metadata.tags) || metadata.tags.some(tag => typeof tag !== "string" || !tag.trim())) throw new Error("tags must be an array of nonempty strings");
      if (new Set(metadata.tags.map(tag => tag.trim().toLowerCase())).size !== metadata.tags.length) throw new Error("tags must be unique");
      if (metadata.author !== undefined && (typeof metadata.author !== "string" || !metadata.author.trim())) throw new Error("author must be nonempty text");
      for (const field of ["publishedAt", "updatedAt"]) {
        if (metadata[field] !== undefined && !validDate(metadata[field])) throw new Error(`${field} must be a real YYYY-MM-DD date`);
      }
      if (metadata.updatedAt && (!metadata.publishedAt || metadata.updatedAt < metadata.publishedAt)) throw new Error("updatedAt requires publishedAt and cannot precede it");
      if (metadata.status === "published") {
        if (!metadata.publishedAt) throw new Error("Published articles require publishedAt");
        if (!body.trim()) throw new Error("Published articles require a nonempty body.md");
        articles.push({
          slug, title: metadata.title.trim(), summary: metadata.summary.trim(),
          publishedAt: metadata.publishedAt, ...(metadata.updatedAt ? { updatedAt: metadata.updatedAt } : {}),
          tags: metadata.tags.map(tag => tag.trim()), author: metadata.author?.trim() || "Ronak Sharma",
          readingMinutes: Math.max(1, Math.ceil(body.trim().split(/\s+/u).length / 220)),
        });
      }
    } catch (error) {
      throw new Error(`Article ${slug}: ${error.message}`, { cause: error });
    }
  }
  return articles.sort((a, b) => b.publishedAt.localeCompare(a.publishedAt) || a.slug.localeCompare(b.slug));
}

async function writeChanged(file, value) {
  let existing;
  try { existing = await readFile(file, "utf8"); } catch (error) { if (error.code !== "ENOENT") throw error; }
  if (existing !== value) await writeFile(file, value, "utf8");
}

export async function generateArticles(repositoryRoot) {
  const articles = await readArticles(repositoryRoot);
  const output = path.join(repositoryRoot, "src/articles/generated");
  await mkdir(output, { recursive: true });
  const header = "// Generated by scripts/generate-articles.mjs. Edit content/articles instead.\n";
  await writeChanged(path.join(output, "catalogue.js"), `${header}export const articles = ${JSON.stringify(articles, null, 2)};\n`);
  // Explicit imports exclude draft bodies from the entire production graph, not just the index.
  const loaders = articles.map(article => `  ${JSON.stringify(article.slug)}: () => import(${JSON.stringify(`../../../content/articles/${article.slug}/body.md?raw`)}).then(module => module.default),`);
  await writeChanged(path.join(output, "loaders.js"), `${header}export const articleLoaders = {\n${loaders.join("\n")}\n};\n`);
  return articles;
}

export async function createArticle(repositoryRoot, slug, title) {
  validateSlug(slug);
  if (typeof title !== "string" || !title.trim()) throw new Error("Provide a nonempty title");
  const directory = path.join(repositoryRoot, "content/articles", slug);
  // Nonrecursive mkdir deliberately refuses to overwrite an existing article.
  await mkdir(directory);
  await writeFile(path.join(directory, "metadata.json"), JSON.stringify({ title: title.trim(), summary: "Describe the question this article answers.", status: "draft", tags: [] }, null, 2) + "\n");
  await writeFile(path.join(directory, "body.md"), "Begin with the question, observation, or argument. The page title comes from metadata.json.\n\n## The idea\n\nDevelop the explanation here, with evidence and examples where useful.\n\n## References\n\nAdd direct, annotated sources where claims need support.\n");
  return directory;
}
