# Generated by scripts/build-dsa-library-bridges.mjs
# Owner: src/learn/data/network-flow-examples.js; examples: augment, matching
# Rebuild; do not maintain a second hand-edited implementation here.

from collections import deque

def validate_edges(n, edges):
    if type(n) is not int or n < 2:
        raise ValueError("At least two vertices are required")
    for edge in edges:
        if len(edge) != 3:
            raise ValueError("An edge is (from, to, capacity)")
        u, v, capacity = edge
        if any(type(x) is not int for x in edge):
            raise ValueError("Use integer vertices and capacities")
        if not (0 <= u < n and 0 <= v < n and capacity >= 0):
            raise ValueError("Invalid vertex or negative capacity")

class ResidualNetwork:
    def __init__(self, n, edges):
        self.edges = list(edges)
        validate_edges(n, self.edges)
        self.n = n
        self.adj = [[] for _ in range(n)]
        self.tail, self.to, self.remaining = [], [], []
        for u, v, capacity in self.edges:
            forward = len(self.to)
            self.tail.extend((u, v))
            self.to.extend((v, u))
            self.remaining.extend((capacity, 0))
            self.adj[u].append(forward)
            self.adj[v].append(forward + 1)

    def check_terminals(self, source, sink):
        if (type(source) is not int or type(sink) is not int
                or not 0 <= source < self.n or not 0 <= sink < self.n
                or source == sink):
            raise ValueError("Choose distinct valid source and sink")

    def search(self, source):
        # A dictionary avoids clearing all isolated vertices at every search.
        parent = {source: None}
        distance = {source: 0}
        queue = deque([source])
        while queue:
            u = queue.popleft()
            for arc in self.adj[u]:
                v = self.to[arc]
                if self.remaining[arc] > 0 and v not in parent:
                    parent[v] = arc
                    distance[v] = distance[u] + 1
                    queue.append(v)
        return parent, distance

    def send(self, arc, amount):
        self.remaining[arc] -= amount
        self.remaining[arc ^ 1] += amount

    def result(self, source, value, steps):
        parent, _ = self.search(source)
        side = set(parent)
        flows = [capacity - self.remaining[2 * i]
                 for i, (_, _, capacity) in enumerate(self.edges)]
        cut_edges = [i for i, (u, v, _) in enumerate(self.edges)
                     if u in side and v not in side]
        return {"value": value, "flows": flows, "source_side": sorted(side),
                "cut_edges": cut_edges,
                "cut_capacity": sum(self.edges[i][2] for i in cut_edges),
                "steps": steps}

def edmonds_karp(n, edges, source, sink, trace=False):
    network = ResidualNetwork(n, edges)
    network.check_terminals(source, sink)
    value, steps = 0, []
    while True:
        parent, _ = network.search(source)
        if sink not in parent:
            return network.result(source, value, steps)
        path = []
        vertex = sink
        while vertex != source:
            arc = parent[vertex]
            path.append(arc)
            vertex = network.tail[arc]
        path.reverse()
        amount = min(network.remaining[arc] for arc in path)
        for arc in path:
            network.send(arc, amount)
        value += amount
        if trace:
            steps.append({"delta": amount,
                          "arcs": [(arc // 2, 1 if arc % 2 == 0 else -1)
                                   for arc in path]})

def bipartite_matching(left_count, right_count, pairs):
    if (type(left_count) is not int or type(right_count) is not int
            or left_count < 0 or right_count < 0):
        raise ValueError("Partition sizes must be nonnegative integers")
    pairs = list(pairs)
    for left, right in pairs:
        if (type(left) is not int or type(right) is not int
                or not 0 <= left < left_count or not 0 <= right < right_count):
            raise ValueError("Pair outside its partition")
    pairs = list(dict.fromkeys(pairs))
    source, sink = left_count + right_count, left_count + right_count + 1
    edges = [(source, left, 1) for left in range(left_count)]
    pair_offset = len(edges)
    edges.extend((left, left_count + right, 1) for left, right in pairs)
    edges.extend((left_count + right, sink, 1) for right in range(right_count))
    flow = edmonds_karp(sink + 1, edges, source, sink)
    matching = [pair for i, pair in enumerate(pairs)
                if flow["flows"][pair_offset + i] == 1]
    left_mate = dict(matching)
    right_mate = {right: left for left, right in matching}
    neighbors = [[] for _ in range(left_count)]
    for left, right in pairs:
        neighbors[left].append(right)
    seen_left = set(range(left_count)) - left_mate.keys()
    seen_right = set()
    queue = deque(sorted(seen_left))
    while queue:
        left = queue.popleft()
        for right in neighbors[left]:
            if left_mate.get(left) == right or right in seen_right:
                continue
            seen_right.add(right)
            # A reached unmatched right would give an augmenting path.
            assert right in right_mate
            mate = right_mate[right]
            if mate not in seen_left:
                seen_left.add(mate)
                queue.append(mate)
    return {"matching": matching,
            "cover_left": sorted(set(range(left_count)) - seen_left),
            "cover_right": sorted(seen_right),
            "shortage_left": sorted(seen_left),
            "shortage_neighbors": sorted(seen_right)}
