# Generated by scripts/build-dsa-library-bridges.mjs
# Owner: src/learn/data/computational-geometry-examples.js; examples: monotoneHull, polygonQuery
# Rebuild; do not maintain a second hand-edited implementation here.

def orient(a, b, c):
    """Doubled signed area; this lesson's contract is integer coordinate pairs."""
    return ((b[0] - a[0]) * (c[1] - a[1])
            - (b[1] - a[1]) * (c[0] - a[0]))

def on_segment(a, b, query):
    return (orient(a, b, query) == 0
            and min(a[0], b[0]) <= query[0] <= max(a[0], b[0])
            and min(a[1], b[1]) <= query[1] <= max(a[1], b[1]))

def convex_hull(points, include_boundary=False):
    points = sorted(set(map(tuple, points)))
    if len(points) <= 1:
        return points
    if all(orient(points[0], points[-1], p) == 0 for p in points):
        return points if include_boundary else [points[0], points[-1]]

    def chain(sequence):
        result = []
        for candidate in sequence:
            while len(result) >= 2:
                turn = orient(result[-2], result[-1], candidate)
                keep_turn = turn >= 0 if include_boundary else turn > 0
                if keep_turn:
                    break
                result.pop()
            result.append(candidate)
        return result

    lower = chain(points)
    upper = chain(reversed(points))
    return lower[:-1] + upper[:-1]

def signed_area_twice(vertices):
    return sum(a[0]*b[1] - a[1]*b[0]
               for a, b in zip(vertices, vertices[1:] + vertices[:1]))

def locate(vertices, query):
    """Simple polygon, at least three vertices; boundary is a separate result."""
    crossings = 0
    for a, b in zip(vertices, vertices[1:] + vertices[:1]):
        if on_segment(a, b, query):
            return "boundary"
        if (a[1] > query[1]) != (b[1] > query[1]):
            determinant = orient(a, b, query)
            to_right = determinant > 0 if b[1] > a[1] else determinant < 0
            crossings += to_right
    return "inside" if crossings % 2 else "outside"

from fractions import Fraction
