"""Create complete standalone programs; capture their actual, deterministic stdout."""

from pathlib import Path
import ast
import contextlib
import io
import json
import textwrap

import black

ROOT = Path(__file__).resolve().parents[1]
examples = []


def add(identifier, title, question, code):
    source = textwrap.dedent(code).strip() + "\n"
    formatted = black.format_str(source, mode=black.Mode(line_length=80))
    assert ast.dump(ast.parse(source)) == ast.dump(ast.parse(formatted))
    output = io.StringIO()
    with contextlib.redirect_stdout(output):
        exec(compile(formatted, identifier, "exec"), {})
    examples.append({"id": identifier, "title": title, "question": question,
                     "code": formatted, "expected": output.getvalue().strip(),
                     "environment": "Python 3.12; standard library"})


GROUP = '''
NAMES = ["e", "r", "r^2", "r^3", "s", "rs", "r^2s", "r^3s"]
G = range(8)

def compose(g, h):
    # gh means apply h first, then g. Encode r^k s^b by k+4b.
    k, b = g % 4, g // 4
    l, c = h % 4, h // 4
    return (k + (-1)**b * l) % 4 + 4*(b ^ c)

def image(g, i):
    return (g % 4 + (-1)**(g // 4)*i) % 4

def inverse(g):
    return next(h for h in G if compose(g, h) == compose(h, g) == 0)

def move(g, values):
    if len(values) != 4:
        raise ValueError("Supply all four vertex values")
    result = [None]*4
    for i, value in enumerate(values):
        result[image(g, i)] = value
    return tuple(result)
'''

add("composition", "Track a label through both orders", "Starting at vertex 1, do rs and sr finish at the same vertex?", GROUP + '''
g, h, vertex = 1, 4, 1
for outer, inner in [(g,h), (h,g)]:
    product = compose(outer,inner)
    print(NAMES[product], "path:", [vertex,image(inner,vertex),image(product,vertex)])
    print("labels at positions 0..3:", " ".join(move(product,"ABCD")))
    print("inverse:",NAMES[inverse(product)])
''')

add("laws", "Identify all square symmetries and check the finite laws", "Why does preserving distances select only eight of the 24 vertex permutations?", GROUP + '''
from itertools import permutations, product
vertices = [(1,0),(0,1),(-1,0),(0,-1)]
def distance_squared(i,j):
    return sum((a-b)**2 for a,b in zip(vertices[i],vertices[j]))
symmetries = [p for p in permutations(range(4)) if all(
    distance_squared(i,j) == distance_squared(p[i],p[j])
    for i,j in product(range(4),repeat=2))]
encoded = {tuple(image(g,i) for i in range(4)) for g in G}
print("distance-preserving permutations:",len(symmetries))
print("same as encoded maps:",set(symmetries)==encoded)
print("associative triples:",sum(compose(compose(g,h),k)==compose(g,compose(h,k))
    for g,h,k in product(G,repeat=3)))
print("two-sided inverse pairs:",sum(compose(g,inverse(g))==compose(inverse(g),g)==0 for g in G))
print("noncommuting witness:",NAMES[compose(1,4)],"!=",NAMES[compose(4,1)])
''')

COSETS = '''
def left_coset(g,H):
    return frozenset(compose(g,h) for h in H)

def cosets(H):
    result=[]
    for g in G:
        value=left_coset(g,H)
        if value not in result:
            result.append(value)
    return result

def names(values):
    return "{"+", ".join(NAMES[g] for g in sorted(values))+"}"
'''

add("subgroups", "Generate a subgroup and partition the group", "What subgroup is generated by a half-turn, and how many translated copies fit in D4?", GROUP + COSETS + '''
def generated(generators):
    found={0}
    frontier=[0]
    while frontier:
        current=frontier.pop()
        for g in generators:
            value=compose(g,current)
            if value not in found:
                found.add(value)
                frontier.append(value)
    return found

H=generated([2])
print("generated by r^2:",names(H))
print("left cosets:"," | ".join(names(c) for c in cosets(H)))
print("group size:",len(cosets(H)),"*",len(H),"=",len(G))
print("generated by r and s:",names(generated([1,4])))
''')

add("orbits", "Count colorings two independent ways", "With three named colors, does allowing reflection merge any rotation-only classes?", GROUP + '''
from itertools import product

def orbits(q,group):
    unseen=set(product(range(q),repeat=4))
    result=[]
    while unseen:
        state=min(unseen)
        orbit={move(g,state) for g in group}
        result.append(orbit)
        unseen.difference_update(orbit)
    return result

def cycle_count(g):
    unseen=set(range(4))
    count=0
    while unseen:
        start=min(unseen)
        current=start
        while current in unseen:
            unseen.remove(current)
            current=image(g,current)
        count+=1
    return count

state=(1,0,1,0)
print("opposite-mark orbit:",sorted({move(g,state) for g in G}))
print("stabilizer:",[NAMES[g] for g in G if move(g,state)==state])
for q in [2,3]:
    fixed=[q**cycle_count(g) for g in G]
    classes=orbits(q,G)
    print("colors",q,"fixed counts",fixed)
    print("Burnside / enumeration:",sum(fixed)//len(G),len(classes))
    print("rotations only:",len(orbits(q,range(4))))
''')

add("quotients", "Check representative independence directly", "Why can the rotation subgroup be collapsed while {e,s} fails the same multiplication rule?", GROUP + COSETS + '''
def representative_independent(H):
    for g in G:
        for h in G:
            expected=left_coset(compose(g,h),H)
            for a in left_coset(g,H):
                for b in left_coset(h,H):
                    if left_coset(compose(a,b),H)!=expected:
                        return False
    return True

N={0,1,2,3}; H={0,4}
print("rotations give a well-defined product:",representative_independent(N))
print("{e,s} gives a well-defined product:",representative_independent(H))
print("same input coset:",names(left_coset(0,H)),names(left_coset(4,H)))
print("using e then right factor r:",names(left_coset(compose(0,1),H)))
print("using s then right factor r:",names(left_coset(compose(4,1),H)))
print("orientation preserves every product:",all(
    (-1)**(compose(g,h)//4)==(-1)**(g//4)*(-1)**(h//4) for g in G for h in G))
''')

MATRICES = '''
from fractions import Fraction

def matmul(A,B):
    return [[sum(A[i][k]*B[k][j] for k in range(len(B)))
        for j in range(len(B[0]))] for i in range(len(A))]

def matvec(A,x):
    return tuple(sum(a*b for a,b in zip(row,x)) for row in A)

def P(g):
    return [[int(j==image(g,i)) for i in range(4)] for j in range(4)]

def defect(W,g):
    left,right=matmul(W,P(g)),matmul(P(g),W)
    return max(abs(left[i][j]-right[i][j]) for i in range(4) for j in range(4))

def averaged(W,group=range(8)):
    group=tuple(group)
    result=[[Fraction(0) for _ in range(4)] for _ in range(4)]
    for g in group:
        term=matmul(matmul(P(inverse(g)),W),P(g))
        for i in range(4):
            for j in range(4):
                result[i][j]+=Fraction(term[i][j],len(group))
    return result
'''

add("representations", "One group, two different kinds of vector", "Does a scalar nonlinearity commute with both vertex permutations and geometric reflections?", GROUP + MATRICES + '''
vertices=[(1,0),(0,1),(-1,0),(0,-1)]
def R(g):
    x,y=vertices[image(g,0)],vertices[image(g,1)]
    return [[x[0],y[0]],[x[1],y[1]]]
print("geometric r:",R(1))
print("data permutation r:",P(1))
print("both preserve all 64 products:",all(
    matmul(R(g),R(h))==R(compose(g,h)) and
    matmul(P(g),P(h))==P(compose(g,h)) for g in G for h in G))
relu=lambda x:tuple(max(0,v) for v in x)
data=(-2,1,-3,4)
print("ReLU and every data permutation:",all(relu(move(g,data))==move(g,relu(data)) for g in G))
point=(-1,2); reflection=[[-1,0],[0,1]]
print("geometric reflect then ReLU:",relu(matvec(reflection,point)))
print("ReLU then geometric reflect:",matvec(reflection,relu(point)))
''')

add("tied", "Check the complete linear map, not one input", "Can a rotation-equivariant map fail reflection even if a constant input looks fine?", GROUP + MATRICES + '''
W=[[Fraction(2) if i==j else Fraction(1,2) if (i-j)%4 in [1,3] else Fraction(0)
    for j in range(4)] for i in range(4)]
x=(1,2,4,8)
print("tied output:",[str(v) for v in matvec(W,x)])
print("all-input D4 defect:",max(defect(W,g) for g in G))
shift=P(1)
print("shift rotation defect:",max(defect(shift,g) for g in range(4)))
print("shift reflection defect:",defect(shift,4))
print("constant input hides failure:",matvec(shift,move(4,(1,1,1,1)))==move(4,matvec(shift,(1,1,1,1))))
print("changed input routes:",matvec(shift,move(4,x)),move(4,matvec(shift,x)))
''')

add("averaging", "Average a map and verify the projection", "Does the exact average commute with every square transformation and stay unchanged when averaged again?", GROUP + MATRICES + '''
W=[[1,2,0,4],[0,1,3,0],[2,0,1,5],[0,6,0,1]]
A=averaged(W)
print("first tied row:",[str(v) for v in A[0]])
print("all-input defect:",max(defect(A,g) for g in G))
print("averaging again changes nothing:",averaged(A)==A)
T=[[2 if i==j else 1 if (i-j)%4 in [1,3] else 0 for j in range(4)] for i in range(4)]
sqnorm=lambda M:sum(v*v for row in M for v in row)
subtract=lambda X,Y:[[a-b for a,b in zip(x,y)] for x,y in zip(X,Y)]
print("Frobenius Pythagoras:",sqnorm(subtract(W,T))==sqnorm(subtract(W,A))+sqnorm(subtract(A,T)))
''')

add("modular", "Division depends on the arithmetic structure", "How many solutions does 2x=4 have modulo 5, 6 and 8?", '''
from math import gcd

def solve_congruence(a,b,n):
    if any(type(v) is not int for v in (a,b,n)) or not 2<=n<=100:
        raise ValueError("Use integer coefficients and a modulus from 2 to 100")
    return [x for x in range(n) if (a*x-b)%n==0]

for n in [5,6,8]:
    units=[a for a in range(n) if any(a*x%n==1 for x in range(n))]
    print("modulus",n,"units:",units)
    print("2x=4 solutions:",solve_congruence(2,4,n))
    print("unit/gcd test agrees:",units==[a for a in range(n) if gcd(a,n)==1])
print("zero-divisor witness mod 6:",2*3%6)
''')

add("capstone", "Audit an intentionally asymmetric four-sensor map", "What changes when a position-specific matrix is replaced by its D4 average?", GROUP + MATRICES + '''
W=[[2,2,4,8],[3,5,7,9],[6,10,11,12],[13,14,15,16]]
x=(1,2,4,8)
A=averaged(W)
print("raw all-input defect:",max(defect(W,g) for g in G))
print("repaired self / neighbor / opposite:",[str(v) for v in A[0][:3]])
print("repaired output:",[str(v) for v in matvec(A,x)])
print("repaired all-input defect:",max(defect(A,g) for g in G))
means={sum(matvec(A,move(g,x)),Fraction(0))/4 for g in G}
print("all transformed-input output means:",sorted(str(v) for v in means))
print("assumption: the four positions should obey the same processing rule")
''')

destination = ROOT / "src/learn/data/abstract-algebra-examples.js"
destination.write_text("export const abstractAlgebraExamples = " + json.dumps(examples, ensure_ascii=False, indent=2) + ";\n", encoding="utf-8")
print(json.dumps({"programs": len(examples), "outputs": {row["id"]: row["expected"] for row in examples}}, indent=2))
