"""Package the exact prepared programs and recompute GP teaching data.

Run with the retained lesson-tools Python; never install into that environment.
The checkpoint-bound draft is read only. --check compares with retained output.
"""
from pathlib import Path
import contextlib
import csv
import hashlib
import importlib.util
import io
import json
import re
import sys
import numpy as np
import scipy
import sklearn

ROOT = Path(__file__).resolve().parents[1]
PACKET = ROOT / "docs/teaching/drafts/gaussian-processes-gp"
DESTINATION = ROOT / "public/learn/examples/gaussian-processes-gp"
DATA = ROOT / "src/learn/data/gaussian-process-data.js"
EXAMPLES = ROOT / "src/learn/data/gaussian-process-examples.js"

def produce():
    manuscript = (PACKET / "lesson.md").read_text(encoding="utf-8")
    programs = re.findall(r"```python\n(.*?)\n```", manuscript, re.S)
    assert len(programs) == 2
    examples = []
    for filename, title, program in zip(
        ["gp_conditioning.py", "co2_gp.py"],
        ["Exact conditioning with triangular solves", "A fixed historical forecast"], programs
    ):
        output = io.StringIO()
        with contextlib.redirect_stdout(output):
            exec(compile(program, filename, "exec"), {"__name__": "__main__", "__file__": str(PACKET / filename)})
        examples.append({"file": filename, "title": title, "code": program, "expected": output.getvalue().rstrip()})
    spec = importlib.util.spec_from_file_location("gp_packet_calculation", PACKET / "author-calculations.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    checked = {"tiny": module.tiny(), "real": module.real()}
    original = json.loads((PACKET / "checked-results.json").read_text())
    def compare(a, b, path="root"):
        if isinstance(a, dict):
            assert a.keys() == b.keys(), path
            for key in a: compare(a[key], b[key], path + "." + key)
        elif isinstance(a, list):
            assert len(a) == len(b), path
            for i, value in enumerate(a): compare(value, b[i], path + f"[{i}]")
        elif isinstance(a, (int, float)) and not isinstance(a, bool):
            assert np.isclose(a, b, rtol=1e-8, atol=1e-9), (path, a, b)
        else: assert a == b, (path, a, b)
    compare(checked, original)
    rows = []
    with (PACKET / "mauna-loa-monthly.csv").open() as handle:
        for row in csv.DictReader(handle):
            year, month = int(row["year"]), int(row["month"])
            rows.append({"month": f"{year}-{month:02}", "x": year - 1990 + (month - .5) / 12, "co2": float(row["co2_ppm"])})
    # Only the actual browser inputs and drawn series enter the topic bundle.
    browser = {"tiny": checked["tiny"], "real": {key: value for key, value in checked["real"].items() if key != "explorer"}, "observations": rows}
    files = {
        DATA: "// Generated by scripts/prepare-gaussian-process-data.py; lesson-scoped.\nexport const gaussianProcessData = " + json.dumps(browser, ensure_ascii=False, separators=(",", ":")) + ";\n",
        EXAMPLES: "// Exact executed manuscript programs, with complete captured stdout.\nexport const gaussianProcessExamples = " + json.dumps(examples, ensure_ascii=False, indent=2) + ";\n",
        DESTINATION / "mauna-loa-monthly.csv": (PACKET / "mauna-loa-monthly.csv").read_text(),
        DESTINATION / "README.md": (PACKET / "data-provenance.md").read_text(encoding="utf-8"),
    }
    for example in examples: files[DESTINATION / example["file"]] = example["code"] + "\n"
    for path, text in files.items():
        if "--check" in sys.argv:
            assert path.read_text(encoding="utf-8") == text, f"Stale artifact: {path}"
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
    receipt = {
        "programsExecuted": [example["file"] for example in examples],
        "python": sys.version.split()[0], "numpy": np.__version__, "scipy": scipy.__version__, "sklearn": sklearn.__version__,
        "packetResultsReproduced": True,
        "files": {str(path.relative_to(ROOT)).replace("\\", "/"): hashlib.sha256(path.read_bytes()).hexdigest() for path in files},
    }
    if "--check" not in sys.argv:
        (ROOT / "docs/teaching/evidence/gaussian-process-native.json").write_text(json.dumps(receipt, indent=2) + "\n")
    print(json.dumps(receipt, indent=2))

if __name__ == "__main__": produce()
