"""Execute the exact three downloadable teaching programs; no data/network fetch."""
from pathlib import Path
import hashlib
import json
import platform
import shutil
import subprocess
import sys

import numpy
import scipy
import sklearn

ROOT = Path(__file__).resolve().parents[1]
PACKET = ROOT / "docs/teaching/drafts/semi-supervised-learning-label-propagation-self-training-co-training"
ASSETS = ROOT / "public/learn-assets/semi-supervised-learning"
ASSETS.mkdir(parents=True, exist_ok=True)
FILES = ["graph-solutions.py", "cotrain-categories.py", "banknote-experiment.py", "banknote-subset.csv", "data-provenance.md"]
for name in FILES:
    shutil.copyfile(PACKET / name, ASSETS / name)

programs = []
for name in FILES[:3]:
    result = subprocess.run([sys.executable, str(ASSETS / name)], capture_output=True, text=True, check=True, timeout=120)
    assert not result.stderr.strip(), result.stderr
    programs.append({"file": name, "code": (ASSETS / name).read_text(encoding="utf-8"), "expected": result.stdout.strip()})

assert "[0.333333 0.666667]" in programs[0]["expected"]
assert "[0.197531 0.37037  0.62963  0.802469]" in programs[0]["expected"]
assert "duplicate-view unresolved [3, 4, 5]" in programs[1]["expected"]
banknote = programs[2]["expected"]
for line in ["supervised_lr 72 / 80", "supervised_knn 63 / 80", "spreading_0.25 61 / 80", "spreading_1.0 59 / 80", "spreading_4.0 65 / 80", "self_0.8 59 / 80", "self_0.95 72 / 80", "selected supervised_lr test 72 / 80", "threshold 0.8 accepted [48, 106, 60, 18, 11, 6, 3, 0]", "wrong in offline audit [0, 12, 28, 14, 10, 6, 3, 0]", "threshold 0.95 accepted [0]"]:
    assert line in banknote, line

titles = ["Hard propagation and soft spreading are different solves", "Two categorical views exchange recipient-side labels", "Run the banknote experiment and retain the losing results"]
for entry, title in zip(programs, titles):
    entry["title"] = title
    entry["language"] = "python"
    entry["download"] = "/learn-assets/semi-supervised-learning/" + entry["file"]

output = "// Generated by scripts/verify-semi-supervised-native.py from executed topic-owned programs.\nexport const semiSupervisedExamples = " + json.dumps(programs, indent=2) + ";\n"
(ROOT / "src/learn/data/semi-supervised-examples.js").write_text(output, encoding="utf-8")
evidence = {
    "status": "passed", "python": platform.python_version(),
    "versions": {"numpy": numpy.__version__, "scipy": scipy.__version__, "scikit-learn": sklearn.__version__},
    "command": "scratch/lesson-tools/Scripts/python.exe scripts/verify-semi-supervised-native.py",
    "programs": [{"file": entry["file"], "stdout": entry["expected"]} for entry in programs],
    "sourceHashes": {str((ASSETS / name).relative_to(ROOT)).replace("\\", "/"): hashlib.sha256((ASSETS / name).read_bytes()).hexdigest() for name in FILES},
    "limits": "One retained banknote subset and seed policy; optional deep methods were not trained. No external dataset was fetched.",
}
(ROOT / "docs/teaching/evidence/semi-supervised-native.json").write_text(json.dumps(evidence, indent=2) + "\n", encoding="utf-8")
print("Passed: all three exact downloadable programs; graph, co-training and banknote outputs match the prepared packet.")
